import java.util.Map;
import java.util.TreeMap;


public class ActsData {
	static public Map<ActCode, ActContent> getActsMap()
	{
		if (entries == null)
			entries =  buildActsMap();
		return entries;
	}
	static public void save()
	{
		ActViewsData.fillWithActs(getActsMap());
		ActViewsData.saveActViewsInfo();
	}
	static private Map<ActCode, ActContent> buildActsMap()
	{
		Map<ActCode, ActContent> entries = buildRawActsMap();
		Map<ActCode, Integer> viewsEntries = ActViewsData.getActViewsInfo();
		for (Map.Entry<ActCode, Integer> viewEntry : viewsEntries.entrySet())
		{
			ActContent rawContent = entries.get(viewEntry.getKey());
			if (rawContent != null)
			{
				rawContent.setTimesViewed(viewEntry.getValue());
			}
		}
		return entries;
	}
	static private Map<ActCode, ActContent> buildRawActsMap()
	{
      Map<ActCode, ActContent> builtEntries = new TreeMap<ActCode, ActContent>();
      builtEntries.put(new ActCode("HBGD011"), new ActContent("Ablation  d'un bloc métallique coulé ou d'une prothèse dentaire à tenon radiculaire scellé", 38.7));
      builtEntries.put(new ActCode("HBGD009"), new ActContent("Ablation  d'une prothèse dentaire implantoportée", 0));
      builtEntries.put(new ActCode("HBGD027"), new ActContent("Ablation  d'une prothèse dentaire scellée unitaire", 38.7));
      builtEntries.put(new ActCode("HBGD005"), new ActContent("Ablation d’un ancrage coronoradiculaire", 0));
      builtEntries.put(new ActCode("HBGD012"), new ActContent("Ablation de corps étranger  d'un canal radiculaire d'une dent", 0));
      builtEntries.put(new ActCode("LBGD001"), new ActContent("Ablation de moyen de contention maxillaire et/ou mandibulaire intrabuccal", 0));
      builtEntries.put(new ActCode("HBMD017"), new ActContent("Adjonction ou changement d'1 élément d'une prothèse dentaire amovible ", 21.5));
      builtEntries.put(new ActCode("HBMD249"), new ActContent("Adjonction ou changement d'1 élément soudé sur une prothèse dentaire amovible sur châssis métallique", 43));
      builtEntries.put(new ActCode("HBMD329"), new ActContent("Adjonction ou changement de 10 éléments d'une prothèse dentaire amovible", 118.25));
      builtEntries.put(new ActCode("HBMD410"), new ActContent("Adjonction ou changement de 10 éléments soudés d'une prothèse dentaire amovible sur châssis métallique", 430));
      builtEntries.put(new ActCode("HBMD226"), new ActContent("Adjonction ou changement de 11 éléments d'une prothèse dentaire amovible", 129));
      builtEntries.put(new ActCode("HBMD429"), new ActContent("Adjonction ou changement de 11 éléments soudés d'une prothèse dentaire amovible sur châssis métallique", 473));
      builtEntries.put(new ActCode("HBMD387"), new ActContent("Adjonction ou changement de 12 éléments d'une prothèse dentaire amovible", 139.75));
      builtEntries.put(new ActCode("HBMD281"), new ActContent("Adjonction ou changement de 12 éléments soudés d'une prothèse dentaire amovible sur châssis métallique", 516));
      builtEntries.put(new ActCode("HBMD134"), new ActContent("Adjonction ou changement de 13 éléments d'une prothèse dentaire amovible", 150.5));
      builtEntries.put(new ActCode("HBMD200"), new ActContent("Adjonction ou changement de 13 éléments soudés d'une prothèse dentaire amovible sur châssis métallique", 559));
      builtEntries.put(new ActCode("HBMD174"), new ActContent("Adjonction ou changement de 14 éléments d'une prothèse dentaire amovible", 161.25));
      builtEntries.put(new ActCode("HBMD298"), new ActContent("Adjonction ou changement de 14 éléments soudés d'une prothèse dentaire amovible sur châssis métallique", 602));
      builtEntries.put(new ActCode("HBMD114"), new ActContent("Adjonction ou changement de 2 éléments d'une prothèse dentaire amovible", 32.25));
      builtEntries.put(new ActCode("HBMD292"), new ActContent("Adjonction ou changement de 2 éléments soudés d'une prothèse dentaire amovible sur châssis métallique", 86));
      builtEntries.put(new ActCode("HBMD322"), new ActContent("Adjonction ou changement de 3 éléments d'une prothèse dentaire amovible", 43));
      builtEntries.put(new ActCode("HBMD188"), new ActContent("Adjonction ou changement de 3 éléments soudés d'une prothèse dentaire amovible sur châssis métallique", 129));
      builtEntries.put(new ActCode("HBMD404"), new ActContent("Adjonction ou changement de 4 éléments d'une prothèse dentaire amovible", 53.75));
      builtEntries.put(new ActCode("HBMD432"), new ActContent("Adjonction ou changement de 4 éléments soudés d'une prothèse dentaire amovible sur châssis métallique", 172));
      builtEntries.put(new ActCode("HBMD245"), new ActContent("Adjonction ou changement de 5 éléments d'une prothèse dentaire amovible", 64.5));
      builtEntries.put(new ActCode("HBMD283"), new ActContent("Adjonction ou changement de 5 éléments soudés d'une prothèse dentaire amovible sur châssis métallique", 215));
      builtEntries.put(new ActCode("HBMD198"), new ActContent("Adjonction ou changement de 6 éléments d'une prothèse dentaire amovible", 75.25));
      builtEntries.put(new ActCode("HBMD439"), new ActContent("Adjonction ou changement de 6 éléments soudés d'une prothèse dentaire amovible sur châssis métallique", 258));
      builtEntries.put(new ActCode("HBMD373"), new ActContent("Adjonction ou changement de 7 éléments d'une prothèse dentaire amovible", 86));
      builtEntries.put(new ActCode("HBMD425"), new ActContent("Adjonction ou changement de 7 éléments soudés d'une prothèse dentaire amovible sur châssis métallique", 301));
      builtEntries.put(new ActCode("HBMD228"), new ActContent("Adjonction ou changement de 8 éléments d'une prothèse dentaire amovible", 96.75));
      builtEntries.put(new ActCode("HBMD444"), new ActContent("Adjonction ou changement de 8 éléments soudés d'une prothèse dentaire amovible sur châssis métallique", 344));
      builtEntries.put(new ActCode("HBMD286"), new ActContent("Adjonction ou changement de 9 éléments d'une prothèse dentaire amovible", 107.5));
      builtEntries.put(new ActCode("HBMD485"), new ActContent("Adjonction ou changement de 9 éléments soudés d'une prothèse dentaire amovible sur châssis métallique", 387));
      builtEntries.put(new ActCode("HBFD014"), new ActContent("Amputation et/ou séparation radiculaire ou coronoradiculaire d'une dent", 0));
      builtEntries.put(new ActCode("HBLD009"), new ActContent("Application d’un topique pour hypersensibilité dentinaire", 0));
      builtEntries.put(new ActCode("HBLD045"), new ActContent("Application dentaire d’un vernis de reminéralisation sur une arcade", 0));
      builtEntries.put(new ActCode("HBED022"), new ActContent("Autogreffe d'un germe ou d'une dent retenue, dans un site naturel ou préparé chirurgicalement", 209));
      builtEntries.put(new ActCode("HBED005"), new ActContent("Autogreffe d'une dent sur arcade, dans un site naturel ou préparé chirurgicalement", 0));
      builtEntries.put(new ActCode("HBGD042"), new ActContent("Avulsion d’1 dent temporaire retenue, incluse ou réincluse", 83.6));
      builtEntries.put(new ActCode("HBGD039"), new ActContent("Avulsion d'1 dent ankylosée sur arcade, avec section coronoradiculaire et séparation des racines", 33.44));
      builtEntries.put(new ActCode("HBGD022"), new ActContent("Avulsion d'1 dent permanente sur arcade avec alvéolectomie", 33.44));
      builtEntries.put(new ActCode("HBGD031"), new ActContent("Avulsion d'1 dent permanente sur arcade avec séparation des racines", 33.44));
      builtEntries.put(new ActCode("HBGD036"), new ActContent("Avulsion d'1 dent permanente sur arcade sans alvéolectomie", 33.44));
      builtEntries.put(new ActCode("HBGD035"), new ActContent("Avulsion d'1 dent temporaire sur arcade", 16.72));
      builtEntries.put(new ActCode("HBGD064"), new ActContent("Avulsion de 10 dents permanentes sur arcade sans alvéolectomie", 183.92));
      builtEntries.put(new ActCode("HBGD093"), new ActContent("Avulsion de 10 dents temporaires sur arcade", 91.96));
      builtEntries.put(new ActCode("HBGD356"), new ActContent("Avulsion de 11 dents permanentes sur arcade sans alvéolectomie", 200.64));
      builtEntries.put(new ActCode("HBGD362"), new ActContent("Avulsion de 11 dents temporaires sur arcade", 100.32));
      builtEntries.put(new ActCode("HBGD146"), new ActContent("Avulsion de 12 dents permanentes sur arcade sans alvéolectomie", 217.36));
      builtEntries.put(new ActCode("HBGD054"), new ActContent("Avulsion de 12 dents temporaires sur arcade", 108.68));
      builtEntries.put(new ActCode("HBGD382"), new ActContent("Avulsion de 13 dents permanentes sur arcade sans alvéolectomie", 234.08));
      builtEntries.put(new ActCode("HBGD111"), new ActContent("Avulsion de 13 dents temporaires sur arcade", 117.04));
      builtEntries.put(new ActCode("HBGD247"), new ActContent("Avulsion de 14 dents permanentes sur arcade sans alvéolectomie", 250.8));
      builtEntries.put(new ActCode("HBGD174"), new ActContent("Avulsion de 14 dents temporaires sur arcade", 125.4));
      builtEntries.put(new ActCode("HBGD197"), new ActContent("Avulsion de 15 dents permanente sur arcade sans alvéolectomie", 267.52));
      builtEntries.put(new ActCode("HBGD057"), new ActContent("Avulsion de 15 dents temporaires sur arcade", 133.76));
      builtEntries.put(new ActCode("HBGD333"), new ActContent("Avulsion de 16 dents permanente sur arcade sans alvéolectomie", 284.24));
      builtEntries.put(new ActCode("HBGD133"), new ActContent("Avulsion de 16 dents temporaires sur arcade", 142.12));
      builtEntries.put(new ActCode("HBGD261"), new ActContent("Avulsion de 17 dents permanentes sur arcade sans alvéolectomie", 300.96));
      builtEntries.put(new ActCode("HBGD123"), new ActContent("Avulsion de 17 dents temporaires sur arcade", 150.48));
      builtEntries.put(new ActCode("HBGD499"), new ActContent("Avulsion de 18 dents permanentes sur arcade sans alvéolectomie", 317.68));
      builtEntries.put(new ActCode("HBGD468"), new ActContent("Avulsion de 18 dents temporaires sur arcade", 158.84));
      builtEntries.put(new ActCode("HBGD461"), new ActContent("Avulsion de 19 dents permanentes sur arcade sans alvéolectomie", 334.4));
      builtEntries.put(new ActCode("HBGD015"), new ActContent("Avulsion de 2 canines permanentes  retenues ou à l'état de germe", 156.75));
      builtEntries.put(new ActCode("HBGD002"), new ActContent("Avulsion de 2 dents ankylosées sur arcade, avec section coronoradiculaire et séparation des racines", 50.16));
      builtEntries.put(new ActCode("HBGD034"), new ActContent("Avulsion de 2 dents permanentes sur arcade avec alvéolectomie", 50.16));
      builtEntries.put(new ActCode("HBGD032"), new ActContent("Avulsion de 2 dents permanentes sur arcade avec séparation des racines", 50.16));
      builtEntries.put(new ActCode("HBGD043"), new ActContent("Avulsion de 2 dents permanentes sur arcade sans alvéolectomie", 50.16));
      builtEntries.put(new ActCode("HBGD026"), new ActContent("Avulsion de 2 dents temporaires retenues, incluses ou réincluses", 125.4));
      builtEntries.put(new ActCode("HBGD037"), new ActContent("Avulsion de 2 dents temporaires sur arcade", 25.08));
      builtEntries.put(new ActCode("HBGD386"), new ActContent("Avulsion de 2 prémolaires retenues ou à l'état de germe", 125.4));
      builtEntries.put(new ActCode("HBGD025"), new ActContent("Avulsion de 2 troisièmes molaires retenues ou à l'état de germe", 125.4));
      builtEntries.put(new ActCode("HBGD278"), new ActContent("Avulsion de 20 dents permanentes sur arcade sans alvéolectomie", 351.12));
      builtEntries.put(new ActCode("HBGD201"), new ActContent("Avulsion de 20 dents temporaires sur arcade", 175.56));
      builtEntries.put(new ActCode("HBGD258"), new ActContent("Avulsion de 21 dents permanentes sur arcade sans alvéolectomie", 367.84));
      builtEntries.put(new ActCode("HBGD311"), new ActContent("Avulsion de 22 dents permanentes sur arcade sans alvéolectomie", 384.56));
      builtEntries.put(new ActCode("HBGD235"), new ActContent("Avulsion de 23 dents permanentes sur arcade sans alvéolectomie", 401.28));
      builtEntries.put(new ActCode("HBGD374"), new ActContent("Avulsion de 24 dents permanentes sur arcade sans alvéolectomie", 418));
      builtEntries.put(new ActCode("HBGD475"), new ActContent("Avulsion de 25 dents permanentes sur arcade sans alvéolectomie", 434.72));
      builtEntries.put(new ActCode("HBGD285"), new ActContent("Avulsion de 26 dents permanentes sur arcade sans alvéolectomie", 451.44));
      builtEntries.put(new ActCode("HBGD338"), new ActContent("Avulsion de 27 dents permanentes sur arcade sans alvéolectomie", 468.16));
      builtEntries.put(new ActCode("HBGD193"), new ActContent("Avulsion de 28 dents permanentes sur arcade sans alvéolectomie", 484.88));
      builtEntries.put(new ActCode("HBGD345"), new ActContent("Avulsion de 29 dents permanentes sur arcade sans alvéolectomie", 501.6));
      builtEntries.put(new ActCode("HBGD287"), new ActContent("Avulsion de 3 dents permanentes sur arcade avec alvéolectomie", 66.88));
      builtEntries.put(new ActCode("HBGD319"), new ActContent("Avulsion de 3 dents permanentes sur arcade sans alvéolectomie", 66.88));
      builtEntries.put(new ActCode("HBGD309"), new ActContent("Avulsion de 3 dents temporaires sur arcade", 33.44));
      builtEntries.put(new ActCode("HBGD021"), new ActContent("Avulsion de 3 troisièmes molaires retenues ou à l'état de germe", 167.2));
      builtEntries.put(new ActCode("HBGD414"), new ActContent("Avulsion de 30 dents permanentes sur arcade sans alvéolectomie", 518.32));
      builtEntries.put(new ActCode("HBGD245"), new ActContent("Avulsion de 31 dents permanentes sur arcade sans alvéolectomie", 535.04));
      builtEntries.put(new ActCode("HBGD283"), new ActContent("Avulsion de 32 dents permanentes sur arcade sans alvéolectomie", 551.76));
      builtEntries.put(new ActCode("HBGD489"), new ActContent("Avulsion de 4 dents permanentes sur arcade sans alvéolectomie", 83.6));
      builtEntries.put(new ActCode("HBGD284"), new ActContent("Avulsion de 4 dents temporaires sur arcade", 41.8));
      builtEntries.put(new ActCode("HBGD038"), new ActContent("Avulsion de 4 troisièmes molaires retenues ou à l'état de germe", 209));
      builtEntries.put(new ActCode("HBGD497"), new ActContent("Avulsion de 5 dents permanentes sur arcade sans alvéolectomie", 100.32));
      builtEntries.put(new ActCode("HBGD065"), new ActContent("Avulsion de 5 dents temporaires sur arcade", 50.16));
      builtEntries.put(new ActCode("HBGD106"), new ActContent("Avulsion de 6 dents permanentes sur arcade sans alvéolectomie", 117.04));
      builtEntries.put(new ActCode("HBGD462"), new ActContent("Avulsion de 6 dents temporaires sur arcade", 58.52));
      builtEntries.put(new ActCode("HBGD076"), new ActContent("Avulsion de 7 dents permanentes sur arcade sans alvéolectomie", 133.76));
      builtEntries.put(new ActCode("HBGD464"), new ActContent("Avulsion de 7 dents temporaires sur arcade", 66.88));
      builtEntries.put(new ActCode("HBGD422"), new ActContent("Avulsion de 8 dents permanentes sur arcade sans alvéolectomie", 150.48));
      builtEntries.put(new ActCode("HBGD263"), new ActContent("Avulsion de 8 dents temporaires sur arcade", 75.24));
      builtEntries.put(new ActCode("HBGD420"), new ActContent("Avulsion de 9 dents permanentes sur arcade sans alvéolectomie", 167.2));
      builtEntries.put(new ActCode("HBGD280"), new ActContent("Avulsion de 9 dents temporaires sur arcade", 83.6));
      builtEntries.put(new ActCode("HBGD040"), new ActContent("Avulsion de plusieurs dents surnuméraires à l'état de germe ou de plusieurs odontoïdes", 125.4));
      builtEntries.put(new ActCode("HBGD282"), new ActContent("Avulsion de19 dents temporaires sur arcade", 167.2));
      builtEntries.put(new ActCode("HBGD003"), new ActContent("Avulsion d'un odontoïde inclus ou d'une dent surnuméraire à l'état de germe", 83.6));
      builtEntries.put(new ActCode("HBGD014"), new ActContent("Avulsion d'une canine permanente retenue ou à l'état de germe", 104.5));
      builtEntries.put(new ActCode("HBGD044"), new ActContent("Avulsion d'une dent à couronne sousmuqueuse ou en désinclusion muqueuse", 41.8));
      builtEntries.put(new ActCode("HBGD017"), new ActContent("Avulsion d'une dent ectopique", 167.2));
      builtEntries.put(new ActCode("HBGD028"), new ActContent("Avulsion d'une incisive permanente retenue ou à l'état de germe", 83.6));
      builtEntries.put(new ActCode("HBGD047"), new ActContent("Avulsion d'une première ou d'une deuxième molaire permanente retenue ou à l'état de germe", 83.6));
      builtEntries.put(new ActCode("HBGD459"), new ActContent("Avulsion d'une prémolaire retenue ou à l'état de germe ", 83.6));
      builtEntries.put(new ActCode("HBGD016"), new ActContent("Avulsion d'une racine incluse", 83.6));
      builtEntries.put(new ActCode("HBGD004"), new ActContent("Avulsion d'une troisième molaire mandibulaire retenue ou à l'état de germe", 83.6));
      builtEntries.put(new ActCode("HBGD018"), new ActContent("Avulsion d'une troisième molaire maxillaire retenue ou à l'état de germe", 83.6));
      builtEntries.put(new ActCode("HBKD396"), new ActContent("Changement d'1 facette d'une prothèse dentaire amovible", 17.2));
      builtEntries.put(new ActCode("HBKD431"), new ActContent("Changement de 2 facettes d'une prothèse dentaire amovible ", 34.4));
      builtEntries.put(new ActCode("HBKD300"), new ActContent("Changement de 3 facettes d'une prothèse dentaire amovible ", 51.6));
      builtEntries.put(new ActCode("HBKD212"), new ActContent("Changement de 4 facettes d'une prothèse dentaire amovible ", 68.8));
      builtEntries.put(new ActCode("HBKD462"), new ActContent("Changement de 5 facettes d'une prothèse dentaire amovible ", 86));
      builtEntries.put(new ActCode("HBKD213"), new ActContent("Changement de 6 facettes d'une prothèse dentaire amovible ", 103.2));
      builtEntries.put(new ActCode("HBKD140"), new ActContent("Changement de 7 facettes d'une prothèse dentaire amovible ", 120.4));
      builtEntries.put(new ActCode("HBKD244"), new ActContent("Changement de 8 facettes d'une prothèse dentaire amovible ", 137.6));
      builtEntries.put(new ActCode("HBKD005"), new ActContent("Changement de dispositif d'attachement d'une prothèse dentaire amovible supra implantaire", 32.25));
      builtEntries.put(new ActCode("HBBD005"), new ActContent("Comblement [Scellement] prophylactique des puits, sillons et fissures sur 1 dent", 21.69));
      builtEntries.put(new ActCode("HBBD006"), new ActContent("Comblement [Scellement] prophylactique des puits, sillons et fissures sur 2 dents", 43.38));
      builtEntries.put(new ActCode("HBBD007"), new ActContent("Comblement [Scellement] prophylactique des puits, sillons et fissures sur 3 dents", 65.07));
      builtEntries.put(new ActCode("HBBD004"), new ActContent("Comblement [Scellement] prophylactique des puits, sillons et fissures sur 4 dents", 86.76));
      builtEntries.put(new ActCode("HBBD039"), new ActContent("Comblement [Scellement] prophylactique des puits, sillons et fissures sur 5 dents", 108.45));
      builtEntries.put(new ActCode("HBBD404"), new ActContent("Comblement [Scellement] prophylactique des puits, sillons et fissures sur 6 dents", 130.14));
      builtEntries.put(new ActCode("HBBD098"), new ActContent("Comblement [Scellement] prophylactique des puits, sillons et fissures sur 7 dents", 151.83));
      builtEntries.put(new ActCode("HBBD427"), new ActContent("Comblement [Scellement] prophylactique des puits, sillons et fissures sur 8 dents", 173.52));
      builtEntries.put(new ActCode("HBPD001"), new ActContent("Dégagement de plusieurs dents retenues ou incluses avec pose de dispositif de traction orthodontique", 156.75));
      builtEntries.put(new ActCode("HBPD002"), new ActContent("Dégagement d'une dent retenue ou incluse avec pose d'un dispositif de traction orthodontique sans aménagement parodontal", 104.5));
      builtEntries.put(new ActCode("HBPA001"), new ActContent("Dégagement d'une dent retenue ou incluse, avec pose d'un dispositif de traction orthodontique et aménagement parodontal par greffe ou lambeau", 146.3));
      builtEntries.put(new ActCode("HBGD233"), new ActContent("Désobturation endodontique d’une première prémolaire maxillaire", 0));
      builtEntries.put(new ActCode("HBGD001"), new ActContent("Désobturation endodontique d’une prémolaire autre que la première prémolaire maxillaire", 0));
      builtEntries.put(new ActCode("HBGD030"), new ActContent("Désobturation endodontique d'une incisive ou d'une canine", 0));
      builtEntries.put(new ActCode("HBGD033"), new ActContent("Désobturation endodontique d'une molaire", 0));
      builtEntries.put(new ActCode("HBJD001"), new ActContent("Détartrage et polissage des dents", 28.92));
      builtEntries.put(new ActCode("HBMD001"), new ActContent("Eclaircissement de dent dépulpée", 0));
      builtEntries.put(new ActCode("HBMD005"), new ActContent("Eclaircissement des dents pulpées", 0));
      builtEntries.put(new ActCode("HBFD006"), new ActContent("Exérèse de la pulpe camérale [Biopulpotomie] d'une dent temporaire", 16.87));
      builtEntries.put(new ActCode("HBFD033"), new ActContent("Exérèse de la pulpe vivante d’une incisive ou d’une canine permanente", 33.74));
      builtEntries.put(new ActCode("HBFD017"), new ActContent("Exérèse de la pulpe vivante d’une incisive ou d’une canine temporaire", 33.74));
      builtEntries.put(new ActCode("HBFD008"), new ActContent("Exérèse de la pulpe vivante d’une molaire permanente", 81.94));
      builtEntries.put(new ActCode("HBFD019"), new ActContent("Exérèse de la pulpe vivante d’une molaire temporaire", 81.94));
      builtEntries.put(new ActCode("HBFD021"), new ActContent("Exérèse de la pulpe vivante d’une première prémolaire maxillaire", 48.2));
      builtEntries.put(new ActCode("HBFD035"), new ActContent("Exérèse de la pulpe vivante d’une prémolaire autre que la première prémolaire maxillaire", 48.2));
      builtEntries.put(new ActCode("HBFD001"), new ActContent("Exérèse du contenu canalaire non vivant d’une incisive ou d’une canine permanente", 33.74));
      builtEntries.put(new ActCode("HBFD458"), new ActContent("Exérèse du contenu canalaire non vivant d’une incisive ou d'une canine permanente immature", 33.74));
      builtEntries.put(new ActCode("HBFD024"), new ActContent("Exérèse du contenu canalaire non vivant d’une molaire permanente", 81.94));
      builtEntries.put(new ActCode("HBFD150"), new ActContent("Exérèse du contenu canalaire non vivant d’une molaire permanente immature", 81.94));
      builtEntries.put(new ActCode("HBFD297"), new ActContent("Exérèse du contenu canalaire non vivant d’une première prémolaire maxillaire", 48.2));
      builtEntries.put(new ActCode("HBFD395"), new ActContent("Exérèse du contenu canalaire non vivant d’une première prémolaire maxillaire immature", 48.2));
      builtEntries.put(new ActCode("HBFD003"), new ActContent("Exérèse du contenu canalaire non vivant d’une prémolaire autre que la première prémolaire maxillaire", 48.2));
      builtEntries.put(new ActCode("HBFD326"), new ActContent("Exérèse du contenu canalaire non vivant d’une prémolaire immature autre que la première prémolaire maxillaire ", 48.2));
      builtEntries.put(new ActCode("HBFD015"), new ActContent("Exérèse du contenu canalaire non vivant d'une incisive ou d'une canine temporaire", 33.74));
      builtEntries.put(new ActCode("HBFD474"), new ActContent("Exérèse du contenu canalaire non vivant d'une molaire temporaire", 81.94));
      builtEntries.put(new ActCode("HBFD032"), new ActContent("Exérèse partielle de la pulpe vivante d'une dent permanente immature pour apexogénèse", 0));
      builtEntries.put(new ActCode("HBBA001"), new ActContent("Obturation d’une résorption radiculaire dentaire externe, par abord parodontal", 0));
      builtEntries.put(new ActCode("HBBD003"), new ActContent("Obturation radiculaire d'une incisive ou d'une canine après apexification", 33.74));
      builtEntries.put(new ActCode("HBBD002"), new ActContent("Obturation radiculaire d'une molaire après apexification", 81.94));
      builtEntries.put(new ActCode("HBBD234"), new ActContent("Obturation radiculaire d'une première prémolaire maxillaire  après apexification", 48.2));
      builtEntries.put(new ActCode("HBBD001"), new ActContent("Obturation radiculaire d'une prémolaire autre que la première prémolaire maxillaire après apexification", 48.2));
      builtEntries.put(new ActCode("HBFD010"), new ActContent("Parage de plaie de la pulpe d'une dent avec coiffage", 0));
      builtEntries.put(new ActCode("HBLD003"), new ActContent("Pose d’un arc de maintien d’espace interdentaire avec dent prothétique", 0));
      builtEntries.put(new ActCode("HBLD001"), new ActContent("Pose d’un arc de maintien d’espace interdentaire sans dent prothétique", 0));
      builtEntries.put(new ActCode("HBLD052"), new ActContent("Pose d’un dispositif unimaxillaire de contention extracoronaire par attelle composite collée, sur 1 à 6 dents", 0));
      builtEntries.put(new ActCode("HBLD050"), new ActContent("Pose d’un dispositif unimaxillaire de contention extracoronaire par attelle composite collée, sur 7 dents ou plus", 0));
      builtEntries.put(new ActCode("HBLD053"), new ActContent("Pose d’un dispositif unimaxillaire de contention extracoronaire par attelle métallique coulée et collée, sur 1 à 6 dents", 96.4));
      builtEntries.put(new ActCode("HBLD051"), new ActContent("Pose d’un dispositif unimaxillaire de contention extracoronaire par attelle métallique coulée et collée, sur 7 dents ou plus", 96.4));
      builtEntries.put(new ActCode("HBLD002"), new ActContent("Pose d’un mainteneur d’espace interdentaire amovible passif", 0));
      builtEntries.put(new ActCode("HBLD006"), new ActContent("Pose d’un mainteneur d’espace interdentaire unitaire scellé", 0));
      builtEntries.put(new ActCode("HBLD236"), new ActContent("Pose d’une prothèse amovible supra-implantaire à chassis métallique  comportant de 9 à 13 dents ", 279.5));
      builtEntries.put(new ActCode("HBLD240"), new ActContent("Pose d’une prothèse amovible supra-implantaire à chassis métallique  comportant moins de 9 dents ", 236.5));
      builtEntries.put(new ActCode("HBLD132"), new ActContent("Pose d’une prothèse amovible supra-implantaire à plaque résine comportant moins de 9 dents ", 102.125));
      builtEntries.put(new ActCode("HBLD171"), new ActContent("Pose d’une prothèse amovible supra-implantaire complète bimaxillaire à chassis métallique ", 623.5));
      builtEntries.put(new ActCode("HBLD217"), new ActContent("Pose d’une prothèse amovible supra-implantaire complète unimaxillaire à chassis métallique", 311.75));
      builtEntries.put(new ActCode("HBLD034"), new ActContent("Pose d’une prothèse dentaire plurale transitoire ", 0));
      builtEntries.put(new ActCode("HBLD017"), new ActContent("Pose d'infrastructure coronaire sur 2 implants", 0));
      builtEntries.put(new ActCode("HBLD021"), new ActContent("Pose d'infrastructure coronaire sur 3 implants", 0));
      builtEntries.put(new ActCode("HBLD013"), new ActContent("Pose d'infrastructure coronaire sur 4 implants", 0));
      builtEntries.put(new ActCode("HBLD005"), new ActContent("Pose d'infrastructure coronaire sur 5 implants ou plus", 0));
      builtEntries.put(new ActCode("HBLD020"), new ActContent("Pose d'un appareil de posture mandibulaire [cale]", 0));
      builtEntries.put(new ActCode("HBLD008"), new ActContent("Pose d'un attachement coronoradiculaire sur une dent", 0));
      builtEntries.put(new ActCode("HBLD019"), new ActContent("Pose d'un plan de guidage des mouvements antéropostérieurs mandibulaires", 0));
      builtEntries.put(new ActCode("HBLD018"), new ActContent("Pose d'un plan de libération occlusale", 172.8));
      builtEntries.put(new ActCode("HBLD015"), new ActContent("Pose d'une coiffe de recouvrement d'une racine dentaire [Coping]", 0));
      builtEntries.put(new ActCode("HBLD036"), new ActContent("Pose d'une couronne dentaire dentoportée céramométallique ou en équivalents minéraux ", 107.5));
      builtEntries.put(new ActCode("HBLD038"), new ActContent("Pose d'une couronne dentaire dentoportée métallique ", 107.5));
      builtEntries.put(new ActCode("HBLD418"), new ActContent("Pose d'une couronne dentaire implantoportée", 107.5));
      builtEntries.put(new ActCode("HBLD037"), new ActContent("Pose d'une couronne dentaire transitoire ", 0));
      builtEntries.put(new ActCode("HBMD048"), new ActContent("Pose d'une facette céramique ou en équivalents minéraux sur une dent d’un secteur incisivocanin", 0));
      builtEntries.put(new ActCode("HBLD012"), new ActContent("Pose d'une infrastructure coronaire sur 1 implant", 0));
      builtEntries.put(new ActCode("HBLD261"), new ActContent("Pose d'une infrastructure coronoradiculaire avec clavette sur une dent [Inlay core à clavette]", 144.05));
      builtEntries.put(new ActCode("HBLD007"), new ActContent("Pose d'une infrastructure coronoradiculaire sans clavette sur une dent [Inlay core]", 122.55));
      builtEntries.put(new ActCode("HBLD364"), new ActContent("Pose d'une prothèse amovible de transition à plaque base résine, comportant 1 à 3 dents", 64.5));
      builtEntries.put(new ActCode("HBLD231"), new ActContent("Pose d'une prothèse amovible de transition à plaque base résine, comportant 10 dents", 139.75));
      builtEntries.put(new ActCode("HBLD215"), new ActContent("Pose d'une prothèse amovible de transition à plaque base résine, comportant 11 dents", 150.5));
      builtEntries.put(new ActCode("HBLD262"), new ActContent("Pose d'une prothèse amovible de transition à plaque base résine, comportant 12 dents", 161.25));
      builtEntries.put(new ActCode("HBLD232"), new ActContent("Pose d'une prothèse amovible de transition à plaque base résine, comportant 13 dents", 172));
      builtEntries.put(new ActCode("HBLD476"), new ActContent("Pose d'une prothèse amovible de transition à plaque base résine, comportant 4 dents", 75.25));
      builtEntries.put(new ActCode("HBLD224"), new ActContent("Pose d'une prothèse amovible de transition à plaque base résine, comportant 5 dents", 86));
      builtEntries.put(new ActCode("HBLD371"), new ActContent("Pose d'une prothèse amovible de transition à plaque base résine, comportant 6 dents", 96.75));
      builtEntries.put(new ActCode("HBLD123"), new ActContent("Pose d'une prothèse amovible de transition à plaque base résine, comportant 7 dents", 107.5));
      builtEntries.put(new ActCode("HBLD270"), new ActContent("Pose d'une prothèse amovible de transition à plaque base résine, comportant 8 dents", 118.25));
      builtEntries.put(new ActCode("HBLD148"), new ActContent("Pose d'une prothèse amovible de transition à plaque base résine, comportant 9 dents", 129));
      builtEntries.put(new ActCode("HBLD032"), new ActContent("Pose d'une prothèse amovible de transition complète unimaxillaire à plaque base résine", 182.75));
      builtEntries.put(new ActCode("HBLD131"), new ActContent("Pose d'une prothèse amovible définitive à châssis métallique, comportant 1 à 3 dents", 193.5));
      builtEntries.put(new ActCode("HBLD079"), new ActContent("Pose d'une prothèse amovible définitive à châssis métallique, comportant 10 dents", 268.75));
      builtEntries.put(new ActCode("HBLD203"), new ActContent("Pose d'une prothèse amovible définitive à châssis métallique, comportant 11 dents", 279.5));
      builtEntries.put(new ActCode("HBLD112"), new ActContent("Pose d'une prothèse amovible définitive à châssis métallique, comportant 12 dents", 290.25));
      builtEntries.put(new ActCode("HBLD308"), new ActContent("Pose d'une prothèse amovible définitive à châssis métallique, comportant 13 dents", 301));
      builtEntries.put(new ActCode("HBLD332"), new ActContent("Pose d'une prothèse amovible définitive à châssis métallique, comportant 4 dents", 204.25));
      builtEntries.put(new ActCode("HBLD452"), new ActContent("Pose d'une prothèse amovible définitive à châssis métallique, comportant 5 dents", 215));
      builtEntries.put(new ActCode("HBLD474"), new ActContent("Pose d'une prothèse amovible définitive à châssis métallique, comportant 6 dents", 225.75));
      builtEntries.put(new ActCode("HBLD075"), new ActContent("Pose d'une prothèse amovible définitive à châssis métallique, comportant 7 dents", 236.5));
      builtEntries.put(new ActCode("HBLD470"), new ActContent("Pose d'une prothèse amovible définitive à châssis métallique, comportant 8 dents", 247.25));
      builtEntries.put(new ActCode("HBLD435"), new ActContent("Pose d'une prothèse amovible définitive à châssis métallique, comportant 9 dents", 258));
      builtEntries.put(new ActCode("HBLD138"), new ActContent("Pose d'une prothèse amovible définitive à plaque base résine, comportant 10 dents", 139.75));
      builtEntries.put(new ActCode("HBLD083"), new ActContent("Pose d'une prothèse amovible définitive à plaque base résine, comportant 11 dents", 150.5));
      builtEntries.put(new ActCode("HBLD370"), new ActContent("Pose d'une prothèse amovible définitive à plaque base résine, comportant 12 dents", 161.25));
      builtEntries.put(new ActCode("HBLD349"), new ActContent("Pose d'une prothèse amovible définitive à plaque base résine, comportant 13 dents", 172));
      builtEntries.put(new ActCode("HBLD101"), new ActContent("Pose d'une prothèse amovible définitive à plaque base résine, comportant 9 dents", 129));
      builtEntries.put(new ActCode("HBLD046"), new ActContent("Pose d'une prothèse amovible définitive complète bimaxillaire à châssis métallique", 623.5));
      builtEntries.put(new ActCode("HBLD035"), new ActContent("Pose d'une prothèse amovible définitive complète bimaxillaire à plaque base résine", 365.5));
      builtEntries.put(new ActCode("HBLD047"), new ActContent("Pose d'une prothèse amovible définitive complète unimaxillaire à châssis métallique", 311.75));
      builtEntries.put(new ActCode("HBLD031"), new ActContent("Pose d'une prothèse amovible définitive complète unimaxillaire à plaque base résine", 182.75));
      builtEntries.put(new ActCode("HBLD048"), new ActContent("Pose d'une prothèse amovible définitive complète unimaxillaire à plaque base résine et d'une prothèse amovible définitive complète unimaxillaire à châssis métallique", 494.5));
      builtEntries.put(new ActCode("HBLD492"), new ActContent("Pose d'une prothèse amovible supra-implantaire à plaque base résine, comportant de 9 à 13 dents", 150.5));
      builtEntries.put(new ActCode("HBLD199"), new ActContent("Pose d'une prothèse amovible supra-implantaire complète bimaxillaire à plaque base résine", 365.5));
      builtEntries.put(new ActCode("HBLD118"), new ActContent("Pose d'une prothèse amovible supra-implantaire complète unimaxillaire à plaque base résine", 182.75));
      builtEntries.put(new ActCode("HBLD030"), new ActContent("Pose d'une prothèse dentaire complète transvissée implantoportée", 182.75));
      builtEntries.put(new ActCode("HBLD043"), new ActContent("Pose d'une prothèse plurale [bridge] comportant 1 pilier d'ancrage métallique, 1 pilier d'ancrage céramométallique ou en équivalents minéraux, et 1 élément intermédiaire céramométallique ou en équivalents minéraux", 279.5));
      builtEntries.put(new ActCode("HBLD040"), new ActContent("Pose d'une prothèse plurale [bridge] comportant 1 pilier d'ancrage métallique, 1 pilier d'ancrage céramométallique ou en équivalents minéraux, et 1 élément intermédiaire métallique", 279.5));
      builtEntries.put(new ActCode("HBLD023"), new ActContent("Pose d'une prothèse plurale [bridge] comportant 2 piliers d'ancrage céramométalliques ou en équivalents minéraux et 1 élément intermédiaire céramométallique ou en équivalents minéraux", 279.5));
      builtEntries.put(new ActCode("HBLD033"), new ActContent("Pose d'une prothèse plurale [bridge] comportant 2 piliers d'ancrage métalliques et 1 élément intermédiaire métallique", 279.5));
      builtEntries.put(new ActCode("HBED015"), new ActContent("Réduction de fracture alvéolaire en denture mixte ou incomplète", 104.5));
      builtEntries.put(new ActCode("HBED009"), new ActContent("Réduction de fracture alvéolaire en denture permanente", 104.5));
      builtEntries.put(new ActCode("HBED016"), new ActContent("Réduction de luxation de plusieurs dents", 0));
      builtEntries.put(new ActCode("HBED011"), new ActContent("Réduction de luxation d'une dent", 0));
      builtEntries.put(new ActCode("HBMD004"), new ActContent("Réfection de la base d'une prothèse dentaire amovible complète", 0));
      builtEntries.put(new ActCode("HBMD007"), new ActContent("Réfection des bords et/ou de l'intrados d'une prothèse dentaire amovible partielle", 0));
      builtEntries.put(new ActCode("HBED001"), new ActContent("Réimplantation d'1 dent permanente expulsée", 96.4));
      builtEntries.put(new ActCode("HBED003"), new ActContent("Réimplantation de 2 dents permanentes expulsées", 192.8));
      builtEntries.put(new ActCode("HBED021"), new ActContent("Réimplantation de 3 dents permanentes expulsées, ou plus", 289.2));
      builtEntries.put(new ActCode("HBMD076"), new ActContent("Réparation de l'artifice cosmétique d'une dent prothétique par technique directe", 0));
      builtEntries.put(new ActCode("HBMD079"), new ActContent("Réparation de l'artifice cosmétique d'une dent prothétique par technique indirecte", 0));
      builtEntries.put(new ActCode("HBMD002"), new ActContent("Réparation d'une fracture de châssis métallique de prothèse dentaire amovible, avec remontage d'1 élément", 38.7));
      builtEntries.put(new ActCode("HBMD481"), new ActContent("Réparation d'une fracture de châssis métallique de prothèse dentaire amovible, avec remontage de 10 éléments", 96.75));
      builtEntries.put(new ActCode("HBMD449"), new ActContent("Réparation d'une fracture de châssis métallique de prothèse dentaire amovible, avec remontage de 11 éléments", 103.2));
      builtEntries.put(new ActCode("HBMD312"), new ActContent("Réparation d'une fracture de châssis métallique de prothèse dentaire amovible, avec remontage de 12 éléments", 109.65));
      builtEntries.put(new ActCode("HBMD289"), new ActContent("Réparation d'une fracture de châssis métallique de prothèse dentaire amovible, avec remontage de 13 éléments", 116.1));
      builtEntries.put(new ActCode("HBMD400"), new ActContent("Réparation d'une fracture de châssis métallique de prothèse dentaire amovible, avec remontage de 14 éléments", 122.55));
      builtEntries.put(new ActCode("HBMD488"), new ActContent("Réparation d'une fracture de châssis métallique de prothèse dentaire amovible, avec remontage de 2 éléments", 45.15));
      builtEntries.put(new ActCode("HBMD469"), new ActContent("Réparation d'une fracture de châssis métallique de prothèse dentaire amovible, avec remontage de 3 éléments", 51.6));
      builtEntries.put(new ActCode("HBMD110"), new ActContent("Réparation d'une fracture de châssis métallique de prothèse dentaire amovible, avec remontage de 4 éléments", 58.05));
      builtEntries.put(new ActCode("HBMD349"), new ActContent("Réparation d'une fracture de châssis métallique de prothèse dentaire amovible, avec remontage de 5 éléments", 64.5));
      builtEntries.put(new ActCode("HBMD386"), new ActContent("Réparation d'une fracture de châssis métallique de prothèse dentaire amovible, avec remontage de 6 éléments", 70.95));
      builtEntries.put(new ActCode("HBMD339"), new ActContent("Réparation d'une fracture de châssis métallique de prothèse dentaire amovible, avec remontage de 7 éléments", 77.4));
      builtEntries.put(new ActCode("HBMD459"), new ActContent("Réparation d'une fracture de châssis métallique de prothèse dentaire amovible, avec remontage de 8 éléments", 83.85));
      builtEntries.put(new ActCode("HBMD438"), new ActContent("Réparation d'une fracture de châssis métallique de prothèse dentaire amovible, avec remontage de 9 éléments", 90.3));
      builtEntries.put(new ActCode("HBMD008"), new ActContent("Réparation d'une fracture de châssis métallique de prothèse dentaire amovible, sans démontage d'éléments", 32.25));
      builtEntries.put(new ActCode("HBMD020"), new ActContent("Réparation d'une prothèse dentaire amovible en résine, fêlée ou fracturée", 21.5));
      builtEntries.put(new ActCode("HBMD016"), new ActContent("Rescellement et/ou recollage d’une ou deux couronnes ou d'un ou deux ancrages d'une prothèse dentaire fixée", 0));
      builtEntries.put(new ActCode("HBMD009"), new ActContent("Rescellement et/ou recollage de 3 couronnes ou plus ou de 3 ancrages ou plus d'une prothèse dentaire fixée", 0));
      builtEntries.put(new ActCode("HBMD058"), new ActContent("Restauration d’une dent d’un secteur incisivocanin sur 1 face par matériau inséré en phase plastique, sans ancrage radiculaire", 19.28));
      builtEntries.put(new ActCode("HBMD050"), new ActContent("Restauration d’une dent d’un secteur incisivocanin sur 2 faces par matériau inséré en phase plastique sans ancrage radiculaire", 33.74));
      builtEntries.put(new ActCode("HBMD054"), new ActContent("Restauration d’une dent d’un secteur incisivocanin sur 3 faces ou plus par matériau inséré en phase plastique sans ancrage radiculaire", 40.97));
      builtEntries.put(new ActCode("HBMD053"), new ActContent("Restauration d’une dent d’un secteur prémolomolaire sur 1 face par matériau inséré en phase plastique, sans ancrage radiculaire", 19.28));
      builtEntries.put(new ActCode("HBMD049"), new ActContent("Restauration d’une dent d’un secteur prémolomolaire sur 2 faces par matériau inséré en phase plastique sans ancrage radiculaire", 33.74));
      builtEntries.put(new ActCode("HBMD038"), new ActContent("Restauration d’une dent d’un secteur prémolomolaire sur 3 faces ou plus par matériau inséré en phase plastique sans ancrage radiculaire", 40.97));
      builtEntries.put(new ActCode("HBMD043"), new ActContent("Restauration d’une dent sur 1 face par matériau incrusté [inlay-onlay]", 19.28));
      builtEntries.put(new ActCode("HBMD046"), new ActContent("Restauration d’une dent sur 2 faces par matériau incrusté [inlay-onlay]", 33.74));
      builtEntries.put(new ActCode("HBMD055"), new ActContent("Restauration d’une dent sur 3 faces ou plus par matériau incrusté [inlay-onlay]", 40.97));
      builtEntries.put(new ActCode("HBMD044"), new ActContent("Restauration d'une dent d’un secteur incisivocanin sur 1 angle par matériau inséré en phase plastique, sans ancrage radiculaire", 43));
      builtEntries.put(new ActCode("HBMD047"), new ActContent("Restauration d'une dent d’un secteur incisivocanin sur 2 angles par matériau inséré en phase plastique, sans ancrage radiculaire", 86));
      builtEntries.put(new ActCode("HBMD042"), new ActContent("Restauration d'une dent par matériau inséré en phase plastique avec ancrage radiculaire", 79.53));
      builtEntries.put(new ActCode("HBMD019"), new ActContent("Révision des piliers implantoportés d'une prothèse dentaire", 18.81));
      builtEntries.put(new ActCode("HBMD061"), new ActContent("Séance d'ajustement occlusal par coronoplastie", 0));
      builtEntries.put(new ActCode("HBLD004"), new ActContent("Séance d'application topique intrabuccale de fluorures", 0));
      builtEntries.put(new ActCode("HBMD003"), new ActContent("Séance de renouvellement de l'obturation radiculaire d'une dent permanente immature à l'hydroxyde de calcium", 0));
      builtEntries.put(new ActCode("YYYY079"), new ActContent("Supplément pour pose de 10 dents contreplaquées ou massives à une prothèse amovible sur châssis métallique", 322.5));
      builtEntries.put(new ActCode("YYYY184"), new ActContent("Supplément pour pose de 11 dents contreplaquées ou massives à une prothèse amovible sur châssis métallique", 354.75));
      builtEntries.put(new ActCode("YYYY284"), new ActContent("Supplément pour pose de 12 dents contreplaquées ou massives à une prothèse amovible sur châssis métallique", 387));
      builtEntries.put(new ActCode("YYYY236"), new ActContent("Supplément pour pose de 13 dents contreplaquées ou massives à une prothèse amovible sur châssis métallique", 419.25));
      builtEntries.put(new ActCode("YYYY353"), new ActContent("Supplément pour pose de 14 dents contreplaquées ou massives à une prothèse amovible sur châssis métallique", 451.5));
      builtEntries.put(new ActCode("YYYY329"), new ActContent("Supplément pour pose de 2 dents contreplaquées ou massives à une prothèse amovible sur châssis métallique", 64.5));
      builtEntries.put(new ActCode("YYYY275"), new ActContent("Supplément pour pose de 2 dents contreplaquées sur une prothèse amovible à plaque base résine", 43));
      builtEntries.put(new ActCode("YYYY258"), new ActContent("Supplément pour pose de 3 dents contreplaquées ou massives à une prothèse amovible sur châssis métallique", 96.75));
      builtEntries.put(new ActCode("YYYY246"), new ActContent("Supplément pour pose de 3 dents contreplaquées sur une prothèse amovible à plaque base résine", 64.5));
      builtEntries.put(new ActCode("YYYY259"), new ActContent("Supplément pour pose de 4 dents contreplaquées ou massives à une prothèse amovible sur châssis métallique", 129));
      builtEntries.put(new ActCode("YYYY478"), new ActContent("Supplément pour pose de 4 dents contreplaquées sur une prothèse amovible à plaque base résine", 86));
      builtEntries.put(new ActCode("YYYY440"), new ActContent("Supplément pour pose de 5 dents contreplaquées ou massives à une prothèse amovible sur châssis métallique", 161.25));
      builtEntries.put(new ActCode("YYYY426"), new ActContent("Supplément pour pose de 5 dents contreplaquées sur une prothèse amovible à plaque base résine", 107.5));
      builtEntries.put(new ActCode("YYYY447"), new ActContent("Supplément pour pose de 6 dents contreplaquées ou massives à une prothèse amovible sur châssis métallique", 193.5));
      builtEntries.put(new ActCode("YYYY389"), new ActContent("Supplément pour pose de 6 dents contreplaquées sur une prothèse amovible à plaque base résine", 129));
      builtEntries.put(new ActCode("YYYY142"), new ActContent("Supplément pour pose de 7 dents contreplaquées ou massives à une prothèse amovible sur châssis métallique", 225.75));
      builtEntries.put(new ActCode("YYYY158"), new ActContent("Supplément pour pose de 8 dents contreplaquées ou massives à une prothèse amovible sur châssis métallique", 258));
      builtEntries.put(new ActCode("YYYY476"), new ActContent("Supplément pour pose de 9 dents contreplaquées ou massives à une prothèse amovible sur châssis métallique", 290.25));
      builtEntries.put(new ActCode("YYYY159"), new ActContent("Supplément pour pose d'une dent contreplaquée ou massive à une prothèse amovible sur châssis métallique", 32.25));
      builtEntries.put(new ActCode("YYYY176"), new ActContent("Supplément pour pose d'une dent contreplaquée sur une prothèse amovible à plaque base résine", 21.5));
      builtEntries.put(new ActCode("LBGA004"), new ActContent("Ablation d'1 implant intraosseux intrabuccal avec résection osseuse, chez l'adulte", 71.06));
      builtEntries.put(new ActCode("LBGA280"), new ActContent("Ablation d'1 implant intraosseux intrabuccal avec résection osseuse, chez l'enfant", 87.78));
      builtEntries.put(new ActCode("LBGA168"), new ActContent("Ablation de 10 implants intraosseux intrabuccaux avec résection osseuse, chez l'adulte", 202.73));
      builtEntries.put(new ActCode("LBGA113"), new ActContent("Ablation de 11 implants intraosseux intrabuccaux ou plus, avec résection osseuse", 0));
      builtEntries.put(new ActCode("LBGA441"), new ActContent("Ablation de 2 implants intraosseux intrabuccaux  avec résection osseuse, chez l'enfant", 106.59));
      builtEntries.put(new ActCode("LBGA003"), new ActContent("Ablation de 2 implants intraosseux intrabuccaux avec résection osseuse, chez l'adulte", 85.69));
      builtEntries.put(new ActCode("LBGA002"), new ActContent("Ablation de 3 implants intraosseux intrabuccaux avec résection osseuse, chez l'adulte", 100.32));
      builtEntries.put(new ActCode("LBGA354"), new ActContent("Ablation de 3 implants intraosseux intrabuccaux avec résection osseuse, chez l'enfant", 125.4));
      builtEntries.put(new ActCode("LBGA006"), new ActContent("Ablation de 4 implants intraosseux intrabuccaux avec résection osseuse, chez l'adulte", 114.95));
      builtEntries.put(new ActCode("LBGA049"), new ActContent("Ablation de 4 implants intraosseux intrabuccaux avec résection osseuse, chez l'enfant", 144.21));
      builtEntries.put(new ActCode("LBGA007"), new ActContent("Ablation de 5 implants intraosseux intrabuccaux avec résection osseuse, chez l'adulte", 129.58));
      builtEntries.put(new ActCode("LBGA008"), new ActContent("Ablation de 6 implants intraosseux intrabuccaux avec résection osseuse, chez l'adulte", 144.21));
      builtEntries.put(new ActCode("LBGA009"), new ActContent("Ablation de 7 implants intraosseux intrabuccaux avec résection osseuse, chez l'adulte", 158.84));
      builtEntries.put(new ActCode("LBGA139"), new ActContent("Ablation de 8 implants intraosseux intrabuccaux avec résection osseuse, chez l'adulte", 173.47));
      builtEntries.put(new ActCode("LBGA052"), new ActContent("Ablation de 9 implants intraosseux intrabuccaux avec résection osseuse, chez l'adulte", 188.1));
      builtEntries.put(new ActCode("LZGA001"), new ActContent("Ablation de biomatériau de la face et/ou du cou, par abord direct", 64.84));
      builtEntries.put(new ActCode("LAGA004"), new ActContent("Ablation de matériel externe d'ostéosynthèse ou de distraction du crâne et/ou du massif facial", 68.96));
      builtEntries.put(new ActCode("LAGA002"), new ActContent("Ablation de matériel interne d'ostéosynthèse du massif facial sur 3 sites ou plus, par abord direct", 97.06));
      builtEntries.put(new ActCode("LAGA005"), new ActContent("Ablation de matériel interne d'ostéosynthèse ou de distraction du massif facial sur 2 sites, par abord direct", 90.49));
      builtEntries.put(new ActCode("LAGA003"), new ActContent("Ablation de matériel interne d'ostéosynthèse ou de distraction du massif facial sur un site, par abord direct", 64.84));
      builtEntries.put(new ActCode("LAGA001"), new ActContent("Ablation de plusieurs implants intraosseux crâniens et/ou faciaux sans résection osseuse, par abord facial", 51.69));
      builtEntries.put(new ActCode("LAGA006"), new ActContent("Ablation d'un implant intraosseux crânien ou facial sans résection osseuse, par abord direct", 43.47));
      builtEntries.put(new ActCode("LAPB451"), new ActContent("Dégagement et activation d'1 implant intraosseux intrabuccal, chez l'enfant", 94.05));
      builtEntries.put(new ActCode("LAPB002"), new ActContent("Dégagement et activation d'1 implant intraosseux intrabuccaux, chez l'adulte", 87.78));
      builtEntries.put(new ActCode("LAPB122"), new ActContent("Dégagement et activation de 10 implants intraosseux intrabuccaux, chez l'adulte", 689.7));
      builtEntries.put(new ActCode("LAPB288"), new ActContent("Dégagement et activation de 11 implants intraosseux intrabuccaux ou plus", 0));
      builtEntries.put(new ActCode("LAPB004"), new ActContent("Dégagement et activation de 2 implants intraosseux intrabuccaux, chez l'adulte", 154.66));
      builtEntries.put(new ActCode("LAPB311"), new ActContent("Dégagement et activation de 2 implants intraosseux intrabuccaux, chez l'enfant", 163.02));
      builtEntries.put(new ActCode("LAPB003"), new ActContent("Dégagement et activation de 3 implants intraosseux intrabuccaux, chez l'adulte", 221.54));
      builtEntries.put(new ActCode("LAPB459"), new ActContent("Dégagement et activation de 3 implants intraosseux intrabuccaux, chez l'enfant", 231.99));
      builtEntries.put(new ActCode("LAPB001"), new ActContent("Dégagement et activation de 4 implants intraosseux intrabuccaux, chez l'adulte", 288.42));
      builtEntries.put(new ActCode("LAPB408"), new ActContent("Dégagement et activation de 4 implants intraosseux intrabuccaux, chez l'enfant", 300.96));
      builtEntries.put(new ActCode("LAPB005"), new ActContent("Dégagement et activation de 5 implants intraosseux intrabuccaux, chez l'adulte", 355.3));
      builtEntries.put(new ActCode("LAPB006"), new ActContent("Dégagement et activation de 6 implants intraosseux intrabuccaux, chez l'adulte", 422.18));
      builtEntries.put(new ActCode("LAPB007"), new ActContent("Dégagement et activation de 7 implants intraosseux intra buccaux, chez l'adulte", 489.06));
      builtEntries.put(new ActCode("LAPB047"), new ActContent("Dégagement et activation de 8 implants intraosseux intrabuccaux, chez l'adulte", 555.94));
      builtEntries.put(new ActCode("LAPB030"), new ActContent("Dégagement et activation de 9 implants intraosseux intrabuccaux, chez l'adulte", 622.82));
      builtEntries.put(new ActCode("LABA002"), new ActContent("Désépaississement des tissus de recouvrement d'un site implantaire", 41.8));
      builtEntries.put(new ActCode("QAJH002"), new ActContent("Drainage de collection de la face, par voie transcutanée avec guidage radiologique", 38.4));
      builtEntries.put(new ActCode("QAJH003"), new ActContent("Drainage de collection de la face, par voie transcutanée avec guidage scanographique", 38.4));
      builtEntries.put(new ActCode("QAJH004"), new ActContent("Évacuation de collection de la face, par voie transcutanée avec guidage radiologique", 83.6));
      builtEntries.put(new ActCode("QAJH001"), new ActContent("Évacuation de collection de la face, par voie transcutanée avec guidage scanographique", 83.6));
      builtEntries.put(new ActCode("LAFA013"), new ActContent("Exérèse partielle d'un os de la face sans interruption de la continuité, par abord direct", 167.2));
      builtEntries.put(new ActCode("LBLD015"), new ActContent("Pose d'1 implant intraosseux intrabuccal, chez l'adulte", 422.18));
      builtEntries.put(new ActCode("LBLD075"), new ActContent("Pose d'1 implant intraosseux intrabuccal, chez l'enfant", 438.9));
      builtEntries.put(new ActCode("LBLD294"), new ActContent("Pose de 10 implants intraosseux intrabuccaux, chez l'adulte", 3695.12));
      builtEntries.put(new ActCode("LBLD261"), new ActContent("Pose de 11 implants intraosseux intrabuccaux ou plus", 0));
      builtEntries.put(new ActCode("LBLD066"), new ActContent("Pose de 2 implants intraosseux intrabuccaux chez l'enfant", 806.74));
      builtEntries.put(new ActCode("LBLD010"), new ActContent("Pose de 2 implants intraosseux intrabuccaux, chez l'adulte", 785.84));
      builtEntries.put(new ActCode("LBLD281"), new ActContent("Pose de 3 implants intraosseux intrabuccaux chez l'enfant", 1174.58));
      builtEntries.put(new ActCode("LBLD013"), new ActContent("Pose de 3 implants intraosseux intrabuccaux, chez l'adulte", 1149.5));
      builtEntries.put(new ActCode("LBLD117"), new ActContent("Pose de 4 implants intraosseux intrabuccaux chez l'enfant", 1542.42));
      builtEntries.put(new ActCode("LBLD004"), new ActContent("Pose de 4 implants intraosseux intrabuccaux, chez l'adulte", 1513.16));
      builtEntries.put(new ActCode("LBLD020"), new ActContent("Pose de 5 implants intraosseux intrabuccaux, chez l'adulte", 1876.82));
      builtEntries.put(new ActCode("LBLD025"), new ActContent("Pose de 6 implants intraosseux intrabuccaux, chez l'adulte", 2240.48));
      builtEntries.put(new ActCode("LBLD026"), new ActContent("Pose de 7 implants intraosseux intrabuccaux, chez l'adulte", 2604.14));
      builtEntries.put(new ActCode("LBLD038"), new ActContent("Pose de 8 implants intraosseux intrabuccaux, chez l'adulte", 2967.8));
      builtEntries.put(new ActCode("LBLD200"), new ActContent("Pose de 9 implants intraosseux intrabuccaux, chez l'adulte", 3331.46));
      builtEntries.put(new ActCode("LBLD034"), new ActContent("Pose de barre de conjonction entre 2 implants intrabuccaux", 96.14));
      builtEntries.put(new ActCode("LBLD057"), new ActContent("Pose de barre de conjonction entre 3 implants intrabuccaux ou plus", 144.21));
      builtEntries.put(new ActCode("LBLD019"), new ActContent("Pose de moyen de liaison sur 1 implant préprothétique intraosseux intrabuccal", 160.93));
      builtEntries.put(new ActCode("LBLD214"), new ActContent("Pose de moyen de liaison sur 10 implants préprothétiques intraosseux intrabuccaux", 1496.44));
      builtEntries.put(new ActCode("LBLD420"), new ActContent("Pose de moyen de liaison sur 11 implants préprothétiques intraosseux intrabuccaux ou plus", 0));
      builtEntries.put(new ActCode("LBLD073"), new ActContent("Pose de moyen de liaison sur 2 implants préprothétiques intraosseux intrabuccaux", 309.32));
      builtEntries.put(new ActCode("LBLD086"), new ActContent("Pose de moyen de liaison sur 3 implants préprothétiques intraosseux intrabuccaux", 457.71));
      builtEntries.put(new ActCode("LBLD193"), new ActContent("Pose de moyen de liaison sur 4 implants préprothétiques intraosseux intrabuccaux", 606.1));
      builtEntries.put(new ActCode("LBLD447"), new ActContent("Pose de moyen de liaison sur 5 implants préprothétiques intraosseux intrabuccaux", 754.49));
      builtEntries.put(new ActCode("LBLD270"), new ActContent("Pose de moyen de liaison sur 6 implants préprothétiques intraosseux intrabuccaux", 902.88));
      builtEntries.put(new ActCode("LBLD143"), new ActContent("Pose de moyen de liaison sur 7 implants préprothétiques intraosseux intrabuccaux", 1051.27));
      builtEntries.put(new ActCode("LBLD235"), new ActContent("Pose de moyen de liaison sur 8 implants préprothétiques intraosseux intrabuccaux", 1199.66));
      builtEntries.put(new ActCode("LBLD311"), new ActContent("Pose de moyen de liaison sur 9 implants préprothétiques intraosseux intrabuccaux", 1348.05));
      builtEntries.put(new ActCode("LALB001"), new ActContent("Pose de moyen de liaison sur implants crâniens et/ou faciaux", 115.2));
      builtEntries.put(new ActCode("LALA001"), new ActContent("Pose de plusieurs implants intraosseux crâniens et/ou faciaux pour fixation d'épithèse", 250.8));
      builtEntries.put(new ActCode("LALA002"), new ActContent("Pose d'un implant intraosseux crânien ou facial pour fixation d'épithèse ou d'appareillage auditif ostéo-intégré", 167.2));
      builtEntries.put(new ActCode("LBFA031"), new ActContent("Résection d'hypertrophie osseuse intrabuccale", 34.55));
      builtEntries.put(new ActCode("HAHA002"), new ActContent("Biopsie de lèvre", 20.97));
      builtEntries.put(new ActCode("HAHD001"), new ActContent("Frottis et/ou prélèvement intrabuccal", 10.2));
      builtEntries.put(new ActCode("HAHD002"), new ActContent("Biopsie de la cavité orale et/ou de l'oropharynx, avec guidage par des colorations vitales", 23.24));
      builtEntries.put(new ActCode("HAHD003"), new ActContent("Biopsie de la cavité orale et/ou de l'oropharynx, sans coloration vitale", 19.67));
      builtEntries.put(new ActCode("HCHA001"), new ActContent("Biopsie de glande salivaire majeure [principale]", 29.49));
      builtEntries.put(new ActCode("HCHA002"), new ActContent("Biopsie des petites glandes salivaires [glandes salivaires mineures] [glandes salivaires accessoires]", 23.68));
      builtEntries.put(new ActCode("HCHB001"), new ActContent("Ponction ou cytoponction de glande salivaire, par voie transcutanée", 28.15));
      builtEntries.put(new ActCode("HGHD002"), new ActContent("Biopsie entérale à l'aveugle à la sonde, par voie nasale", 57.6));
      builtEntries.put(new ActCode("HJHD001"), new ActContent("Biopsie rectale par aspiration de la muqueuse par sonde", 22.24));
      builtEntries.put(new ActCode("HJHD002"), new ActContent("Biopsie de la musculeuse du rectum, par voie anale", 60.94));
      builtEntries.put(new ActCode("HKHA001"), new ActContent("Biopsie de lésion de la région périanale et/ou du canal anal", 26.72));
      builtEntries.put(new ActCode("HPHB001"), new ActContent("Ponction-lavage du péritoine, avec pose de cathéter intrapéritonéal par voie transcutanée", 96.25));
      builtEntries.put(new ActCode("HPHB002"), new ActContent("Ponction du cul-de-sac recto-utérin [de Douglas] [Culdocentèse], par voie transvaginale sans guidage", 24.93));
      builtEntries.put(new ActCode("HPHB003"), new ActContent("Ponction d'un épanchement péritonéal, par voie transcutanée", 24.51));
      builtEntries.put(new ActCode("HPHJ001"), new ActContent("Ponction du cul-de-sac recto-utérin [de Douglas] [Culdocentèse], par voie transvaginale avec guidage échographique", 19.2));
      builtEntries.put(new ActCode("HBAA338"), new ActContent("Allongement coronaire par gingivectomie sur une dent", 0));
      builtEntries.put(new ActCode("HBBA002"), new ActContent("Ostéoplastie additive de l'arcade alvéolaire sur un secteur de 4 à 6 dents", 269.61));
      builtEntries.put(new ActCode("HBBA003"), new ActContent("Ostéoplastie additive de l'arcade alvéolaire sur un secteur de 1 à 3 dents", 85.69));
      builtEntries.put(new ActCode("HBBA004"), new ActContent("Ostéoplastie additive de l'arcade alvéolaire sur un secteur de 7 dents ou plus", 298.87));
      builtEntries.put(new ActCode("HBED023"), new ActContent("Greffe épithélioconjonctive ou conjonctive sur la gencive, sur un secteur de 1 à 3 dents", 79.42));
      builtEntries.put(new ActCode("HBED024"), new ActContent("Greffe épithélioconjonctive ou conjonctive sur la gencive, sur un sextant", 94.05));
      builtEntries.put(new ActCode("HBFA003"), new ActContent("Ostéoplastie soustractive de l'arcade alvéolaire sur un secteur de 7 dents ou plus", 0));
      builtEntries.put(new ActCode("HBFA004"), new ActContent("Ostéoplastie soustractive de l'arcade alvéolaire sur un secteur de 4 à 6 dents", 0));
      builtEntries.put(new ActCode("HBFA005"), new ActContent("Ostéoplastie soustractive de l'arcade alvéolaire sur un secteur de 1 à 3 dents", 0));
      builtEntries.put(new ActCode("HBFA006"), new ActContent("Gingivectomie sur un secteur de 1 à 3 dents", 0));
      builtEntries.put(new ActCode("HBFA007"), new ActContent("Gingivectomie sur un secteur de 4 à 6 dents", 41.8));
      builtEntries.put(new ActCode("HBFA008"), new ActContent("Gingivectomie  sur un secteur de 7 dents ou plus", 0));
      builtEntries.put(new ActCode("HBFA012"), new ActContent("Exérèse d'hypertrophie gingivale ou de crête flottante sur une arcade maxillaire ou mandibulaire complète", 0));
      builtEntries.put(new ActCode("HBFA013"), new ActContent("Exérèse d'hypertrophie gingivale ou de crête flottante localisée", 0));
      builtEntries.put(new ActCode("HBGB001"), new ActContent("Curetage d'alvéole dentaire", 0));
      builtEntries.put(new ActCode("HBGB002"), new ActContent("Curetage périapical avec résection de l'apex et obturation radiculaire d'une prémolaire", 98.36));
      builtEntries.put(new ActCode("HBGB003"), new ActContent("Curetage périapical avec résection de l'apex et obturation radiculaire d'une incisive ou d'une canine", 83.9));
      builtEntries.put(new ActCode("HBGB004"), new ActContent("Curetage périapical avec résection de l'apex et obturation radiculaire d'une molaire", 132.1));
      builtEntries.put(new ActCode("HBGB005"), new ActContent("Curetage périapical avec résection de l'apex d'une racine dentaire endodontiquement traitée", 50.16));
      builtEntries.put(new ActCode("HBGB006"), new ActContent("Surfaçage radiculaire dentaire sur un sextant", 0));
      builtEntries.put(new ActCode("HBJA003"), new ActContent("Assainissement parodontal par lambeau sur un sextant", 0));
      builtEntries.put(new ActCode("HBJB001"), new ActContent("Évacuation d'abcès parodontal", 40));
      builtEntries.put(new ActCode("HBMA001"), new ActContent("Plastie mucogingivale par lambeau déplacé latéralement, coronairement ou apicalement", 75.24));
      builtEntries.put(new ActCode("HBMA003"), new ActContent("Ostéoplastie d'une alvéole dentaire avec comblement par autogreffe osseuse", 0));
      builtEntries.put(new ActCode("HBMA004"), new ActContent("Régénération parodontale ", 0));
      builtEntries.put(new ActCode("HBMA006"), new ActContent("Ostéoplastie d'une alvéole dentaire avec comblement par biomatériau", 0));
      builtEntries.put(new ActCode("HBMD018"), new ActContent("Séance de préparation [mise en condition] tissulaire des surfaces d'appui muqueux d'une prothèse dentaire, sur une arcade", 0));
      builtEntries.put(new ActCode("GALP002"), new ActContent("Pose préopératoire d'un appareillage orthopédique de correction d'une déformation nasale, pour fente orofaciale", 268.8));
      builtEntries.put(new ActCode("GAMA025"), new ActContent("Correction de séquelle narinaire d'une fente labio-maxillo-palatine unilatérale", 191.95));
      builtEntries.put(new ActCode("GAMA026"), new ActContent("Correction de séquelle narinaire d'une fente labio-maxillo-palatine bilatérale", 214.15));
      builtEntries.put(new ActCode("HAAA001"), new ActContent("Approfondissement du vestibule oral [sillon gingivojugal] par section mucopériostée avec greffe cutanée ou muqueuse", 104.61));
      builtEntries.put(new ActCode("HAAA002"), new ActContent("Approfondissement du vestibule oral [sillon gingivojugal] par section mucopériostée", 83.6));
      builtEntries.put(new ActCode("HAAA003"), new ActContent("Approfondissement du plancher de la bouche par section musculaire", 125.4));
      builtEntries.put(new ActCode("HACA001"), new ActContent("Adhésion labiale pour fente labio-maxillo-palatine unilatérale", 145.19));
      builtEntries.put(new ActCode("HACA002"), new ActContent("Adhésion labiale pour fente labio-maxillo-palatine bilatérale", 234.59));
      builtEntries.put(new ActCode("HADA001"), new ActContent("Labioglossopexie", 141.99));
      builtEntries.put(new ActCode("HADA002"), new ActContent("Hyomandibulopexie", 153.15));
      builtEntries.put(new ActCode("HAFA001"), new ActContent("Glossectomie partielle de base, par cervicotomie", 259.58));
      builtEntries.put(new ActCode("HAFA002"), new ActContent("Pelvi-glosso-mandibulectomie non interruptrice, par abord intrabuccal", 288.68));
      builtEntries.put(new ActCode("HAFA003"), new ActContent("Glossectomie totale de langue mobile, par abord cervicofacial", 268.07));
      builtEntries.put(new ActCode("HAFA004"), new ActContent("Pelvimandibulectomie interruptrice, par abord cervicofacial", 464.23));
      builtEntries.put(new ActCode("HAFA005"), new ActContent("Exérèse partielle de la base de la langue et/ou du sillon amygdaloglosse, par abord intrabuccal", 182.32));
      builtEntries.put(new ActCode("HAFA006"), new ActContent("Pelviglossectomie de langue mobile, par abord intrabuccal", 206.43));
      builtEntries.put(new ActCode("HAFA007"), new ActContent("Pelvectomie orale partielle, par abord intrabuccal", 182.32));
      builtEntries.put(new ActCode("HAFA009"), new ActContent("Exérèse de kyste du plancher de la bouche, par abord intrabuccal et par abord facial", 171.38));
      builtEntries.put(new ActCode("HAFA012"), new ActContent("Glossectomie totale de base", 344.44));
      builtEntries.put(new ActCode("HAFA013"), new ActContent("Glossectomie totale de langue mobile, par abord intrabuccal", 193.49));
      builtEntries.put(new ActCode("HAFA015"), new ActContent("Exérèse de lésion de la muqueuse de la bouche ou de l'oropharynx de moins de 2 cm de grand axe, par abord intrabuccal", 37.01));
      builtEntries.put(new ActCode("HAFA016"), new ActContent("Glossectomie totale avec pharyngolaryngectomie totale", 690.73));
      builtEntries.put(new ActCode("HAFA017"), new ActContent("Pelvi-glosso-mandibulectomie interruptrice, par abord cervicofacial", 480.76));
      builtEntries.put(new ActCode("HAFA019"), new ActContent("Exérèse de lésion de la muqueuse de la bouche ou de l'oropharynx de plus de 4 cm de grand axe, par abord intrabuccal", 167.2));
      builtEntries.put(new ActCode("HAFA021"), new ActContent("Exérèse non transfixiante de lésion infiltrante de la joue, par abord intrabuccal", 125.4));
      builtEntries.put(new ActCode("HAFA022"), new ActContent("Exérèse transfixiante de lésion de la joue, par abord facial", 125.4));
      builtEntries.put(new ActCode("HAFA023"), new ActContent("Glossectomie partielle de langue mobile, par abord intrabuccal", 111.32));
      builtEntries.put(new ActCode("HAFA024"), new ActContent("Pelvimandibulectomie non interruptrice, par abord cervicofacial", 367.72));
      builtEntries.put(new ActCode("HAFA026"), new ActContent("Pelvi-glosso-mandibulectomie non interruptrice, par abord cervicofacial", 367.72));
      builtEntries.put(new ActCode("HAFA027"), new ActContent("Pelviglossectomie de langue mobile, par abord cervicofacial", 297.1));
      builtEntries.put(new ActCode("HAFA029"), new ActContent("Glossectomie totale de base de langue et de langue mobile", 377.48));
      builtEntries.put(new ActCode("HAFA032"), new ActContent("Exérèse de lésion de la muqueuse de la bouche ou de l'oropharynx de 2 cm à 4 cm de grand axe, par abord intrabuccal", 104.5));
      builtEntries.put(new ActCode("HAFA033"), new ActContent("Pelvimandibulectomie non interruptrice, par abord intrabuccal", 272.15));
      builtEntries.put(new ActCode("HAFA034"), new ActContent("Exérèse de kyste du plancher de la bouche, par abord intrabuccal", 83.77));
      builtEntries.put(new ActCode("HAJA002"), new ActContent("Évacuation de collection pelvilinguale, par abord intrabuccal", 41.8));
      builtEntries.put(new ActCode("HAJA007"), new ActContent("Parage et/ou suture de plaies muqueuses intrabuccales multiples", 32.49));
      builtEntries.put(new ActCode("HAJA008"), new ActContent("Parage et/ou suture de plaie du voile du palais", 36.51));
      builtEntries.put(new ActCode("HAJA009"), new ActContent("Parage et/ou suture de plaie de la langue", 28.5));
      builtEntries.put(new ActCode("HAJA010"), new ActContent("Parage et/ou suture d'une plaie muqueuse intrabuccale", 23.3));
      builtEntries.put(new ActCode("HAJD003"), new ActContent("Pansement intrabuccal sous anesthésie générale, dans les suites d'un acte sur la cavité orale", 38.66));
      builtEntries.put(new ActCode("HAJD004"), new ActContent("Évacuation de collection de la base de la langue", 83.6));
      builtEntries.put(new ActCode("HALD001"), new ActContent("Pose de dispositif intrabuccal d'expansion labiojugale", 153.6));
      builtEntries.put(new ActCode("HALD002"), new ActContent("Pose d'un appareillage antiautomorsure", 0));
      builtEntries.put(new ActCode("HALD003"), new ActContent("Pose d'une plaque palatine active [orthopédique] pour fente orofaciale", 48));
      builtEntries.put(new ActCode("HALD004"), new ActContent("Pose d'une plaque palatine non active [passive] pour fente orofaciale ou division palatine", 48));
      builtEntries.put(new ActCode("HALD005"), new ActContent("Pose d'une prothèse intrabuccale pour perte de substance du palais dur et du palais mou", 192));
      builtEntries.put(new ActCode("HAMA001"), new ActContent("Glossoplastie de réduction", 125.4));
      builtEntries.put(new ActCode("HAMA006"), new ActContent("Correction primaire unilatérale complète d'une fente labioalvéolaire ou labiomaxillaire", 246.64));
      builtEntries.put(new ActCode("HAMA007"), new ActContent("Reconstruction du philtrum par lambeau hétérolabial, pour séquelle d'une fente orofaciale", 0));
      builtEntries.put(new ActCode("HAMA012"), new ActContent("Plastie cutanéomuqueuse de symétrisation labiale pour séquelle d'une fente labio-maxillo-palatine", 150.11));
      builtEntries.put(new ActCode("HAMA017"), new ActContent("Correction primaire bilatérale complète d'une fente labioalvéolaire ou labiomaxillaire", 309.71));
      builtEntries.put(new ActCode("HAMA024"), new ActContent("Correction de séquelle labionarinaire d'une fente labio-maxillo-palatine unilatérale", 299.43));
      builtEntries.put(new ActCode("HAMA025"), new ActContent("Correction de séquelle labionarinaire d'une fente labio-maxillo-palatine bilatérale", 378.55));
      builtEntries.put(new ActCode("HAMA026"), new ActContent("Pelviglossoplastie", 154.49));
      builtEntries.put(new ActCode("HAND001"), new ActContent("Destruction de lésion de la muqueuse de la bouche ou de l'oropharynx de 2 cm à 4 cm de grand axe, par voie buccale sans laser", 29.94));
      builtEntries.put(new ActCode("HAND002"), new ActContent("Destruction de lésion de la muqueuse de la bouche ou de l'oropharynx de moins de 2 cm de grand axe, par voie buccale sans laser", 22.13));
      builtEntries.put(new ActCode("HAND003"), new ActContent("Destruction de lésion de la muqueuse de la bouche ou de l'oropharynx de plus de 4 cm de grand axe, par voie buccale sans laser", 104.5));
      builtEntries.put(new ActCode("HAND004"), new ActContent("Destruction de lésion de la muqueuse de la bouche ou de l'oropharynx de moins de 2 cm de grand axe, par voie buccale avec laser", 22.2));
      builtEntries.put(new ActCode("HAND005"), new ActContent("Destruction de lésion de la muqueuse de la bouche ou de l'oropharynx de plus de 4 cm de grand axe, par voie buccale avec laser", 104.5));
      builtEntries.put(new ActCode("HAND006"), new ActContent("Destruction de lésion de la muqueuse de la bouche ou de l'oropharynx de 2 cm à 4 cm de grand axe, par voie buccale avec laser", 30.04));
      builtEntries.put(new ActCode("HAPA001"), new ActContent("Section de bride muqueuse ou de frein intrabuccal avec plastie par lambeau local", 29.34));
      builtEntries.put(new ActCode("HAPA003"), new ActContent("Libération musculaire et muqueuse d'une ankyloglossie", 62.7));
      builtEntries.put(new ActCode("HAPA004"), new ActContent("Marsupialisation d'un kyste du plancher de la bouche", 54.16));
      builtEntries.put(new ActCode("HAPD001"), new ActContent("Section de bride muqueuse ou de frein intrabuccal", 20.9));
      builtEntries.put(new ActCode("HASA001"), new ActContent("Fermeture labiale primaire unilatérale d'une fente labio-alvéolo-maxillaire, avec correction complète de la déformation nasale [Chéilorhinoplastie unilatérale pour fente labio-alvéolo-maxillaire]", 347.96));
      builtEntries.put(new ActCode("HASA002"), new ActContent("Fermeture d'une fistule bucconasale séquellaire d'une fente orofaciale par plastie locale", 199.89));
      builtEntries.put(new ActCode("HASA003"), new ActContent("Fermeture d'une fistule bucconasale séquellaire d'une fente orofaciale par plastie locorégionale ou lambeau de langue", 221.33));
      builtEntries.put(new ActCode("HASA004"), new ActContent("Fermeture bilatérale de la lèvre et du palais osseux d'une fente labio-maxillo-palatine, en un temps [Chéilo-rhino-uranoplastie bilatérale pour fente orofaciale]", 529.34));
      builtEntries.put(new ActCode("HASA005"), new ActContent("Fermeture d'une fente labiale inférieure médiane", 234.84));
      builtEntries.put(new ActCode("HASA006"), new ActContent("Fermeture labiale primaire bilatérale d'une fente labio-alvéolo-maxillaire, sans correction complète de la déformation nasale [Chéiloplastie bilatérale pour fente labio-alvéolo-maxillaire]", 375.1));
      builtEntries.put(new ActCode("HASA007"), new ActContent("Fermeture unilatérale complète d'une fente labio-maxillo-palatine, en un temps [Chéilo-rhino-urano-staphylorraphie unilatérale pour fente orofaciale]", 459.7));
      builtEntries.put(new ActCode("HASA008"), new ActContent("Fermeture primaire bilatérale d'une fente labiale sans fente osseuse alvéolomaxillaire, sans réparation complète de la déformation nasale [Chéiloplastie primaire bilatérale pour fente labiale]", 330.67));
      builtEntries.put(new ActCode("HASA009"), new ActContent("Fermeture d'une communication buccosinusienne et/ou bucconasale par lambeau de muscle temporal, par abord intrabuccal et par abord facial", 219.45));
      builtEntries.put(new ActCode("HASA010"), new ActContent("Fermeture bilatérale complète d'une fente labio-maxillo-palatine, en un temps [Chéilo-rhino-urano-staphylorraphie bilatérale pour fente orofaciale]", 546.61));
      builtEntries.put(new ActCode("HASA012"), new ActContent("Fermeture d'orostome ou de pharyngostome", 104.5));
      builtEntries.put(new ActCode("HASA013"), new ActContent("Fermeture d'une communication buccosinusienne et/ou bucconasale par lambeau palatin, par abord intrabuccal", 146.3));
      builtEntries.put(new ActCode("HASA014"), new ActContent("Fermeture primaire bilatérale d'une fente labiale sans fente osseuse alvéolomaxillaire, avec réparation complète de la déformation nasale [Chéilorhinoplastie primaire bilatérale pour fente labiale]", 384.41));
      builtEntries.put(new ActCode("HASA015"), new ActContent("Fermeture primaire unilatérale d'une fente labiale sans fente osseuse alvéolomaxillaire, sans réparation complète de la déformation nasale [Chéiloplastie primaire unilatérale pour fente labiale]", 212.22));
      builtEntries.put(new ActCode("HASA016"), new ActContent("Fermeture bilatérale de la lèvre et du voile du palais d'une fente labio-maxillo-palatine, en un temps [Chéilorhinoplastie bilatérale avec staphylorraphie pour fente orofaciale]", 530.98));
      builtEntries.put(new ActCode("HASA017"), new ActContent("Fermeture unilatérale de la lèvre et du palais osseux d'une fente labio-maxillo-palatine, en un temps [Chéilo-rhino-uranoplastie unilatérale pour fente orofaciale]", 442.42));
      builtEntries.put(new ActCode("HASA018"), new ActContent("Fermeture d'une communication buccosinusienne par lambeau de glissement vestibulojugal, par abord intrabuccal", 146.3));
      builtEntries.put(new ActCode("HASA019"), new ActContent("Fermeture labiale primaire unilatérale d'une fente labio-alvéolo-maxillaire, sans correction complète de la déformation nasale [Chéiloplastie unilatérale pour fente labio-alvéolo-maxillaire]", 281.59));
      builtEntries.put(new ActCode("HASA020"), new ActContent("Fermeture labiale primaire bilatérale d'une fente labio-alvéolo-maxillaire, avec correction complète de la déformation nasale [Chéilorhinoplastie bilatérale pour fente labio-alvéolo-maxillaire]", 426.09));
      builtEntries.put(new ActCode("HASA021"), new ActContent("Fermeture d'une fente labiale supérieure médiane", 261.16));
      builtEntries.put(new ActCode("HASA022"), new ActContent("Fermeture unilatérale de la lèvre et du voile du palais d'une fente labio-maxillo-palatine, en un temps [Chéilorhinoplastie unilatérale avec staphylorraphie pour fente orofaciale]", 444.07));
      builtEntries.put(new ActCode("HASA023"), new ActContent("Fermeture primaire unilatérale d'une fente labiale sans fente osseuse alvéolomaxillaire, avec réparation complète de la déformation nasale [Chéilorhinoplastie primaire unilatérale pour fente labiale]", 298.06));
      builtEntries.put(new ActCode("HASA025"), new ActContent("Fermeture d'une communication buccosinusienne par lambeau de transposition du corps adipeux de la joue, par abord intrabuccal", 146.3));
      builtEntries.put(new ActCode("HASD001"), new ActContent("Fermeture secondaire bilatérale d'une fente alvéolaire par gingivopériostoplastie ou lambeau muqueux, avec autogreffe osseuse", 361.96));
      builtEntries.put(new ActCode("HASD002"), new ActContent("Fermeture secondaire unilatérale d'une fente alvéolaire par gingivopériostoplastie ou lambeau muqueux", 224.31));
      builtEntries.put(new ActCode("HASD003"), new ActContent("Hémostase secondaire à une électrocoagulation intrabuccale", 36.44));
      builtEntries.put(new ActCode("HASD004"), new ActContent("Fermeture secondaire bilatérale d'une fente alvéolaire par gingivopériostoplastie ou lambeau muqueux", 315.89));
      builtEntries.put(new ActCode("HASD005"), new ActContent("Fermeture secondaire unilatérale d'une fente alvéolaire par gingivopériostoplastie ou lambeau muqueux, avec autogreffe osseuse", 293.96));
      builtEntries.put(new ActCode("HASD006"), new ActContent("Fermeture primaire d'une fente du palais osseux [Uranoplastie pour fente orofaciale]", 232.53));
      builtEntries.put(new ActCode("HASD007"), new ActContent("Fermeture primaire d'une fente palatovélaire [Uranostaphylorraphie pour fente orofaciale]", 281.87));
      builtEntries.put(new ActCode("HBSD001"), new ActContent("Hémostase gingivoalvéolaire secondaire à une avulsion dentaire", 22.05));
      builtEntries.put(new ActCode("HCCA001"), new ActContent("Dérivation du conduit parotidien [de Sténon] pour suppléance lacrymale", 215.94));
      builtEntries.put(new ActCode("HCCA002"), new ActContent("Suture de plaie de conduit salivaire", 103.15));
      builtEntries.put(new ActCode("HCCD001"), new ActContent("Dérivation oropharyngée bilatérale du conduit parotidien [de Sténon], par voie buccale", 303.6));
      builtEntries.put(new ActCode("HCEA001"), new ActContent("Transposition unilatérale ou bilatérale des conduits submandibulaires [de Wharton]", 149.13));
      builtEntries.put(new ActCode("HCFA001"), new ActContent("Exérèse de glande submandibulaire [Submandibulectomie] [Sousmaxillectomie] élargie à sa loge, par abord cervicofacial", 203.76));
      builtEntries.put(new ActCode("HCFA002"), new ActContent("Parotidectomie totale avec résection du nerf facial", 410.06));
      builtEntries.put(new ActCode("HCFA003"), new ActContent("Exérèse de glande sublinguale, par abord direct", 104.5));
      builtEntries.put(new ActCode("HCFA004"), new ActContent("Parotidectomie partielle sans dissection du nerf facial", 230.41));
      builtEntries.put(new ActCode("HCFA005"), new ActContent("Parotidectomie totale avec exérèse du prolongement [processus] parapharyngien, par abord cervicofacial", 541.36));
      builtEntries.put(new ActCode("HCFA006"), new ActContent("Parotidectomie totale élargie au méat acoustique externe [conduit auditif externe] et/ou à la mandibule", 536.87));
      builtEntries.put(new ActCode("HCFA007"), new ActContent("Exérèse de petite glande salivaire [glande salivaire accessoire]", 111.78));
      builtEntries.put(new ActCode("HCFA008"), new ActContent("Parotidectomie partielle avec dissection et conservation du nerf facial", 437.75));
      builtEntries.put(new ActCode("HCFA009"), new ActContent("Parotidectomie totale avec dissection et conservation du nerf facial", 498.93));
      builtEntries.put(new ActCode("HCFA010"), new ActContent("Parotidectomie totale avec résection du nerf facial et réparation immédiate par suture ou greffe", 550.05));
      builtEntries.put(new ActCode("HCFA011"), new ActContent("Exérèse de glande submandibulaire [Submandibulectomie] [Sousmaxillectomie], par abord cervicofacial", 152.41));
      builtEntries.put(new ActCode("HCFA012"), new ActContent("Exérèse de récidive de tumeur de la glande parotide avec dissection et conservation du nerf facial", 565.48));
      builtEntries.put(new ActCode("HCFA013"), new ActContent("Parotidectomie totale par abord cervicofacial, avec exérèse du prolongement [processus] parapharyngien par abord pharyngé", 565.48));
      builtEntries.put(new ActCode("HCGA001"), new ActContent("Ablation de calcul canalaire d'une glande salivaire, par abord intrabuccal", 49.42));
      builtEntries.put(new ActCode("HCGA002"), new ActContent("Ablation de calcul canalaire d'une glande salivaire, par abord cervicofacial", 141.25));
      builtEntries.put(new ActCode("HCGA003"), new ActContent("Ablation de calcul du bassinet de la glande submandibulaire, par abord intrabuccal", 88.43));
      builtEntries.put(new ActCode("HCJA001"), new ActContent("Évacuation de collection salivaire, par abord direct", 45.84));
      builtEntries.put(new ActCode("HCLD001"), new ActContent("Cathétérisme de canal salivaire sans sialographie", 37.55));
      builtEntries.put(new ActCode("HCNM900"), new ActContent("Lithotritie de la glande parotide", 0));
      builtEntries.put(new ActCode("HCNM901"), new ActContent("Lithotritie de la glande submandibulaire", 0));
      builtEntries.put(new ActCode("HCPA001"), new ActContent("Marsupialisation de kyste de glande salivaire", 45.84));
      builtEntries.put(new ActCode("HCSA001"), new ActContent("Fermeture de fistule salivaire parenchymateuse ou juxtaglandulaire", 104.5));
      builtEntries.put(new ActCode("HDAA002"), new ActContent("Véloplastie d'allongement avec lambeau palatin", 233.38));
      builtEntries.put(new ActCode("HDFA020"), new ActContent("Uvulectomie", 167.2));
      builtEntries.put(new ActCode("HDFA021"), new ActContent("Uvulovélectomie avec palatectomie partielle", 250.8));
      builtEntries.put(new ActCode("HDFA022"), new ActContent("Uvulovélectomie", 167.2));
      builtEntries.put(new ActCode("HDMA006"), new ActContent("Pharyngoplastie ou sphinctéroplastie pour correction de séquelle phonétique d'une fente palatine", 313.5));
      builtEntries.put(new ActCode("HDMA010"), new ActContent("Véloplastie secondaire intravélaire", 233.38));
      builtEntries.put(new ActCode("HDSD002"), new ActContent("Fermeture primaire d'une fente vélaire [Staphylorraphie pour fente orofaciale]", 237.05));
      builtEntries.put(new ActCode("LBLD012"), new ActContent("Pose de dispositif intrabuccal d'expansion tissulaire pour rehaussement de crête alvéolaire", 0));
      builtEntries.put(new ActCode("LBPA024"), new ActContent("Ostéotomie d'un segment du maxillaire pour correction d'une malposition fragmentaire séquellaire d'une fente orofaciale, par abord intrabuccal", 374.48));
      builtEntries.put(new ActCode("LBPA028"), new ActContent("Ostéotomie maxillaire de type Le Fort I pour séquelle d'une fente orofaciale, par abord intrabuccal", 433.21));
      builtEntries.put(new ActCode("LCGA002"), new ActContent("Ablation de corps étranger projeté dans les tissus mous buccofaciaux, par abord intrabuccal", 63.61));
      builtEntries.put(new ActCode("LCJA002"), new ActContent("Évacuation de collection de la région des muscles masticateurs, par abord intrabuccal et par abord facial", 83.6));
      builtEntries.put(new ActCode("LCJA003"), new ActContent("Évacuation de collection périmaxillaire ou périmandibulaire, par abord intrabuccal", 20.9));
      builtEntries.put(new ActCode("LCJA004"), new ActContent("Évacuation de collection de la région des muscles masticateurs, par abord intrabuccal", 83.6));
      builtEntries.put(new ActCode("HBMD072"), new ActContent("Adjonction à une prothèse dentaire plurale fixée d'un élément intermédiaire céramométallique ou en équivalents minéraux supplémentaire, au-delà du 3e ", 10.75));
      builtEntries.put(new ActCode("HBMD081"), new ActContent("Adjonction d'un pilier d'ancrage métallique à une prothèse dentaire plurale fixée [pilier de bridge]", 107.5));
      builtEntries.put(new ActCode("HBMD082"), new ActContent("Adjonction à une prothèse dentaire plurale fixée d'un élément intermédiaire métallique supplémentaire, au-delà du 3e ", 10.75));
      builtEntries.put(new ActCode("HBMD087"), new ActContent("Adjonction d'un pilier d'ancrage céramométallique ou en équivalents minéraux  à une prothèse dentaire plurale fixée [pilier de bridge]", 107.5));
      builtEntries.put(new ActCode("HBMD342"), new ActContent("Adjonction d'un 2e élément intermédiaire métallique à une prothèse dentaire plurale  [3e élément métallique  intermédiaire de bridge] ", 0));
      builtEntries.put(new ActCode("HBMD433"), new ActContent("Adjonction d'un 2e élément intermédiaire céramométallique ou en équivalents minéraux à une prothèse dentaire plurale fixée [3e élément  céramométallique ou en équivalents minérauxcintermédiaire de bridge] ", 0));
      builtEntries.put(new ActCode("HBMD479"), new ActContent("Adjonction d'un 1er élément intermédiaire céramométallique ou en équivalents minéraux à une prothèse dentaire plurale fixée [2e élément céramométallique ou en équivalents minéraux intermédiaire de bridge] ", 0));
      builtEntries.put(new ActCode("HBMD490"), new ActContent("Adjonction d'un 1er élément intermédiaire métallique à une prothèse dentaire plurale fixée [2e élément métallique intermédiaire de bridge] ", 0));
      builtEntries.put(new ActCode("HBQK001"), new ActContent("Radiographie pelvibuccale [occlusale]", 7.98));
      builtEntries.put(new ActCode("HBQK002"), new ActContent("Radiographie panoramique dentomaxillaire", 21.28));
      builtEntries.put(new ActCode("HBQK041"), new ActContent("Radiographies intrabuccales rétroalvéolaires et/ou rétrocoronaires de 14 secteurs distincts de 1 à 3 dents contigües", 111.72));
      builtEntries.put(new ActCode("HBQK046"), new ActContent("Radiographies intrabuccales rétroalvéolaires et/ou rétrocoronaires de 9 secteurs distincts de 1 à 3 dents contigües", 71.82));
      builtEntries.put(new ActCode("HBQK065"), new ActContent("Radiographies intrabuccales rétroalvéolaires et/ou rétrocoronaires de 10 secteurs distincts de 1 à 3 dents contigües", 79.8));
      builtEntries.put(new ActCode("HBQK093"), new ActContent("Radiographies intrabuccales rétroalvéolaires et/ou rétrocoronaires de 13 secteurs distincts de 1 à 3 dents contigües", 103.74));
      builtEntries.put(new ActCode("HBQK142"), new ActContent("Radiographies intrabuccales rétroalvéolaires et/ou rétrocoronaires de 8 secteurs distincts de 1 à 3 dents contigües", 63.84));
      builtEntries.put(new ActCode("HBQK191"), new ActContent("Radiographies intrabuccales rétroalvéolaires et/ou rétrocoronaires de 2 secteurs distincts de 1 à 3 dents contigües", 15.96));
      builtEntries.put(new ActCode("HBQK331"), new ActContent("Radiographies intrabuccales rétroalvéolaires et/ou rétrocoronaires de 3 secteurs distincts de 1 à 3 dents contigües", 23.94));
      builtEntries.put(new ActCode("HBQK389"), new ActContent("Radiographie intrabuccale rétroalvéolaire et/ou rétrocoronaire d'un secteur de 1 à 3 dents contigües", 7.98));
      builtEntries.put(new ActCode("HBQK424"), new ActContent("Radiographies intrabuccales rétroalvéolaires et/ou rétrocoronaires de 11 secteurs distincts de 1 à 3 dents contigües", 87.78));
      builtEntries.put(new ActCode("HBQK428"), new ActContent("Radiographies intrabuccales rétroalvéolaires et/ou rétrocoronaires de 5 secteurs distincts de 1 à 3 dents contigües", 39.9));
      builtEntries.put(new ActCode("HBQK430"), new ActContent("Radiographies intrabuccales rétroalvéolaires et/ou rétrocoronaires de 7 secteurs distincts de 1 à 3 dents contigües", 55.86));
      builtEntries.put(new ActCode("HBQK443"), new ActContent("Radiographies intrabuccales rétroalvéolaires et/ou rétrocoronaires de 4 secteurs distincts de 1 à 3 dents contigües", 31.92));
      builtEntries.put(new ActCode("HBQK476"), new ActContent("Radiographies intrabuccales rétroalvéolaires et/ou rétrocoronaires de 12 secteurs distincts de 1 à 3 dents contigües", 95.76));
      builtEntries.put(new ActCode("HBQK480"), new ActContent("Radiographies intrabuccales rétroalvéolaires et/ou rétrocoronaires de 6 secteurs distincts de 1 à 3 dents contigües", 47.88));
      builtEntries.put(new ActCode("HCQH001"), new ActContent("Sialographie", 50.54));
      builtEntries.put(new ActCode("HCQH002"), new ActContent("Sialographie avec scanographie des glandes salivaires", 50.54));
      builtEntries.put(new ActCode("HBQK040"), new ActContent("Radiographies intrabuccales rétroalvéolaires sur un secteur de 1 à 3 dents contigües préinterventionnelle ou perinterventionnelle avec radiographie finale pour acte thérapeutique endodontique", 11.97));
      builtEntries.put(new ActCode("HBQK061"), new ActContent("Radiographie intrabuccale rétroalvéolaire et/ou rétrocoronaire d'un secteur de 1 à 3 dents contigües, perinterventionnelle et/ou finale, en dehors  d'un acte thérapeutique endodontique", 3.99));
      builtEntries.put(new ActCode("HBQK303"), new ActContent("Radiographies intrabuccales rétroalvéolaires sur un secteur de 1 à 3 dents contigües préinterventionnelle, perinterventionnelle et finale pour acte thérapeutique endodontique", 15.96));
      builtEntries.put(new ActCode("U"), new ModificateurContent("Acte réalisé en urgence par les médecins ou les chirurgiens dentistes, la nuit entre 20 h et 08 h", "25.15"));
      builtEntries.put(new ActCode("S"), new ModificateurContent("Acte réalisé en urgence par les pédiatres et les médecins généralistes ou acte thérapeutique réalisé en urgence sous anesthésie générale ou locorégionale par les autres médecins, la nuit de 00h à 08h  ", "40"));
      builtEntries.put(new ActCode("P"), new ModificateurContent("Acte réalisé en urgence par les pédiatres et médecins généralistes de 20h à 00h", "35"));
      builtEntries.put(new ActCode("F"), new ModificateurContent("Acte réalisé en urgence un dimanche ou un jour férié", "19.06"));
      builtEntries.put(new ActCode("8"), new ModificateurContent("Anesthésie d'une intervention pour glaucome, cataracte, décollement de rétine ou greffe de cornée portant sur un œil ayant déjà subi une de ces mêmes interventions, à l'exclusion de implantation, ablation ou repositionnement de cristallin artificiel ; Anesthésie pour intervention itérative sur les voies biliaires ; Anesthésie pour intervention itérative sur les voies urinaires .", "+20%"));
      builtEntries.put(new ActCode("D"), new ModificateurContent("Majoration du tarif pour acte de contrôle radiographique de segment de squelette immobilisé par contention rigide", "+24%"));
      builtEntries.put(new ActCode("B"), new ModificateurContent("Majoration du tarif pour acte de radiographie réalisé au bloc opératoire, en unité de réanimation ou au lit du patient intransportable", "+49%"));
      builtEntries.put(new ActCode("Y"), new ModificateurContent("Majoration du tarif pour acte de radiographie réalisé par un pneumologue ou un rhumatologue", "+15,80%"));
      builtEntries.put(new ActCode("Z"), new ModificateurContent("Majoration du tarif pour acte de radiographie réalisé par un radiologue", "+21,80%"));
      builtEntries.put(new ActCode("K"), new ModificateurContent("Majoration forfaits modulables pour les actes d’accouchement réalisés par les gynécologues-obstétriciens et pour les actes réalisés par les chirurgiens admettant la majoration transitoire de chirurgie, en secteur 1 ou ayant adhéré au contrat d’accès aux soins défini aux articles 36 et suivants de la convention médicale approuvée par arrêté du 22/09/2011 ", "+11,50%"));
      builtEntries.put(new ActCode("7"), new ModificateurContent("Majoration pour présence permanente du médecin anesthésiste durant toute l'intervention", "+4%"));
      builtEntries.put(new ActCode("N"), new ModificateurContent("Majoration pour réalisation d’un acte de restauration des tissus durs de la dent et/ou d’endodontie sur des dents permanentes chez un enfant de moins de 13 ans", "+15,7%"));
      builtEntries.put(new ActCode("M"), new ModificateurContent("Majoration pour soins d'urgence faits au cabinet du médecin généraliste ou du pédiatre, après examen en urgence d'un patient", "26.88"));
      builtEntries.put(new ActCode("L"), new ModificateurContent("Majoration pour traitement d'une fracture ou d'une luxation ouverte", "+20%"));
      builtEntries.put(new ActCode("J"), new ModificateurContent("Majoration transitoire de chirurgie", "+6,50%"));
      builtEntries.put(new ActCode("H"), new ModificateurContent("Modificateur numérique pour radiothérapie, niveau 1", "+100%"));
      builtEntries.put(new ActCode("Q"), new ModificateurContent("Modificateur numérique pour radiothérapie, niveau 2", "+200%"));
      builtEntries.put(new ActCode("V"), new ModificateurContent("Modificateur numérique pour radiothérapie, niveau 3", "+300%"));
      builtEntries.put(new ActCode("W"), new ModificateurContent("Modificateur numérique pour radiothérapie, niveau 4", "+400%"));
      builtEntries.put(new ActCode("O"), new ModificateurContent("Modificateur transitoire de convergence vers la cible, valeur 1", "+0,6%"));
      builtEntries.put(new ActCode("9"), new ModificateurContent("Modificateur transitoire de convergence vers la cible, valeur 2", "+3,7%"));
      builtEntries.put(new ActCode("I"), new ModificateurContent("Modificateur transitoire de convergence vers la cible, valeur 3", "+9,2%"));
      builtEntries.put(new ActCode("X"), new ModificateurContent("Modificateur transitoire de convergence vers la cible, valeur 4", "+16%"));
      builtEntries.put(new ActCode("R"), new ModificateurContent("Réalisation d'un acte de chirurgie plastique des téguments de la face, du cou, de la main et des doigts, ou d'un acte sur des plaies ou brûlures de la face ou des mains", "+50%"));
      builtEntries.put(new ActCode("E"), new ModificateurContent("Réalisation d'un acte de radiographie conventionnelle ou de scanographie chez un patient de moins de 5 ans", "+49%"));
      builtEntries.put(new ActCode("A"), new ModificateurContent("Réalisation d'une anesthésie générale ou locorégionale chez un patient de moins de 4 ans ou de plus de 80 ans", "23"));
      builtEntries.put(new ActCode("G"), new ModificateurContent("Réalisation d'une intervention pour glaucome, cataracte, décollement de rétine ou greffe de cornée chez un patient de moins de 1 an ; Extraction d'un corps étranger oesophagien ou bronchique chez un patient de moins de 3 ans ; Réalisation d'un acte de médecine nucléaire chez un patient de moins de 3 ans", "+25%"));
      builtEntries.put(new ActCode("6"), new ModificateurContent("Réalisation d'une intervention pour glaucome, cataracte, décollement de rétine ou greffe de cornée portant sur un œil ayant déjà subi une de ces mêmes interventions, à l'exclusion de implantation, ablation ou repositionnement de cristallin artificiel ; Intervention itérative sur les voies biliaires ; Intervention itérative sur les voies urinaires .", "+25%"));
      builtEntries.put(new ActCode("C"), new ModificateurContent("Réalisation d'une radiographie comparative", "+49%"));

      return builtEntries;
   }
   static private Map<ActCode, ActContent> entries;
   private ActsData(){}
}
