import java.util.Map;
import java.util.TreeMap;


public class ActsData {
	static public Map<ActCode, ActContent> getActsMap()
	{
		if (entries == null)
			entries =  buildActsMap();
		return entries;
	}
	static public void save()
	{
		ActViewsData.fillWithActs(getActsMap());
		ActViewsData.saveActViewsInfo();
	}
	static private Map<ActCode, ActContent> buildActsMap()
	{
		Map<ActCode, ActContent> entries = buildRawActsMap();
		Map<ActCode, Integer> viewsEntries = ActViewsData.getActViewsInfo();
		for (Map.Entry<ActCode, Integer> viewEntry : viewsEntries.entrySet())
		{
			ActContent rawContent = entries.get(viewEntry.getKey());
			if (rawContent != null)
			{
				rawContent.setTimesViewed(viewEntry.getValue());
			}
		}
		return entries;
	}
	static private Map<ActCode, ActContent> buildRawActsMap()
	{
      Map<ActCode, ActContent> builtEntries = new TreeMap<ActCode, ActContent>();
      builtEntries.put(new ActCode("HBGD011"), new ActContent("Ablation  d'un bloc m�tallique coul� ou d'une proth�se dentaire � tenon radiculaire scell�", 38.7));
      builtEntries.put(new ActCode("HBGD009"), new ActContent("Ablation  d'une proth�se dentaire implantoport�e", 0));
      builtEntries.put(new ActCode("HBGD027"), new ActContent("Ablation  d'une proth�se dentaire scell�e unitaire", 38.7));
      builtEntries.put(new ActCode("HBGD005"), new ActContent("Ablation d�un ancrage coronoradiculaire", 0));
      builtEntries.put(new ActCode("HBGD012"), new ActContent("Ablation de corps �tranger  d'un canal radiculaire d'une dent", 0));
      builtEntries.put(new ActCode("LBGD001"), new ActContent("Ablation de moyen de contention maxillaire et/ou mandibulaire intrabuccal", 0));
      builtEntries.put(new ActCode("HBMD017"), new ActContent("Adjonction ou changement d'1 �l�ment d'une proth�se dentaire amovible ", 21.5));
      builtEntries.put(new ActCode("HBMD249"), new ActContent("Adjonction ou changement d'1 �l�ment soud� sur une proth�se dentaire amovible sur ch�ssis m�tallique", 43));
      builtEntries.put(new ActCode("HBMD329"), new ActContent("Adjonction ou changement de 10 �l�ments d'une proth�se dentaire amovible", 118.25));
      builtEntries.put(new ActCode("HBMD410"), new ActContent("Adjonction ou changement de 10 �l�ments soud�s d'une proth�se dentaire amovible sur ch�ssis m�tallique", 430));
      builtEntries.put(new ActCode("HBMD226"), new ActContent("Adjonction ou changement de 11 �l�ments d'une proth�se dentaire amovible", 129));
      builtEntries.put(new ActCode("HBMD429"), new ActContent("Adjonction ou changement de 11 �l�ments soud�s d'une proth�se dentaire amovible sur ch�ssis m�tallique", 473));
      builtEntries.put(new ActCode("HBMD387"), new ActContent("Adjonction ou changement de 12 �l�ments d'une proth�se dentaire amovible", 139.75));
      builtEntries.put(new ActCode("HBMD281"), new ActContent("Adjonction ou changement de 12 �l�ments soud�s d'une proth�se dentaire amovible sur ch�ssis m�tallique", 516));
      builtEntries.put(new ActCode("HBMD134"), new ActContent("Adjonction ou changement de 13 �l�ments d'une proth�se dentaire amovible", 150.5));
      builtEntries.put(new ActCode("HBMD200"), new ActContent("Adjonction ou changement de 13 �l�ments soud�s d'une proth�se dentaire amovible sur ch�ssis m�tallique", 559));
      builtEntries.put(new ActCode("HBMD174"), new ActContent("Adjonction ou changement de 14 �l�ments d'une proth�se dentaire amovible", 161.25));
      builtEntries.put(new ActCode("HBMD298"), new ActContent("Adjonction ou changement de 14 �l�ments soud�s d'une proth�se dentaire amovible sur ch�ssis m�tallique", 602));
      builtEntries.put(new ActCode("HBMD114"), new ActContent("Adjonction ou changement de 2 �l�ments d'une proth�se dentaire amovible", 32.25));
      builtEntries.put(new ActCode("HBMD292"), new ActContent("Adjonction ou changement de 2 �l�ments soud�s d'une proth�se dentaire amovible sur ch�ssis m�tallique", 86));
      builtEntries.put(new ActCode("HBMD322"), new ActContent("Adjonction ou changement de 3 �l�ments d'une proth�se dentaire amovible", 43));
      builtEntries.put(new ActCode("HBMD188"), new ActContent("Adjonction ou changement de 3 �l�ments soud�s d'une proth�se dentaire amovible sur ch�ssis m�tallique", 129));
      builtEntries.put(new ActCode("HBMD404"), new ActContent("Adjonction ou changement de 4 �l�ments d'une proth�se dentaire amovible", 53.75));
      builtEntries.put(new ActCode("HBMD432"), new ActContent("Adjonction ou changement de 4 �l�ments soud�s d'une proth�se dentaire amovible sur ch�ssis m�tallique", 172));
      builtEntries.put(new ActCode("HBMD245"), new ActContent("Adjonction ou changement de 5 �l�ments d'une proth�se dentaire amovible", 64.5));
      builtEntries.put(new ActCode("HBMD283"), new ActContent("Adjonction ou changement de 5 �l�ments soud�s d'une proth�se dentaire amovible sur ch�ssis m�tallique", 215));
      builtEntries.put(new ActCode("HBMD198"), new ActContent("Adjonction ou changement de 6 �l�ments d'une proth�se dentaire amovible", 75.25));
      builtEntries.put(new ActCode("HBMD439"), new ActContent("Adjonction ou changement de 6 �l�ments soud�s d'une proth�se dentaire amovible sur ch�ssis m�tallique", 258));
      builtEntries.put(new ActCode("HBMD373"), new ActContent("Adjonction ou changement de 7 �l�ments d'une proth�se dentaire amovible", 86));
      builtEntries.put(new ActCode("HBMD425"), new ActContent("Adjonction ou changement de 7 �l�ments soud�s d'une proth�se dentaire amovible sur ch�ssis m�tallique", 301));
      builtEntries.put(new ActCode("HBMD228"), new ActContent("Adjonction ou changement de 8 �l�ments d'une proth�se dentaire amovible", 96.75));
      builtEntries.put(new ActCode("HBMD444"), new ActContent("Adjonction ou changement de 8 �l�ments soud�s d'une proth�se dentaire amovible sur ch�ssis m�tallique", 344));
      builtEntries.put(new ActCode("HBMD286"), new ActContent("Adjonction ou changement de 9 �l�ments d'une proth�se dentaire amovible", 107.5));
      builtEntries.put(new ActCode("HBMD485"), new ActContent("Adjonction ou changement de 9 �l�ments soud�s d'une proth�se dentaire amovible sur ch�ssis m�tallique", 387));
      builtEntries.put(new ActCode("HBFD014"), new ActContent("Amputation et/ou s�paration radiculaire ou coronoradiculaire d'une dent", 0));
      builtEntries.put(new ActCode("HBLD009"), new ActContent("Application d�un topique pour hypersensibilit� dentinaire", 0));
      builtEntries.put(new ActCode("HBLD045"), new ActContent("Application dentaire d�un vernis de remin�ralisation sur une arcade", 0));
      builtEntries.put(new ActCode("HBED022"), new ActContent("Autogreffe d'un germe ou d'une dent retenue, dans un site naturel ou pr�par� chirurgicalement", 209));
      builtEntries.put(new ActCode("HBED005"), new ActContent("Autogreffe d'une dent sur arcade, dans un site naturel ou pr�par� chirurgicalement", 0));
      builtEntries.put(new ActCode("HBGD042"), new ActContent("Avulsion d�1 dent temporaire retenue, incluse ou r�incluse", 83.6));
      builtEntries.put(new ActCode("HBGD039"), new ActContent("Avulsion d'1 dent ankylos�e sur arcade, avec section coronoradiculaire et s�paration des racines", 33.44));
      builtEntries.put(new ActCode("HBGD022"), new ActContent("Avulsion d'1 dent permanente sur arcade avec alv�olectomie", 33.44));
      builtEntries.put(new ActCode("HBGD031"), new ActContent("Avulsion d'1 dent permanente sur arcade avec s�paration des racines", 33.44));
      builtEntries.put(new ActCode("HBGD036"), new ActContent("Avulsion d'1 dent permanente sur arcade sans alv�olectomie", 33.44));
      builtEntries.put(new ActCode("HBGD035"), new ActContent("Avulsion d'1 dent temporaire sur arcade", 16.72));
      builtEntries.put(new ActCode("HBGD064"), new ActContent("Avulsion de 10 dents permanentes sur arcade sans alv�olectomie", 183.92));
      builtEntries.put(new ActCode("HBGD093"), new ActContent("Avulsion de 10 dents temporaires sur arcade", 91.96));
      builtEntries.put(new ActCode("HBGD356"), new ActContent("Avulsion de 11 dents permanentes sur arcade sans alv�olectomie", 200.64));
      builtEntries.put(new ActCode("HBGD362"), new ActContent("Avulsion de 11 dents temporaires sur arcade", 100.32));
      builtEntries.put(new ActCode("HBGD146"), new ActContent("Avulsion de 12 dents permanentes sur arcade sans alv�olectomie", 217.36));
      builtEntries.put(new ActCode("HBGD054"), new ActContent("Avulsion de 12 dents temporaires sur arcade", 108.68));
      builtEntries.put(new ActCode("HBGD382"), new ActContent("Avulsion de 13 dents permanentes sur arcade sans alv�olectomie", 234.08));
      builtEntries.put(new ActCode("HBGD111"), new ActContent("Avulsion de 13 dents temporaires sur arcade", 117.04));
      builtEntries.put(new ActCode("HBGD247"), new ActContent("Avulsion de 14 dents permanentes sur arcade sans alv�olectomie", 250.8));
      builtEntries.put(new ActCode("HBGD174"), new ActContent("Avulsion de 14 dents temporaires sur arcade", 125.4));
      builtEntries.put(new ActCode("HBGD197"), new ActContent("Avulsion de 15 dents permanente sur arcade sans alv�olectomie", 267.52));
      builtEntries.put(new ActCode("HBGD057"), new ActContent("Avulsion de 15 dents temporaires sur arcade", 133.76));
      builtEntries.put(new ActCode("HBGD333"), new ActContent("Avulsion de 16 dents permanente sur arcade sans alv�olectomie", 284.24));
      builtEntries.put(new ActCode("HBGD133"), new ActContent("Avulsion de 16 dents temporaires sur arcade", 142.12));
      builtEntries.put(new ActCode("HBGD261"), new ActContent("Avulsion de 17 dents permanentes sur arcade sans alv�olectomie", 300.96));
      builtEntries.put(new ActCode("HBGD123"), new ActContent("Avulsion de 17 dents temporaires sur arcade", 150.48));
      builtEntries.put(new ActCode("HBGD499"), new ActContent("Avulsion de 18 dents permanentes sur arcade sans alv�olectomie", 317.68));
      builtEntries.put(new ActCode("HBGD468"), new ActContent("Avulsion de 18 dents temporaires sur arcade", 158.84));
      builtEntries.put(new ActCode("HBGD461"), new ActContent("Avulsion de 19 dents permanentes sur arcade sans alv�olectomie", 334.4));
      builtEntries.put(new ActCode("HBGD015"), new ActContent("Avulsion de 2 canines permanentes  retenues ou � l'�tat de germe", 156.75));
      builtEntries.put(new ActCode("HBGD002"), new ActContent("Avulsion de 2 dents ankylos�es sur arcade, avec section coronoradiculaire et s�paration des racines", 50.16));
      builtEntries.put(new ActCode("HBGD034"), new ActContent("Avulsion de 2 dents permanentes sur arcade avec alv�olectomie", 50.16));
      builtEntries.put(new ActCode("HBGD032"), new ActContent("Avulsion de 2 dents permanentes sur arcade avec s�paration des racines", 50.16));
      builtEntries.put(new ActCode("HBGD043"), new ActContent("Avulsion de 2 dents permanentes sur arcade sans alv�olectomie", 50.16));
      builtEntries.put(new ActCode("HBGD026"), new ActContent("Avulsion de 2 dents temporaires retenues, incluses ou r�incluses", 125.4));
      builtEntries.put(new ActCode("HBGD037"), new ActContent("Avulsion de 2 dents temporaires sur arcade", 25.08));
      builtEntries.put(new ActCode("HBGD386"), new ActContent("Avulsion de 2 pr�molaires retenues ou � l'�tat de germe", 125.4));
      builtEntries.put(new ActCode("HBGD025"), new ActContent("Avulsion de 2 troisi�mes molaires retenues ou � l'�tat de germe", 125.4));
      builtEntries.put(new ActCode("HBGD278"), new ActContent("Avulsion de 20 dents permanentes sur arcade sans alv�olectomie", 351.12));
      builtEntries.put(new ActCode("HBGD201"), new ActContent("Avulsion de 20 dents temporaires sur arcade", 175.56));
      builtEntries.put(new ActCode("HBGD258"), new ActContent("Avulsion de 21 dents permanentes sur arcade sans alv�olectomie", 367.84));
      builtEntries.put(new ActCode("HBGD311"), new ActContent("Avulsion de 22 dents permanentes sur arcade sans alv�olectomie", 384.56));
      builtEntries.put(new ActCode("HBGD235"), new ActContent("Avulsion de 23 dents permanentes sur arcade sans alv�olectomie", 401.28));
      builtEntries.put(new ActCode("HBGD374"), new ActContent("Avulsion de 24 dents permanentes sur arcade sans alv�olectomie", 418));
      builtEntries.put(new ActCode("HBGD475"), new ActContent("Avulsion de 25 dents permanentes sur arcade sans alv�olectomie", 434.72));
      builtEntries.put(new ActCode("HBGD285"), new ActContent("Avulsion de 26 dents permanentes sur arcade sans alv�olectomie", 451.44));
      builtEntries.put(new ActCode("HBGD338"), new ActContent("Avulsion de 27 dents permanentes sur arcade sans alv�olectomie", 468.16));
      builtEntries.put(new ActCode("HBGD193"), new ActContent("Avulsion de 28 dents permanentes sur arcade sans alv�olectomie", 484.88));
      builtEntries.put(new ActCode("HBGD345"), new ActContent("Avulsion de 29 dents permanentes sur arcade sans alv�olectomie", 501.6));
      builtEntries.put(new ActCode("HBGD287"), new ActContent("Avulsion de 3 dents permanentes sur arcade avec alv�olectomie", 66.88));
      builtEntries.put(new ActCode("HBGD319"), new ActContent("Avulsion de 3 dents permanentes sur arcade sans alv�olectomie", 66.88));
      builtEntries.put(new ActCode("HBGD309"), new ActContent("Avulsion de 3 dents temporaires sur arcade", 33.44));
      builtEntries.put(new ActCode("HBGD021"), new ActContent("Avulsion de 3 troisi�mes molaires retenues ou � l'�tat de germe", 167.2));
      builtEntries.put(new ActCode("HBGD414"), new ActContent("Avulsion de 30 dents permanentes sur arcade sans alv�olectomie", 518.32));
      builtEntries.put(new ActCode("HBGD245"), new ActContent("Avulsion de 31 dents permanentes sur arcade sans alv�olectomie", 535.04));
      builtEntries.put(new ActCode("HBGD283"), new ActContent("Avulsion de 32 dents permanentes sur arcade sans alv�olectomie", 551.76));
      builtEntries.put(new ActCode("HBGD489"), new ActContent("Avulsion de 4 dents permanentes sur arcade sans alv�olectomie", 83.6));
      builtEntries.put(new ActCode("HBGD284"), new ActContent("Avulsion de 4 dents temporaires sur arcade", 41.8));
      builtEntries.put(new ActCode("HBGD038"), new ActContent("Avulsion de 4 troisi�mes molaires retenues ou � l'�tat de germe", 209));
      builtEntries.put(new ActCode("HBGD497"), new ActContent("Avulsion de 5 dents permanentes sur arcade sans alv�olectomie", 100.32));
      builtEntries.put(new ActCode("HBGD065"), new ActContent("Avulsion de 5 dents temporaires sur arcade", 50.16));
      builtEntries.put(new ActCode("HBGD106"), new ActContent("Avulsion de 6 dents permanentes sur arcade sans alv�olectomie", 117.04));
      builtEntries.put(new ActCode("HBGD462"), new ActContent("Avulsion de 6 dents temporaires sur arcade", 58.52));
      builtEntries.put(new ActCode("HBGD076"), new ActContent("Avulsion de 7 dents permanentes sur arcade sans alv�olectomie", 133.76));
      builtEntries.put(new ActCode("HBGD464"), new ActContent("Avulsion de 7 dents temporaires sur arcade", 66.88));
      builtEntries.put(new ActCode("HBGD422"), new ActContent("Avulsion de 8 dents permanentes sur arcade sans alv�olectomie", 150.48));
      builtEntries.put(new ActCode("HBGD263"), new ActContent("Avulsion de 8 dents temporaires sur arcade", 75.24));
      builtEntries.put(new ActCode("HBGD420"), new ActContent("Avulsion de 9 dents permanentes sur arcade sans alv�olectomie", 167.2));
      builtEntries.put(new ActCode("HBGD280"), new ActContent("Avulsion de 9 dents temporaires sur arcade", 83.6));
      builtEntries.put(new ActCode("HBGD040"), new ActContent("Avulsion de plusieurs dents surnum�raires � l'�tat de germe ou de plusieurs odonto�des", 125.4));
      builtEntries.put(new ActCode("HBGD282"), new ActContent("Avulsion de19 dents temporaires sur arcade", 167.2));
      builtEntries.put(new ActCode("HBGD003"), new ActContent("Avulsion d'un odonto�de inclus ou d'une dent surnum�raire � l'�tat de germe", 83.6));
      builtEntries.put(new ActCode("HBGD014"), new ActContent("Avulsion d'une canine permanente retenue ou � l'�tat de germe", 104.5));
      builtEntries.put(new ActCode("HBGD044"), new ActContent("Avulsion d'une dent � couronne sousmuqueuse ou en d�sinclusion muqueuse", 41.8));
      builtEntries.put(new ActCode("HBGD017"), new ActContent("Avulsion d'une dent ectopique", 167.2));
      builtEntries.put(new ActCode("HBGD028"), new ActContent("Avulsion d'une incisive permanente retenue ou � l'�tat de germe", 83.6));
      builtEntries.put(new ActCode("HBGD047"), new ActContent("Avulsion d'une premi�re ou d'une deuxi�me molaire permanente retenue ou � l'�tat de germe", 83.6));
      builtEntries.put(new ActCode("HBGD459"), new ActContent("Avulsion d'une pr�molaire retenue ou � l'�tat de germe ", 83.6));
      builtEntries.put(new ActCode("HBGD016"), new ActContent("Avulsion d'une racine incluse", 83.6));
      builtEntries.put(new ActCode("HBGD004"), new ActContent("Avulsion d'une troisi�me molaire mandibulaire retenue ou � l'�tat de germe", 83.6));
      builtEntries.put(new ActCode("HBGD018"), new ActContent("Avulsion d'une troisi�me molaire maxillaire retenue ou � l'�tat de germe", 83.6));
      builtEntries.put(new ActCode("HBKD396"), new ActContent("Changement d'1 facette d'une proth�se dentaire amovible", 17.2));
      builtEntries.put(new ActCode("HBKD431"), new ActContent("Changement de 2 facettes d'une proth�se dentaire amovible ", 34.4));
      builtEntries.put(new ActCode("HBKD300"), new ActContent("Changement de 3 facettes d'une proth�se dentaire amovible ", 51.6));
      builtEntries.put(new ActCode("HBKD212"), new ActContent("Changement de 4 facettes d'une proth�se dentaire amovible ", 68.8));
      builtEntries.put(new ActCode("HBKD462"), new ActContent("Changement de 5 facettes d'une proth�se dentaire amovible ", 86));
      builtEntries.put(new ActCode("HBKD213"), new ActContent("Changement de 6 facettes d'une proth�se dentaire amovible ", 103.2));
      builtEntries.put(new ActCode("HBKD140"), new ActContent("Changement de 7 facettes d'une proth�se dentaire amovible ", 120.4));
      builtEntries.put(new ActCode("HBKD244"), new ActContent("Changement de 8 facettes d'une proth�se dentaire amovible ", 137.6));
      builtEntries.put(new ActCode("HBKD005"), new ActContent("Changement de dispositif d'attachement d'une proth�se dentaire amovible supra implantaire", 32.25));
      builtEntries.put(new ActCode("HBBD005"), new ActContent("Comblement [Scellement] prophylactique des puits, sillons et fissures sur 1 dent", 21.69));
      builtEntries.put(new ActCode("HBBD006"), new ActContent("Comblement [Scellement] prophylactique des puits, sillons et fissures sur 2 dents", 43.38));
      builtEntries.put(new ActCode("HBBD007"), new ActContent("Comblement [Scellement] prophylactique des puits, sillons et fissures sur 3 dents", 65.07));
      builtEntries.put(new ActCode("HBBD004"), new ActContent("Comblement [Scellement] prophylactique des puits, sillons et fissures sur 4 dents", 86.76));
      builtEntries.put(new ActCode("HBBD039"), new ActContent("Comblement [Scellement] prophylactique des puits, sillons et fissures sur 5 dents", 108.45));
      builtEntries.put(new ActCode("HBBD404"), new ActContent("Comblement [Scellement] prophylactique des puits, sillons et fissures sur 6 dents", 130.14));
      builtEntries.put(new ActCode("HBBD098"), new ActContent("Comblement [Scellement] prophylactique des puits, sillons et fissures sur 7 dents", 151.83));
      builtEntries.put(new ActCode("HBBD427"), new ActContent("Comblement [Scellement] prophylactique des puits, sillons et fissures sur 8 dents", 173.52));
      builtEntries.put(new ActCode("HBPD001"), new ActContent("D�gagement de plusieurs dents retenues ou incluses avec pose de dispositif de traction orthodontique", 156.75));
      builtEntries.put(new ActCode("HBPD002"), new ActContent("D�gagement d'une dent retenue ou incluse avec pose d'un dispositif de traction orthodontique sans am�nagement parodontal", 104.5));
      builtEntries.put(new ActCode("HBPA001"), new ActContent("D�gagement d'une dent retenue ou incluse, avec pose d'un dispositif de traction orthodontique et am�nagement parodontal par greffe ou lambeau", 146.3));
      builtEntries.put(new ActCode("HBGD233"), new ActContent("D�sobturation endodontique d�une premi�re pr�molaire maxillaire", 0));
      builtEntries.put(new ActCode("HBGD001"), new ActContent("D�sobturation endodontique d�une pr�molaire autre que la premi�re pr�molaire maxillaire", 0));
      builtEntries.put(new ActCode("HBGD030"), new ActContent("D�sobturation endodontique d'une incisive ou d'une canine", 0));
      builtEntries.put(new ActCode("HBGD033"), new ActContent("D�sobturation endodontique d'une molaire", 0));
      builtEntries.put(new ActCode("HBJD001"), new ActContent("D�tartrage et polissage des dents", 28.92));
      builtEntries.put(new ActCode("HBMD001"), new ActContent("Eclaircissement de dent d�pulp�e", 0));
      builtEntries.put(new ActCode("HBMD005"), new ActContent("Eclaircissement des dents pulp�es", 0));
      builtEntries.put(new ActCode("HBFD006"), new ActContent("Ex�r�se de la pulpe cam�rale [Biopulpotomie] d'une dent temporaire", 16.87));
      builtEntries.put(new ActCode("HBFD033"), new ActContent("Ex�r�se de la pulpe vivante d�une incisive ou d�une canine permanente", 33.74));
      builtEntries.put(new ActCode("HBFD017"), new ActContent("Ex�r�se de la pulpe vivante d�une incisive ou d�une canine temporaire", 33.74));
      builtEntries.put(new ActCode("HBFD008"), new ActContent("Ex�r�se de la pulpe vivante d�une molaire permanente", 81.94));
      builtEntries.put(new ActCode("HBFD019"), new ActContent("Ex�r�se de la pulpe vivante d�une molaire temporaire", 81.94));
      builtEntries.put(new ActCode("HBFD021"), new ActContent("Ex�r�se de la pulpe vivante d�une premi�re pr�molaire maxillaire", 48.2));
      builtEntries.put(new ActCode("HBFD035"), new ActContent("Ex�r�se de la pulpe vivante d�une pr�molaire autre que la premi�re pr�molaire maxillaire", 48.2));
      builtEntries.put(new ActCode("HBFD001"), new ActContent("Ex�r�se du contenu canalaire non vivant d�une incisive ou d�une canine permanente", 33.74));
      builtEntries.put(new ActCode("HBFD458"), new ActContent("Ex�r�se du contenu canalaire non vivant d�une incisive ou d'une canine permanente immature", 33.74));
      builtEntries.put(new ActCode("HBFD024"), new ActContent("Ex�r�se du contenu canalaire non vivant d�une molaire permanente", 81.94));
      builtEntries.put(new ActCode("HBFD150"), new ActContent("Ex�r�se du contenu canalaire non vivant d�une molaire permanente immature", 81.94));
      builtEntries.put(new ActCode("HBFD297"), new ActContent("Ex�r�se du contenu canalaire non vivant d�une premi�re pr�molaire maxillaire", 48.2));
      builtEntries.put(new ActCode("HBFD395"), new ActContent("Ex�r�se du contenu canalaire non vivant d�une premi�re pr�molaire maxillaire immature", 48.2));
      builtEntries.put(new ActCode("HBFD003"), new ActContent("Ex�r�se du contenu canalaire non vivant d�une pr�molaire autre que la premi�re pr�molaire maxillaire", 48.2));
      builtEntries.put(new ActCode("HBFD326"), new ActContent("Ex�r�se du contenu canalaire non vivant d�une pr�molaire immature autre que la premi�re pr�molaire maxillaire ", 48.2));
      builtEntries.put(new ActCode("HBFD015"), new ActContent("Ex�r�se du contenu canalaire non vivant d'une incisive ou d'une canine temporaire", 33.74));
      builtEntries.put(new ActCode("HBFD474"), new ActContent("Ex�r�se du contenu canalaire non vivant d'une molaire temporaire", 81.94));
      builtEntries.put(new ActCode("HBFD032"), new ActContent("Ex�r�se partielle de la pulpe vivante d'une dent permanente immature pour apexog�n�se", 0));
      builtEntries.put(new ActCode("HBBA001"), new ActContent("Obturation d�une r�sorption radiculaire dentaire externe, par abord parodontal", 0));
      builtEntries.put(new ActCode("HBBD003"), new ActContent("Obturation radiculaire d'une incisive ou d'une canine apr�s apexification", 33.74));
      builtEntries.put(new ActCode("HBBD002"), new ActContent("Obturation radiculaire d'une molaire apr�s apexification", 81.94));
      builtEntries.put(new ActCode("HBBD234"), new ActContent("Obturation radiculaire d'une premi�re pr�molaire maxillaire  apr�s apexification", 48.2));
      builtEntries.put(new ActCode("HBBD001"), new ActContent("Obturation radiculaire d'une pr�molaire autre que la premi�re pr�molaire maxillaire apr�s apexification", 48.2));
      builtEntries.put(new ActCode("HBFD010"), new ActContent("Parage de plaie de la pulpe d'une dent avec coiffage", 0));
      builtEntries.put(new ActCode("HBLD003"), new ActContent("Pose d�un arc de maintien d�espace interdentaire avec dent proth�tique", 0));
      builtEntries.put(new ActCode("HBLD001"), new ActContent("Pose d�un arc de maintien d�espace interdentaire sans dent proth�tique", 0));
      builtEntries.put(new ActCode("HBLD052"), new ActContent("Pose d�un dispositif unimaxillaire de contention extracoronaire par attelle composite coll�e, sur 1 � 6 dents", 0));
      builtEntries.put(new ActCode("HBLD050"), new ActContent("Pose d�un dispositif unimaxillaire de contention extracoronaire par attelle composite coll�e, sur 7 dents ou plus", 0));
      builtEntries.put(new ActCode("HBLD053"), new ActContent("Pose d�un dispositif unimaxillaire de contention extracoronaire par attelle m�tallique coul�e et coll�e, sur 1 � 6 dents", 96.4));
      builtEntries.put(new ActCode("HBLD051"), new ActContent("Pose d�un dispositif unimaxillaire de contention extracoronaire par attelle m�tallique coul�e et coll�e, sur 7 dents ou plus", 96.4));
      builtEntries.put(new ActCode("HBLD002"), new ActContent("Pose d�un mainteneur d�espace interdentaire amovible passif", 0));
      builtEntries.put(new ActCode("HBLD006"), new ActContent("Pose d�un mainteneur d�espace interdentaire unitaire scell�", 0));
      builtEntries.put(new ActCode("HBLD236"), new ActContent("Pose d�une proth�se amovible supra-implantaire � chassis m�tallique  comportant de 9 � 13 dents ", 279.5));
      builtEntries.put(new ActCode("HBLD240"), new ActContent("Pose d�une proth�se amovible supra-implantaire � chassis m�tallique  comportant moins de 9 dents ", 236.5));
      builtEntries.put(new ActCode("HBLD132"), new ActContent("Pose d�une proth�se amovible supra-implantaire � plaque r�sine comportant moins de 9 dents ", 102.125));
      builtEntries.put(new ActCode("HBLD171"), new ActContent("Pose d�une proth�se amovible supra-implantaire compl�te bimaxillaire � chassis m�tallique ", 623.5));
      builtEntries.put(new ActCode("HBLD217"), new ActContent("Pose d�une proth�se amovible supra-implantaire compl�te unimaxillaire � chassis m�tallique", 311.75));
      builtEntries.put(new ActCode("HBLD034"), new ActContent("Pose d�une proth�se dentaire plurale transitoire ", 0));
      builtEntries.put(new ActCode("HBLD017"), new ActContent("Pose d'infrastructure coronaire sur 2 implants", 0));
      builtEntries.put(new ActCode("HBLD021"), new ActContent("Pose d'infrastructure coronaire sur 3 implants", 0));
      builtEntries.put(new ActCode("HBLD013"), new ActContent("Pose d'infrastructure coronaire sur 4 implants", 0));
      builtEntries.put(new ActCode("HBLD005"), new ActContent("Pose d'infrastructure coronaire sur 5 implants ou plus", 0));
      builtEntries.put(new ActCode("HBLD020"), new ActContent("Pose d'un appareil de posture mandibulaire [cale]", 0));
      builtEntries.put(new ActCode("HBLD008"), new ActContent("Pose d'un attachement coronoradiculaire sur une dent", 0));
      builtEntries.put(new ActCode("HBLD019"), new ActContent("Pose d'un plan de guidage des mouvements ant�ropost�rieurs mandibulaires", 0));
      builtEntries.put(new ActCode("HBLD018"), new ActContent("Pose d'un plan de lib�ration occlusale", 172.8));
      builtEntries.put(new ActCode("HBLD015"), new ActContent("Pose d'une coiffe de recouvrement d'une racine dentaire [Coping]", 0));
      builtEntries.put(new ActCode("HBLD036"), new ActContent("Pose d'une couronne dentaire dentoport�e c�ramom�tallique ou en �quivalents min�raux ", 107.5));
      builtEntries.put(new ActCode("HBLD038"), new ActContent("Pose d'une couronne dentaire dentoport�e m�tallique ", 107.5));
      builtEntries.put(new ActCode("HBLD418"), new ActContent("Pose d'une couronne dentaire implantoport�e", 107.5));
      builtEntries.put(new ActCode("HBLD037"), new ActContent("Pose d'une couronne dentaire transitoire ", 0));
      builtEntries.put(new ActCode("HBMD048"), new ActContent("Pose d'une facette c�ramique ou en �quivalents min�raux sur une dent d�un secteur incisivocanin", 0));
      builtEntries.put(new ActCode("HBLD012"), new ActContent("Pose d'une infrastructure coronaire sur 1 implant", 0));
      builtEntries.put(new ActCode("HBLD261"), new ActContent("Pose d'une infrastructure coronoradiculaire avec clavette sur une dent [Inlay core � clavette]", 144.05));
      builtEntries.put(new ActCode("HBLD007"), new ActContent("Pose d'une infrastructure coronoradiculaire sans clavette sur une dent [Inlay core]", 122.55));
      builtEntries.put(new ActCode("HBLD364"), new ActContent("Pose d'une proth�se amovible de transition � plaque base r�sine, comportant 1 � 3 dents", 64.5));
      builtEntries.put(new ActCode("HBLD231"), new ActContent("Pose d'une proth�se amovible de transition � plaque base r�sine, comportant 10 dents", 139.75));
      builtEntries.put(new ActCode("HBLD215"), new ActContent("Pose d'une proth�se amovible de transition � plaque base r�sine, comportant 11 dents", 150.5));
      builtEntries.put(new ActCode("HBLD262"), new ActContent("Pose d'une proth�se amovible de transition � plaque base r�sine, comportant 12 dents", 161.25));
      builtEntries.put(new ActCode("HBLD232"), new ActContent("Pose d'une proth�se amovible de transition � plaque base r�sine, comportant 13 dents", 172));
      builtEntries.put(new ActCode("HBLD476"), new ActContent("Pose d'une proth�se amovible de transition � plaque base r�sine, comportant 4 dents", 75.25));
      builtEntries.put(new ActCode("HBLD224"), new ActContent("Pose d'une proth�se amovible de transition � plaque base r�sine, comportant 5 dents", 86));
      builtEntries.put(new ActCode("HBLD371"), new ActContent("Pose d'une proth�se amovible de transition � plaque base r�sine, comportant 6 dents", 96.75));
      builtEntries.put(new ActCode("HBLD123"), new ActContent("Pose d'une proth�se amovible de transition � plaque base r�sine, comportant 7 dents", 107.5));
      builtEntries.put(new ActCode("HBLD270"), new ActContent("Pose d'une proth�se amovible de transition � plaque base r�sine, comportant 8 dents", 118.25));
      builtEntries.put(new ActCode("HBLD148"), new ActContent("Pose d'une proth�se amovible de transition � plaque base r�sine, comportant 9 dents", 129));
      builtEntries.put(new ActCode("HBLD032"), new ActContent("Pose d'une proth�se amovible de transition compl�te unimaxillaire � plaque base r�sine", 182.75));
      builtEntries.put(new ActCode("HBLD131"), new ActContent("Pose d'une proth�se amovible d�finitive � ch�ssis m�tallique, comportant 1 � 3 dents", 193.5));
      builtEntries.put(new ActCode("HBLD079"), new ActContent("Pose d'une proth�se amovible d�finitive � ch�ssis m�tallique, comportant 10 dents", 268.75));
      builtEntries.put(new ActCode("HBLD203"), new ActContent("Pose d'une proth�se amovible d�finitive � ch�ssis m�tallique, comportant 11 dents", 279.5));
      builtEntries.put(new ActCode("HBLD112"), new ActContent("Pose d'une proth�se amovible d�finitive � ch�ssis m�tallique, comportant 12 dents", 290.25));
      builtEntries.put(new ActCode("HBLD308"), new ActContent("Pose d'une proth�se amovible d�finitive � ch�ssis m�tallique, comportant 13 dents", 301));
      builtEntries.put(new ActCode("HBLD332"), new ActContent("Pose d'une proth�se amovible d�finitive � ch�ssis m�tallique, comportant 4 dents", 204.25));
      builtEntries.put(new ActCode("HBLD452"), new ActContent("Pose d'une proth�se amovible d�finitive � ch�ssis m�tallique, comportant 5 dents", 215));
      builtEntries.put(new ActCode("HBLD474"), new ActContent("Pose d'une proth�se amovible d�finitive � ch�ssis m�tallique, comportant 6 dents", 225.75));
      builtEntries.put(new ActCode("HBLD075"), new ActContent("Pose d'une proth�se amovible d�finitive � ch�ssis m�tallique, comportant 7 dents", 236.5));
      builtEntries.put(new ActCode("HBLD470"), new ActContent("Pose d'une proth�se amovible d�finitive � ch�ssis m�tallique, comportant 8 dents", 247.25));
      builtEntries.put(new ActCode("HBLD435"), new ActContent("Pose d'une proth�se amovible d�finitive � ch�ssis m�tallique, comportant 9 dents", 258));
      builtEntries.put(new ActCode("HBLD138"), new ActContent("Pose d'une proth�se amovible d�finitive � plaque base r�sine, comportant 10 dents", 139.75));
      builtEntries.put(new ActCode("HBLD083"), new ActContent("Pose d'une proth�se amovible d�finitive � plaque base r�sine, comportant 11 dents", 150.5));
      builtEntries.put(new ActCode("HBLD370"), new ActContent("Pose d'une proth�se amovible d�finitive � plaque base r�sine, comportant 12 dents", 161.25));
      builtEntries.put(new ActCode("HBLD349"), new ActContent("Pose d'une proth�se amovible d�finitive � plaque base r�sine, comportant 13 dents", 172));
      builtEntries.put(new ActCode("HBLD101"), new ActContent("Pose d'une proth�se amovible d�finitive � plaque base r�sine, comportant 9 dents", 129));
      builtEntries.put(new ActCode("HBLD046"), new ActContent("Pose d'une proth�se amovible d�finitive compl�te bimaxillaire � ch�ssis m�tallique", 623.5));
      builtEntries.put(new ActCode("HBLD035"), new ActContent("Pose d'une proth�se amovible d�finitive compl�te bimaxillaire � plaque base r�sine", 365.5));
      builtEntries.put(new ActCode("HBLD047"), new ActContent("Pose d'une proth�se amovible d�finitive compl�te unimaxillaire � ch�ssis m�tallique", 311.75));
      builtEntries.put(new ActCode("HBLD031"), new ActContent("Pose d'une proth�se amovible d�finitive compl�te unimaxillaire � plaque base r�sine", 182.75));
      builtEntries.put(new ActCode("HBLD048"), new ActContent("Pose d'une proth�se amovible d�finitive compl�te unimaxillaire � plaque base r�sine et d'une proth�se amovible d�finitive compl�te unimaxillaire � ch�ssis m�tallique", 494.5));
      builtEntries.put(new ActCode("HBLD492"), new ActContent("Pose d'une proth�se amovible supra-implantaire � plaque base r�sine, comportant de 9 � 13 dents", 150.5));
      builtEntries.put(new ActCode("HBLD199"), new ActContent("Pose d'une proth�se amovible supra-implantaire compl�te bimaxillaire � plaque base r�sine", 365.5));
      builtEntries.put(new ActCode("HBLD118"), new ActContent("Pose d'une proth�se amovible supra-implantaire compl�te unimaxillaire � plaque base r�sine", 182.75));
      builtEntries.put(new ActCode("HBLD030"), new ActContent("Pose d'une proth�se dentaire compl�te transviss�e implantoport�e", 182.75));
      builtEntries.put(new ActCode("HBLD043"), new ActContent("Pose d'une proth�se plurale [bridge] comportant 1 pilier d'ancrage m�tallique, 1 pilier d'ancrage c�ramom�tallique ou en �quivalents min�raux, et 1 �l�ment interm�diaire c�ramom�tallique ou en �quivalents min�raux", 279.5));
      builtEntries.put(new ActCode("HBLD040"), new ActContent("Pose d'une proth�se plurale [bridge] comportant 1 pilier d'ancrage m�tallique, 1 pilier d'ancrage c�ramom�tallique ou en �quivalents min�raux, et 1 �l�ment interm�diaire m�tallique", 279.5));
      builtEntries.put(new ActCode("HBLD023"), new ActContent("Pose d'une proth�se plurale [bridge] comportant 2 piliers d'ancrage c�ramom�talliques ou en �quivalents min�raux et 1 �l�ment interm�diaire c�ramom�tallique ou en �quivalents min�raux", 279.5));
      builtEntries.put(new ActCode("HBLD033"), new ActContent("Pose d'une proth�se plurale [bridge] comportant 2 piliers d'ancrage m�talliques et 1 �l�ment interm�diaire m�tallique", 279.5));
      builtEntries.put(new ActCode("HBED015"), new ActContent("R�duction de fracture alv�olaire en denture mixte ou incompl�te", 104.5));
      builtEntries.put(new ActCode("HBED009"), new ActContent("R�duction de fracture alv�olaire en denture permanente", 104.5));
      builtEntries.put(new ActCode("HBED016"), new ActContent("R�duction de luxation de plusieurs dents", 0));
      builtEntries.put(new ActCode("HBED011"), new ActContent("R�duction de luxation d'une dent", 0));
      builtEntries.put(new ActCode("HBMD004"), new ActContent("R�fection de la base d'une proth�se dentaire amovible compl�te", 0));
      builtEntries.put(new ActCode("HBMD007"), new ActContent("R�fection des bords et/ou de l'intrados d'une proth�se dentaire amovible partielle", 0));
      builtEntries.put(new ActCode("HBED001"), new ActContent("R�implantation d'1 dent permanente expuls�e", 96.4));
      builtEntries.put(new ActCode("HBED003"), new ActContent("R�implantation de 2 dents permanentes expuls�es", 192.8));
      builtEntries.put(new ActCode("HBED021"), new ActContent("R�implantation de 3 dents permanentes expuls�es, ou plus", 289.2));
      builtEntries.put(new ActCode("HBMD076"), new ActContent("R�paration de l'artifice cosm�tique d'une dent proth�tique par technique directe", 0));
      builtEntries.put(new ActCode("HBMD079"), new ActContent("R�paration de l'artifice cosm�tique d'une dent proth�tique par technique indirecte", 0));
      builtEntries.put(new ActCode("HBMD002"), new ActContent("R�paration d'une fracture de ch�ssis m�tallique de proth�se dentaire amovible, avec remontage d'1 �l�ment", 38.7));
      builtEntries.put(new ActCode("HBMD481"), new ActContent("R�paration d'une fracture de ch�ssis m�tallique de proth�se dentaire amovible, avec remontage de 10 �l�ments", 96.75));
      builtEntries.put(new ActCode("HBMD449"), new ActContent("R�paration d'une fracture de ch�ssis m�tallique de proth�se dentaire amovible, avec remontage de 11 �l�ments", 103.2));
      builtEntries.put(new ActCode("HBMD312"), new ActContent("R�paration d'une fracture de ch�ssis m�tallique de proth�se dentaire amovible, avec remontage de 12 �l�ments", 109.65));
      builtEntries.put(new ActCode("HBMD289"), new ActContent("R�paration d'une fracture de ch�ssis m�tallique de proth�se dentaire amovible, avec remontage de 13 �l�ments", 116.1));
      builtEntries.put(new ActCode("HBMD400"), new ActContent("R�paration d'une fracture de ch�ssis m�tallique de proth�se dentaire amovible, avec remontage de 14 �l�ments", 122.55));
      builtEntries.put(new ActCode("HBMD488"), new ActContent("R�paration d'une fracture de ch�ssis m�tallique de proth�se dentaire amovible, avec remontage de 2 �l�ments", 45.15));
      builtEntries.put(new ActCode("HBMD469"), new ActContent("R�paration d'une fracture de ch�ssis m�tallique de proth�se dentaire amovible, avec remontage de 3 �l�ments", 51.6));
      builtEntries.put(new ActCode("HBMD110"), new ActContent("R�paration d'une fracture de ch�ssis m�tallique de proth�se dentaire amovible, avec remontage de 4 �l�ments", 58.05));
      builtEntries.put(new ActCode("HBMD349"), new ActContent("R�paration d'une fracture de ch�ssis m�tallique de proth�se dentaire amovible, avec remontage de 5 �l�ments", 64.5));
      builtEntries.put(new ActCode("HBMD386"), new ActContent("R�paration d'une fracture de ch�ssis m�tallique de proth�se dentaire amovible, avec remontage de 6 �l�ments", 70.95));
      builtEntries.put(new ActCode("HBMD339"), new ActContent("R�paration d'une fracture de ch�ssis m�tallique de proth�se dentaire amovible, avec remontage de 7 �l�ments", 77.4));
      builtEntries.put(new ActCode("HBMD459"), new ActContent("R�paration d'une fracture de ch�ssis m�tallique de proth�se dentaire amovible, avec remontage de 8 �l�ments", 83.85));
      builtEntries.put(new ActCode("HBMD438"), new ActContent("R�paration d'une fracture de ch�ssis m�tallique de proth�se dentaire amovible, avec remontage de 9 �l�ments", 90.3));
      builtEntries.put(new ActCode("HBMD008"), new ActContent("R�paration d'une fracture de ch�ssis m�tallique de proth�se dentaire amovible, sans d�montage d'�l�ments", 32.25));
      builtEntries.put(new ActCode("HBMD020"), new ActContent("R�paration d'une proth�se dentaire amovible en r�sine, f�l�e ou fractur�e", 21.5));
      builtEntries.put(new ActCode("HBMD016"), new ActContent("Rescellement et/ou recollage d�une ou deux couronnes ou d'un ou deux ancrages d'une proth�se dentaire fix�e", 0));
      builtEntries.put(new ActCode("HBMD009"), new ActContent("Rescellement et/ou recollage de 3 couronnes ou plus ou de 3 ancrages ou plus d'une proth�se dentaire fix�e", 0));
      builtEntries.put(new ActCode("HBMD058"), new ActContent("Restauration d�une dent d�un secteur incisivocanin sur 1 face par mat�riau ins�r� en phase plastique, sans ancrage radiculaire", 19.28));
      builtEntries.put(new ActCode("HBMD050"), new ActContent("Restauration d�une dent d�un secteur incisivocanin sur 2 faces par mat�riau ins�r� en phase plastique sans ancrage radiculaire", 33.74));
      builtEntries.put(new ActCode("HBMD054"), new ActContent("Restauration d�une dent d�un secteur incisivocanin sur 3 faces ou plus par mat�riau ins�r� en phase plastique sans ancrage radiculaire", 40.97));
      builtEntries.put(new ActCode("HBMD053"), new ActContent("Restauration d�une dent d�un secteur pr�molomolaire sur 1 face par mat�riau ins�r� en phase plastique, sans ancrage radiculaire", 19.28));
      builtEntries.put(new ActCode("HBMD049"), new ActContent("Restauration d�une dent d�un secteur pr�molomolaire sur 2 faces par mat�riau ins�r� en phase plastique sans ancrage radiculaire", 33.74));
      builtEntries.put(new ActCode("HBMD038"), new ActContent("Restauration d�une dent d�un secteur pr�molomolaire sur 3 faces ou plus par mat�riau ins�r� en phase plastique sans ancrage radiculaire", 40.97));
      builtEntries.put(new ActCode("HBMD043"), new ActContent("Restauration d�une dent sur 1 face par mat�riau incrust� [inlay-onlay]", 19.28));
      builtEntries.put(new ActCode("HBMD046"), new ActContent("Restauration d�une dent sur 2 faces par mat�riau incrust� [inlay-onlay]", 33.74));
      builtEntries.put(new ActCode("HBMD055"), new ActContent("Restauration d�une dent sur 3 faces ou plus par mat�riau incrust� [inlay-onlay]", 40.97));
      builtEntries.put(new ActCode("HBMD044"), new ActContent("Restauration d'une dent d�un secteur incisivocanin sur 1 angle par mat�riau ins�r� en phase plastique, sans ancrage radiculaire", 43));
      builtEntries.put(new ActCode("HBMD047"), new ActContent("Restauration d'une dent d�un secteur incisivocanin sur 2 angles par mat�riau ins�r� en phase plastique, sans ancrage radiculaire", 86));
      builtEntries.put(new ActCode("HBMD042"), new ActContent("Restauration d'une dent par mat�riau ins�r� en phase plastique avec ancrage radiculaire", 79.53));
      builtEntries.put(new ActCode("HBMD019"), new ActContent("R�vision des piliers implantoport�s d'une proth�se dentaire", 18.81));
      builtEntries.put(new ActCode("HBMD061"), new ActContent("S�ance d'ajustement occlusal par coronoplastie", 0));
      builtEntries.put(new ActCode("HBLD004"), new ActContent("S�ance d'application topique intrabuccale de fluorures", 0));
      builtEntries.put(new ActCode("HBMD003"), new ActContent("S�ance de renouvellement de l'obturation radiculaire d'une dent permanente immature � l'hydroxyde de calcium", 0));
      builtEntries.put(new ActCode("YYYY079"), new ActContent("Suppl�ment pour pose de 10 dents contreplaqu�es ou massives � une proth�se amovible sur ch�ssis m�tallique", 322.5));
      builtEntries.put(new ActCode("YYYY184"), new ActContent("Suppl�ment pour pose de 11 dents contreplaqu�es ou massives � une proth�se amovible sur ch�ssis m�tallique", 354.75));
      builtEntries.put(new ActCode("YYYY284"), new ActContent("Suppl�ment pour pose de 12 dents contreplaqu�es ou massives � une proth�se amovible sur ch�ssis m�tallique", 387));
      builtEntries.put(new ActCode("YYYY236"), new ActContent("Suppl�ment pour pose de 13 dents contreplaqu�es ou massives � une proth�se amovible sur ch�ssis m�tallique", 419.25));
      builtEntries.put(new ActCode("YYYY353"), new ActContent("Suppl�ment pour pose de 14 dents contreplaqu�es ou massives � une proth�se amovible sur ch�ssis m�tallique", 451.5));
      builtEntries.put(new ActCode("YYYY329"), new ActContent("Suppl�ment pour pose de 2 dents contreplaqu�es ou massives � une proth�se amovible sur ch�ssis m�tallique", 64.5));
      builtEntries.put(new ActCode("YYYY275"), new ActContent("Suppl�ment pour pose de 2 dents contreplaqu�es sur une proth�se amovible � plaque base r�sine", 43));
      builtEntries.put(new ActCode("YYYY258"), new ActContent("Suppl�ment pour pose de 3 dents contreplaqu�es ou massives � une proth�se amovible sur ch�ssis m�tallique", 96.75));
      builtEntries.put(new ActCode("YYYY246"), new ActContent("Suppl�ment pour pose de 3 dents contreplaqu�es sur une proth�se amovible � plaque base r�sine", 64.5));
      builtEntries.put(new ActCode("YYYY259"), new ActContent("Suppl�ment pour pose de 4 dents contreplaqu�es ou massives � une proth�se amovible sur ch�ssis m�tallique", 129));
      builtEntries.put(new ActCode("YYYY478"), new ActContent("Suppl�ment pour pose de 4 dents contreplaqu�es sur une proth�se amovible � plaque base r�sine", 86));
      builtEntries.put(new ActCode("YYYY440"), new ActContent("Suppl�ment pour pose de 5 dents contreplaqu�es ou massives � une proth�se amovible sur ch�ssis m�tallique", 161.25));
      builtEntries.put(new ActCode("YYYY426"), new ActContent("Suppl�ment pour pose de 5 dents contreplaqu�es sur une proth�se amovible � plaque base r�sine", 107.5));
      builtEntries.put(new ActCode("YYYY447"), new ActContent("Suppl�ment pour pose de 6 dents contreplaqu�es ou massives � une proth�se amovible sur ch�ssis m�tallique", 193.5));
      builtEntries.put(new ActCode("YYYY389"), new ActContent("Suppl�ment pour pose de 6 dents contreplaqu�es sur une proth�se amovible � plaque base r�sine", 129));
      builtEntries.put(new ActCode("YYYY142"), new ActContent("Suppl�ment pour pose de 7 dents contreplaqu�es ou massives � une proth�se amovible sur ch�ssis m�tallique", 225.75));
      builtEntries.put(new ActCode("YYYY158"), new ActContent("Suppl�ment pour pose de 8 dents contreplaqu�es ou massives � une proth�se amovible sur ch�ssis m�tallique", 258));
      builtEntries.put(new ActCode("YYYY476"), new ActContent("Suppl�ment pour pose de 9 dents contreplaqu�es ou massives � une proth�se amovible sur ch�ssis m�tallique", 290.25));
      builtEntries.put(new ActCode("YYYY159"), new ActContent("Suppl�ment pour pose d'une dent contreplaqu�e ou massive � une proth�se amovible sur ch�ssis m�tallique", 32.25));
      builtEntries.put(new ActCode("YYYY176"), new ActContent("Suppl�ment pour pose d'une dent contreplaqu�e sur une proth�se amovible � plaque base r�sine", 21.5));
      builtEntries.put(new ActCode("LBGA004"), new ActContent("Ablation d'1 implant intraosseux intrabuccal avec r�section osseuse, chez l'adulte", 71.06));
      builtEntries.put(new ActCode("LBGA280"), new ActContent("Ablation d'1 implant intraosseux intrabuccal avec r�section osseuse, chez l'enfant", 87.78));
      builtEntries.put(new ActCode("LBGA168"), new ActContent("Ablation de 10 implants intraosseux intrabuccaux avec r�section osseuse, chez l'adulte", 202.73));
      builtEntries.put(new ActCode("LBGA113"), new ActContent("Ablation de 11 implants intraosseux intrabuccaux ou plus, avec r�section osseuse", 0));
      builtEntries.put(new ActCode("LBGA441"), new ActContent("Ablation de 2 implants intraosseux intrabuccaux  avec r�section osseuse, chez l'enfant", 106.59));
      builtEntries.put(new ActCode("LBGA003"), new ActContent("Ablation de 2 implants intraosseux intrabuccaux avec r�section osseuse, chez l'adulte", 85.69));
      builtEntries.put(new ActCode("LBGA002"), new ActContent("Ablation de 3 implants intraosseux intrabuccaux avec r�section osseuse, chez l'adulte", 100.32));
      builtEntries.put(new ActCode("LBGA354"), new ActContent("Ablation de 3 implants intraosseux intrabuccaux avec r�section osseuse, chez l'enfant", 125.4));
      builtEntries.put(new ActCode("LBGA006"), new ActContent("Ablation de 4 implants intraosseux intrabuccaux avec r�section osseuse, chez l'adulte", 114.95));
      builtEntries.put(new ActCode("LBGA049"), new ActContent("Ablation de 4 implants intraosseux intrabuccaux avec r�section osseuse, chez l'enfant", 144.21));
      builtEntries.put(new ActCode("LBGA007"), new ActContent("Ablation de 5 implants intraosseux intrabuccaux avec r�section osseuse, chez l'adulte", 129.58));
      builtEntries.put(new ActCode("LBGA008"), new ActContent("Ablation de 6 implants intraosseux intrabuccaux avec r�section osseuse, chez l'adulte", 144.21));
      builtEntries.put(new ActCode("LBGA009"), new ActContent("Ablation de 7 implants intraosseux intrabuccaux avec r�section osseuse, chez l'adulte", 158.84));
      builtEntries.put(new ActCode("LBGA139"), new ActContent("Ablation de 8 implants intraosseux intrabuccaux avec r�section osseuse, chez l'adulte", 173.47));
      builtEntries.put(new ActCode("LBGA052"), new ActContent("Ablation de 9 implants intraosseux intrabuccaux avec r�section osseuse, chez l'adulte", 188.1));
      builtEntries.put(new ActCode("LZGA001"), new ActContent("Ablation de biomat�riau de la face et/ou du cou, par abord direct", 64.84));
      builtEntries.put(new ActCode("LAGA004"), new ActContent("Ablation de mat�riel externe d'ost�osynth�se ou de distraction du cr�ne et/ou du massif facial", 68.96));
      builtEntries.put(new ActCode("LAGA002"), new ActContent("Ablation de mat�riel interne d'ost�osynth�se du massif facial sur 3 sites ou plus, par abord direct", 97.06));
      builtEntries.put(new ActCode("LAGA005"), new ActContent("Ablation de mat�riel interne d'ost�osynth�se ou de distraction du massif facial sur 2 sites, par abord direct", 90.49));
      builtEntries.put(new ActCode("LAGA003"), new ActContent("Ablation de mat�riel interne d'ost�osynth�se ou de distraction du massif facial sur un site, par abord direct", 64.84));
      builtEntries.put(new ActCode("LAGA001"), new ActContent("Ablation de plusieurs implants intraosseux cr�niens et/ou faciaux sans r�section osseuse, par abord facial", 51.69));
      builtEntries.put(new ActCode("LAGA006"), new ActContent("Ablation d'un implant intraosseux cr�nien ou facial sans r�section osseuse, par abord direct", 43.47));
      builtEntries.put(new ActCode("LAPB451"), new ActContent("D�gagement et activation d'1 implant intraosseux intrabuccal, chez l'enfant", 94.05));
      builtEntries.put(new ActCode("LAPB002"), new ActContent("D�gagement et activation d'1 implant intraosseux intrabuccaux, chez l'adulte", 87.78));
      builtEntries.put(new ActCode("LAPB122"), new ActContent("D�gagement et activation de 10 implants intraosseux intrabuccaux, chez l'adulte", 689.7));
      builtEntries.put(new ActCode("LAPB288"), new ActContent("D�gagement et activation de 11 implants intraosseux intrabuccaux ou plus", 0));
      builtEntries.put(new ActCode("LAPB004"), new ActContent("D�gagement et activation de 2 implants intraosseux intrabuccaux, chez l'adulte", 154.66));
      builtEntries.put(new ActCode("LAPB311"), new ActContent("D�gagement et activation de 2 implants intraosseux intrabuccaux, chez l'enfant", 163.02));
      builtEntries.put(new ActCode("LAPB003"), new ActContent("D�gagement et activation de 3 implants intraosseux intrabuccaux, chez l'adulte", 221.54));
      builtEntries.put(new ActCode("LAPB459"), new ActContent("D�gagement et activation de 3 implants intraosseux intrabuccaux, chez l'enfant", 231.99));
      builtEntries.put(new ActCode("LAPB001"), new ActContent("D�gagement et activation de 4 implants intraosseux intrabuccaux, chez l'adulte", 288.42));
      builtEntries.put(new ActCode("LAPB408"), new ActContent("D�gagement et activation de 4 implants intraosseux intrabuccaux, chez l'enfant", 300.96));
      builtEntries.put(new ActCode("LAPB005"), new ActContent("D�gagement et activation de 5 implants intraosseux intrabuccaux, chez l'adulte", 355.3));
      builtEntries.put(new ActCode("LAPB006"), new ActContent("D�gagement et activation de 6 implants intraosseux intrabuccaux, chez l'adulte", 422.18));
      builtEntries.put(new ActCode("LAPB007"), new ActContent("D�gagement et activation de 7 implants intraosseux intra buccaux, chez l'adulte", 489.06));
      builtEntries.put(new ActCode("LAPB047"), new ActContent("D�gagement et activation de 8 implants intraosseux intrabuccaux, chez l'adulte", 555.94));
      builtEntries.put(new ActCode("LAPB030"), new ActContent("D�gagement et activation de 9 implants intraosseux intrabuccaux, chez l'adulte", 622.82));
      builtEntries.put(new ActCode("LABA002"), new ActContent("D�s�paississement des tissus de recouvrement d'un site implantaire", 41.8));
      builtEntries.put(new ActCode("QAJH002"), new ActContent("Drainage de collection de la face, par voie transcutan�e avec guidage radiologique", 38.4));
      builtEntries.put(new ActCode("QAJH003"), new ActContent("Drainage de collection de la face, par voie transcutan�e avec guidage scanographique", 38.4));
      builtEntries.put(new ActCode("QAJH004"), new ActContent("�vacuation de collection de la face, par voie transcutan�e avec guidage radiologique", 83.6));
      builtEntries.put(new ActCode("QAJH001"), new ActContent("�vacuation de collection de la face, par voie transcutan�e avec guidage scanographique", 83.6));
      builtEntries.put(new ActCode("LAFA013"), new ActContent("Ex�r�se partielle d'un os de la face sans interruption de la continuit�, par abord direct", 167.2));
      builtEntries.put(new ActCode("LBLD015"), new ActContent("Pose d'1 implant intraosseux intrabuccal, chez l'adulte", 422.18));
      builtEntries.put(new ActCode("LBLD075"), new ActContent("Pose d'1 implant intraosseux intrabuccal, chez l'enfant", 438.9));
      builtEntries.put(new ActCode("LBLD294"), new ActContent("Pose de 10 implants intraosseux intrabuccaux, chez l'adulte", 3695.12));
      builtEntries.put(new ActCode("LBLD261"), new ActContent("Pose de 11 implants intraosseux intrabuccaux ou plus", 0));
      builtEntries.put(new ActCode("LBLD066"), new ActContent("Pose de 2 implants intraosseux intrabuccaux chez l'enfant", 806.74));
      builtEntries.put(new ActCode("LBLD010"), new ActContent("Pose de 2 implants intraosseux intrabuccaux, chez l'adulte", 785.84));
      builtEntries.put(new ActCode("LBLD281"), new ActContent("Pose de 3 implants intraosseux intrabuccaux chez l'enfant", 1174.58));
      builtEntries.put(new ActCode("LBLD013"), new ActContent("Pose de 3 implants intraosseux intrabuccaux, chez l'adulte", 1149.5));
      builtEntries.put(new ActCode("LBLD117"), new ActContent("Pose de 4 implants intraosseux intrabuccaux chez l'enfant", 1542.42));
      builtEntries.put(new ActCode("LBLD004"), new ActContent("Pose de 4 implants intraosseux intrabuccaux, chez l'adulte", 1513.16));
      builtEntries.put(new ActCode("LBLD020"), new ActContent("Pose de 5 implants intraosseux intrabuccaux, chez l'adulte", 1876.82));
      builtEntries.put(new ActCode("LBLD025"), new ActContent("Pose de 6 implants intraosseux intrabuccaux, chez l'adulte", 2240.48));
      builtEntries.put(new ActCode("LBLD026"), new ActContent("Pose de 7 implants intraosseux intrabuccaux, chez l'adulte", 2604.14));
      builtEntries.put(new ActCode("LBLD038"), new ActContent("Pose de 8 implants intraosseux intrabuccaux, chez l'adulte", 2967.8));
      builtEntries.put(new ActCode("LBLD200"), new ActContent("Pose de 9 implants intraosseux intrabuccaux, chez l'adulte", 3331.46));
      builtEntries.put(new ActCode("LBLD034"), new ActContent("Pose de barre de conjonction entre 2 implants intrabuccaux", 96.14));
      builtEntries.put(new ActCode("LBLD057"), new ActContent("Pose de barre de conjonction entre 3 implants intrabuccaux ou plus", 144.21));
      builtEntries.put(new ActCode("LBLD019"), new ActContent("Pose de moyen de liaison sur 1 implant pr�proth�tique intraosseux intrabuccal", 160.93));
      builtEntries.put(new ActCode("LBLD214"), new ActContent("Pose de moyen de liaison sur 10 implants pr�proth�tiques intraosseux intrabuccaux", 1496.44));
      builtEntries.put(new ActCode("LBLD420"), new ActContent("Pose de moyen de liaison sur 11 implants pr�proth�tiques intraosseux intrabuccaux ou plus", 0));
      builtEntries.put(new ActCode("LBLD073"), new ActContent("Pose de moyen de liaison sur 2 implants pr�proth�tiques intraosseux intrabuccaux", 309.32));
      builtEntries.put(new ActCode("LBLD086"), new ActContent("Pose de moyen de liaison sur 3 implants pr�proth�tiques intraosseux intrabuccaux", 457.71));
      builtEntries.put(new ActCode("LBLD193"), new ActContent("Pose de moyen de liaison sur 4 implants pr�proth�tiques intraosseux intrabuccaux", 606.1));
      builtEntries.put(new ActCode("LBLD447"), new ActContent("Pose de moyen de liaison sur 5 implants pr�proth�tiques intraosseux intrabuccaux", 754.49));
      builtEntries.put(new ActCode("LBLD270"), new ActContent("Pose de moyen de liaison sur 6 implants pr�proth�tiques intraosseux intrabuccaux", 902.88));
      builtEntries.put(new ActCode("LBLD143"), new ActContent("Pose de moyen de liaison sur 7 implants pr�proth�tiques intraosseux intrabuccaux", 1051.27));
      builtEntries.put(new ActCode("LBLD235"), new ActContent("Pose de moyen de liaison sur 8 implants pr�proth�tiques intraosseux intrabuccaux", 1199.66));
      builtEntries.put(new ActCode("LBLD311"), new ActContent("Pose de moyen de liaison sur 9 implants pr�proth�tiques intraosseux intrabuccaux", 1348.05));
      builtEntries.put(new ActCode("LALB001"), new ActContent("Pose de moyen de liaison sur implants cr�niens et/ou faciaux", 115.2));
      builtEntries.put(new ActCode("LALA001"), new ActContent("Pose de plusieurs implants intraosseux cr�niens et/ou faciaux pour fixation d'�pith�se", 250.8));
      builtEntries.put(new ActCode("LALA002"), new ActContent("Pose d'un implant intraosseux cr�nien ou facial pour fixation d'�pith�se ou d'appareillage auditif ost�o-int�gr�", 167.2));
      builtEntries.put(new ActCode("LBFA031"), new ActContent("R�section d'hypertrophie osseuse intrabuccale", 34.55));
      builtEntries.put(new ActCode("HAHA002"), new ActContent("Biopsie de l�vre", 20.97));
      builtEntries.put(new ActCode("HAHD001"), new ActContent("Frottis et/ou pr�l�vement intrabuccal", 10.2));
      builtEntries.put(new ActCode("HAHD002"), new ActContent("Biopsie de la cavit� orale et/ou de l'oropharynx, avec guidage par des colorations vitales", 23.24));
      builtEntries.put(new ActCode("HAHD003"), new ActContent("Biopsie de la cavit� orale et/ou de l'oropharynx, sans coloration vitale", 19.67));
      builtEntries.put(new ActCode("HCHA001"), new ActContent("Biopsie de glande salivaire majeure [principale]", 29.49));
      builtEntries.put(new ActCode("HCHA002"), new ActContent("Biopsie des petites glandes salivaires [glandes salivaires mineures] [glandes salivaires accessoires]", 23.68));
      builtEntries.put(new ActCode("HCHB001"), new ActContent("Ponction ou cytoponction de glande salivaire, par voie transcutan�e", 28.15));
      builtEntries.put(new ActCode("HGHD002"), new ActContent("Biopsie ent�rale � l'aveugle � la sonde, par voie nasale", 57.6));
      builtEntries.put(new ActCode("HJHD001"), new ActContent("Biopsie rectale par aspiration de la muqueuse par sonde", 22.24));
      builtEntries.put(new ActCode("HJHD002"), new ActContent("Biopsie de la musculeuse du rectum, par voie anale", 60.94));
      builtEntries.put(new ActCode("HKHA001"), new ActContent("Biopsie de l�sion de la r�gion p�rianale et/ou du canal anal", 26.72));
      builtEntries.put(new ActCode("HPHB001"), new ActContent("Ponction-lavage du p�ritoine, avec pose de cath�ter intrap�riton�al par voie transcutan�e", 96.25));
      builtEntries.put(new ActCode("HPHB002"), new ActContent("Ponction du cul-de-sac recto-ut�rin [de Douglas] [Culdocent�se], par voie transvaginale sans guidage", 24.93));
      builtEntries.put(new ActCode("HPHB003"), new ActContent("Ponction d'un �panchement p�riton�al, par voie transcutan�e", 24.51));
      builtEntries.put(new ActCode("HPHJ001"), new ActContent("Ponction du cul-de-sac recto-ut�rin [de Douglas] [Culdocent�se], par voie transvaginale avec guidage �chographique", 19.2));
      builtEntries.put(new ActCode("HBAA338"), new ActContent("Allongement coronaire par gingivectomie sur une dent", 0));
      builtEntries.put(new ActCode("HBBA002"), new ActContent("Ost�oplastie additive de l'arcade alv�olaire sur un secteur de 4 � 6 dents", 269.61));
      builtEntries.put(new ActCode("HBBA003"), new ActContent("Ost�oplastie additive de l'arcade alv�olaire sur un secteur de 1 � 3 dents", 85.69));
      builtEntries.put(new ActCode("HBBA004"), new ActContent("Ost�oplastie additive de l'arcade alv�olaire sur un secteur de 7 dents ou plus", 298.87));
      builtEntries.put(new ActCode("HBED023"), new ActContent("Greffe �pith�lioconjonctive ou conjonctive sur la gencive, sur un secteur de 1 � 3 dents", 79.42));
      builtEntries.put(new ActCode("HBED024"), new ActContent("Greffe �pith�lioconjonctive ou conjonctive sur la gencive, sur un sextant", 94.05));
      builtEntries.put(new ActCode("HBFA003"), new ActContent("Ost�oplastie soustractive de l'arcade alv�olaire sur un secteur de 7 dents ou plus", 0));
      builtEntries.put(new ActCode("HBFA004"), new ActContent("Ost�oplastie soustractive de l'arcade alv�olaire sur un secteur de 4 � 6 dents", 0));
      builtEntries.put(new ActCode("HBFA005"), new ActContent("Ost�oplastie soustractive de l'arcade alv�olaire sur un secteur de 1 � 3 dents", 0));
      builtEntries.put(new ActCode("HBFA006"), new ActContent("Gingivectomie sur un secteur de 1 � 3 dents", 0));
      builtEntries.put(new ActCode("HBFA007"), new ActContent("Gingivectomie sur un secteur de 4 � 6 dents", 41.8));
      builtEntries.put(new ActCode("HBFA008"), new ActContent("Gingivectomie  sur un secteur de 7 dents ou plus", 0));
      builtEntries.put(new ActCode("HBFA012"), new ActContent("Ex�r�se d'hypertrophie gingivale ou de cr�te flottante sur une arcade maxillaire ou mandibulaire compl�te", 0));
      builtEntries.put(new ActCode("HBFA013"), new ActContent("Ex�r�se d'hypertrophie gingivale ou de cr�te flottante localis�e", 0));
      builtEntries.put(new ActCode("HBGB001"), new ActContent("Curetage d'alv�ole dentaire", 0));
      builtEntries.put(new ActCode("HBGB002"), new ActContent("Curetage p�riapical avec r�section de l'apex et obturation radiculaire d'une pr�molaire", 98.36));
      builtEntries.put(new ActCode("HBGB003"), new ActContent("Curetage p�riapical avec r�section de l'apex et obturation radiculaire d'une incisive ou d'une canine", 83.9));
      builtEntries.put(new ActCode("HBGB004"), new ActContent("Curetage p�riapical avec r�section de l'apex et obturation radiculaire d'une molaire", 132.1));
      builtEntries.put(new ActCode("HBGB005"), new ActContent("Curetage p�riapical avec r�section de l'apex d'une racine dentaire endodontiquement trait�e", 50.16));
      builtEntries.put(new ActCode("HBGB006"), new ActContent("Surfa�age radiculaire dentaire sur un sextant", 0));
      builtEntries.put(new ActCode("HBJA003"), new ActContent("Assainissement parodontal par lambeau sur un sextant", 0));
      builtEntries.put(new ActCode("HBJB001"), new ActContent("�vacuation d'abc�s parodontal", 40));
      builtEntries.put(new ActCode("HBMA001"), new ActContent("Plastie mucogingivale par lambeau d�plac� lat�ralement, coronairement ou apicalement", 75.24));
      builtEntries.put(new ActCode("HBMA003"), new ActContent("Ost�oplastie d'une alv�ole dentaire avec comblement par autogreffe osseuse", 0));
      builtEntries.put(new ActCode("HBMA004"), new ActContent("R�g�n�ration parodontale ", 0));
      builtEntries.put(new ActCode("HBMA006"), new ActContent("Ost�oplastie d'une alv�ole dentaire avec comblement par biomat�riau", 0));
      builtEntries.put(new ActCode("HBMD018"), new ActContent("S�ance de pr�paration [mise en condition] tissulaire des surfaces d'appui muqueux d'une proth�se dentaire, sur une arcade", 0));
      builtEntries.put(new ActCode("HCCA001"), new ActContent("D�rivation du conduit parotidien [de St�non] pour suppl�ance lacrymale", 215.94));
      builtEntries.put(new ActCode("HCCA002"), new ActContent("Suture de plaie de conduit salivaire", 103.15));
      builtEntries.put(new ActCode("HCCD001"), new ActContent("D�rivation oropharyng�e bilat�rale du conduit parotidien [de St�non], par voie buccale", 303.6));
      builtEntries.put(new ActCode("HCEA001"), new ActContent("Transposition unilat�rale ou bilat�rale des conduits submandibulaires [de Wharton]", 149.13));
      builtEntries.put(new ActCode("HCFA001"), new ActContent("Ex�r�se de glande submandibulaire [Submandibulectomie] [Sousmaxillectomie] �largie � sa loge, par abord cervicofacial", 203.76));
      builtEntries.put(new ActCode("HCFA002"), new ActContent("Parotidectomie totale avec r�section du nerf facial", 410.06));
      builtEntries.put(new ActCode("HCFA003"), new ActContent("Ex�r�se de glande sublinguale, par abord direct", 104.5));
      builtEntries.put(new ActCode("HCFA004"), new ActContent("Parotidectomie partielle sans dissection du nerf facial", 230.41));
      builtEntries.put(new ActCode("HCFA005"), new ActContent("Parotidectomie totale avec ex�r�se du prolongement [processus] parapharyngien, par abord cervicofacial", 541.36));
      builtEntries.put(new ActCode("HCFA006"), new ActContent("Parotidectomie totale �largie au m�at acoustique externe [conduit auditif externe] et/ou � la mandibule", 536.87));
      builtEntries.put(new ActCode("HCFA007"), new ActContent("Ex�r�se de petite glande salivaire [glande salivaire accessoire]", 111.78));
      builtEntries.put(new ActCode("HCFA008"), new ActContent("Parotidectomie partielle avec dissection et conservation du nerf facial", 437.75));
      builtEntries.put(new ActCode("HCFA009"), new ActContent("Parotidectomie totale avec dissection et conservation du nerf facial", 498.93));
      builtEntries.put(new ActCode("HCFA010"), new ActContent("Parotidectomie totale avec r�section du nerf facial et r�paration imm�diate par suture ou greffe", 550.05));
      builtEntries.put(new ActCode("HCFA011"), new ActContent("Ex�r�se de glande submandibulaire [Submandibulectomie] [Sousmaxillectomie], par abord cervicofacial", 152.41));
      builtEntries.put(new ActCode("HCFA012"), new ActContent("Ex�r�se de r�cidive de tumeur de la glande parotide avec dissection et conservation du nerf facial", 565.48));
      builtEntries.put(new ActCode("HCFA013"), new ActContent("Parotidectomie totale par abord cervicofacial, avec ex�r�se du prolongement [processus] parapharyngien par abord pharyng�", 565.48));
      builtEntries.put(new ActCode("HCGA001"), new ActContent("Ablation de calcul canalaire d'une glande salivaire, par abord intrabuccal", 49.42));
      builtEntries.put(new ActCode("HCGA002"), new ActContent("Ablation de calcul canalaire d'une glande salivaire, par abord cervicofacial", 141.25));
      builtEntries.put(new ActCode("HCGA003"), new ActContent("Ablation de calcul du bassinet de la glande submandibulaire, par abord intrabuccal", 88.43));
      builtEntries.put(new ActCode("HCJA001"), new ActContent("�vacuation de collection salivaire, par abord direct", 45.84));
      builtEntries.put(new ActCode("HCLD001"), new ActContent("Cath�t�risme de canal salivaire sans sialographie", 37.55));
      builtEntries.put(new ActCode("HCNM900"), new ActContent("Lithotritie de la glande parotide", 0));
      builtEntries.put(new ActCode("HCNM901"), new ActContent("Lithotritie de la glande submandibulaire", 0));
      builtEntries.put(new ActCode("HCPA001"), new ActContent("Marsupialisation de kyste de glande salivaire", 45.84));
      builtEntries.put(new ActCode("HCSA001"), new ActContent("Fermeture de fistule salivaire parenchymateuse ou juxtaglandulaire", 104.5));
      /*builtEntries.put(new ActCode("U"), new ActContent("Acte r�alis� en urgence par les m�decins ou les chirurgiens dentistes, la nuit entre 20 h et 08 h", "25.15"));
      builtEntries.put(new ActCode("S"), new ActContent("Acte r�alis� en urgence par les p�diatres et les m�decins g�n�ralistes ou acte th�rapeutique r�alis� en urgence sous anesth�sie g�n�rale ou locor�gionale par les autres m�decins, la nuit de 00h � 08h  ", "40"));
      builtEntries.put(new ActCode("P"), new ActContent("Acte r�alis� en urgence par les p�diatres et m�decins g�n�ralistes de 20h � 00h", "35"));
      builtEntries.put(new ActCode("F"), new ActContent("Acte r�alis� en urgence un dimanche ou un jour f�ri�", "19.06"));
      builtEntries.put(new ActCode("8"), new ActContent("Anesth�sie d'une intervention pour glaucome, cataracte, d�collement de r�tine ou greffe de corn�e portant sur un oeil ayant d�j� subi une de ces m�mes interventions, � l'exclusion de implantation, ablation ou repositionnement de cristallin artificiel ; Anesth�sie pour intervention it�rative sur les voies biliaires ; Anesth�sie pour intervention it�rative sur les voies urinaires .", "+20%"));
      builtEntries.put(new ActCode("D"), new ActContent("Majoration du tarif pour acte de contr�le radiographique de segment de squelette immobilis� par contention rigide", "+24%"));
      builtEntries.put(new ActCode("B"), new ActContent("Majoration du tarif pour acte de radiographie r�alis� au bloc op�ratoire, en unit� de r�animation ou au lit du patient intransportable", "+49%"));
      builtEntries.put(new ActCode("Y"), new ActContent("Majoration du tarif pour acte de radiographie r�alis� par un pneumologue ou un rhumatologue", "+15,80%"));
      builtEntries.put(new ActCode("Z"), new ActContent("Majoration du tarif pour acte de radiographie r�alis� par un radiologue", "+21,80%"));
      builtEntries.put(new ActCode("K"), new ActContent("Majoration forfaits modulables pour les actes d�accouchement r�alis�s par les gyn�cologues-obst�triciens et pour les actes r�alis�s par les chirurgiens admettant la majoration transitoire de chirurgie, en secteur 1 ou ayant adh�r� au contrat d�acc�s aux soins d�fini aux articles 36 et suivants de la convention m�dicale approuv�e par arr�t� du 22/09/2011 ", "+11,50%"));
      builtEntries.put(new ActCode("7"), new ActContent("Majoration pour pr�sence permanente du m�decin anesth�siste durant toute l'intervention", "+4%"));
      builtEntries.put(new ActCode("N "), new ActContent("Majoration pour r�alisation d�un acte de restauration des tissus durs de la dent et/ou d�endodontie sur des dents permanentes chez un enfant de moins de 13 ans", "+15,7%"));
      builtEntries.put(new ActCode("M"), new ActContent("Majoration pour soins d'urgence faits au cabinet du m�decin g�n�raliste ou du p�diatre, apr�s examen en urgence d'un patient", "26.88"));
      builtEntries.put(new ActCode("L"), new ActContent("Majoration pour traitement d'une fracture ou d'une luxation ouverte", "+20%"));
      builtEntries.put(new ActCode("J"), new ActContent("Majoration transitoire de chirurgie", "+6,50%"));
      builtEntries.put(new ActCode("H"), new ActContent("Modificateur num�rique pour radioth�rapie, niveau 1", "+100%"));
      builtEntries.put(new ActCode("Q"), new ActContent("Modificateur num�rique pour radioth�rapie, niveau 2", "+200%"));
      builtEntries.put(new ActCode("V"), new ActContent("Modificateur num�rique pour radioth�rapie, niveau 3", "+300%"));
      builtEntries.put(new ActCode("W"), new ActContent("Modificateur num�rique pour radioth�rapie, niveau 4", "+400%"));
      builtEntries.put(new ActCode("O"), new ActContent("Modificateur transitoire de convergence vers la cible, valeur 1", "+0,6%"));
      builtEntries.put(new ActCode("9"), new ActContent("Modificateur transitoire de convergence vers la cible, valeur 2", "+3,7%"));
      builtEntries.put(new ActCode("I"), new ActContent("Modificateur transitoire de convergence vers la cible, valeur 3", "+9,2%"));
      builtEntries.put(new ActCode("X"), new ActContent("Modificateur transitoire de convergence vers la cible, valeur 4", "+16%"));
      builtEntries.put(new ActCode("R"), new ActContent("R�alisation d'un acte de chirurgie plastique des t�guments de la face, du cou, de la main et des doigts, ou d'un acte sur des plaies ou br�lures de la face ou des mains", "+50%"));
      builtEntries.put(new ActCode("E"), new ActContent("R�alisation d'un acte de radiographie conventionnelle ou de scanographie chez un patient de moins de 5 ans", "+49%"));
      builtEntries.put(new ActCode("A"), new ActContent("R�alisation d'une anesth�sie g�n�rale ou locor�gionale chez un patient de moins de 4 ans ou de plus de 80 ans", "23"));
      builtEntries.put(new ActCode("G"), new ActContent("R�alisation d'une intervention pour glaucome, cataracte, d�collement de r�tine ou greffe de corn�e chez un patient de moins de 1 an ; Extraction d'un corps �tranger oesophagien ou bronchique chez un patient de moins de 3 ans ; R�alisation d'un acte de m�decine nucl�aire chez un patient de moins de 3 ans", "+25%"));
      builtEntries.put(new ActCode("6"), new ActContent("R�alisation d'une intervention pour glaucome, cataracte, d�collement de r�tine ou greffe de corn�e portant sur un oeil ayant d�j� subi une de ces m�mes interventions, � l'exclusion de implantation, ablation ou repositionnement de cristallin artificiel ; Intervention it�rative sur les voies biliaires ; Intervention it�rative sur les voies urinaires .", "+25%"));
      builtEntries.put(new ActCode("C"), new ActContent("R�alisation d'une radiographie comparative", "+49%"));
      */
      return builtEntries;
   }
   static private Map<ActCode, ActContent> entries;
   private ActsData(){}
}
