import java.util.Map;
import java.util.TreeMap;


public class ActsData {
	static public Map<ActCode, ActContent> getActsMap()
	{
		if (entries == null)
			entries =  buildActsMap();
		return entries;
	}
	static public void save()
	{
		ActViewsData.fillWithActs(getActsMap());
		ActViewsData.saveActViewsInfo();
	}
	static private Map<ActCode, ActContent> buildActsMap()
	{
		Map<ActCode, ActContent> entries = buildRawActsMap();
		Map<ActCode, Integer> viewsEntries = ActViewsData.getActViewsInfo();
		for (Map.Entry<ActCode, Integer> viewEntry : viewsEntries.entrySet())
		{
			ActContent rawContent = entries.get(viewEntry.getKey());
			if (rawContent != null)
			{
				rawContent.setTimesViewed(viewEntry.getValue());
			}
		}
		return entries;
	}
	static private Map<ActCode, ActContent> buildRawActsMap()
	{
		Map<ActCode, ActContent> builtEntries = new TreeMap<ActCode, ActContent>();
		builtEntries.put(new ActCode("HBBA001"), new ActContent("Obturation d'une résorption radiculaire dentaire externe, par abord parodontal", 0));
		builtEntries.put(new ActCode("HBBD001"), new ActContent("Obturation radiculaire d'une prémolaire autre que la première prémolaire maxillaire après apexification", 48.20));
		builtEntries.put(new ActCode("HBBD002"), new ActContent("Obturation radiculaire d'une molaire après apexification", 81.94));
		builtEntries.put(new ActCode("HBBD003"), new ActContent("Obturation radiculaire d'une incisive ou d'une canine après apexification", 33.74));
		builtEntries.put(new ActCode("HBBD004"), new ActContent("Comblement [Scellement] prophylactique des puits, sillons et fissures sur 4 dents", 86.76));
		builtEntries.put(new ActCode("HBBD005"), new ActContent("Comblement [Scellement] prophylactique des puits, sillons et fissures sur 1 dent", 21.69));
		builtEntries.put(new ActCode("HBBD006"), new ActContent("Comblement [Scellement] prophylactique des puits, sillons et fissures sur 2 dents", 43.38));
		builtEntries.put(new ActCode("HBBD007"), new ActContent("Comblement [Scellement] prophylactique des puits, sillons et fissures sur 3 dents", 65.07));
		builtEntries.put(new ActCode("HBBD039"), new ActContent("Comblement [Scellement] prophylactique des puits, sillons et fissures sur 5 dents", 108.45));
		builtEntries.put(new ActCode("HBBD098"), new ActContent("Comblement [Scellement] prophylactique des puits, sillons et fissures sur 7 dents", 151.83));
		builtEntries.put(new ActCode("HBBD234"), new ActContent("Obturation radiculaire d'une première prémolaire maxillaire  après apexification", 48.20));
		builtEntries.put(new ActCode("HBBD404"), new ActContent("Comblement [Scellement] prophylactique des puits, sillons et fissures sur 6 dents", 130.14));
		builtEntries.put(new ActCode("HBBD427"), new ActContent("Comblement [Scellement] prophylactique des puits, sillons et fissures sur 8 dents", 173.52));
		builtEntries.put(new ActCode("HBED001"), new ActContent("Réimplantation d'1 dent permanente expulsée", 96.40));
		builtEntries.put(new ActCode("HBED003"), new ActContent("Réimplantation de 2 dents permanentes expulsées", 192.80));
		builtEntries.put(new ActCode("HBED005"), new ActContent("Autogreffe d'une dent sur arcade, dans un site naturel ou préparé chirurgicalement", 0));
		builtEntries.put(new ActCode("HBED009"), new ActContent("Réduction de fracture alvéolaire en denture permanente", 104.50));
		builtEntries.put(new ActCode("HBED011"), new ActContent("Réduction de luxation d'une dent", 0));
		builtEntries.put(new ActCode("HBED015"), new ActContent("Réduction de fracture alvéolaire en denture mixte ou incomplète", 104.50));
		builtEntries.put(new ActCode("HBED016"), new ActContent("Réduction de luxation de plusieurs dents", 0));
		builtEntries.put(new ActCode("HBED021"), new ActContent("Réimplantation de 3 dents permanentes expulsées, ou plus", 289.20));
		builtEntries.put(new ActCode("HBED022"), new ActContent("Autogreffe d'un germe ou d'une dent retenue, dans un site naturel ou préparé chirurgicalement", 209.00));
		builtEntries.put(new ActCode("HBFD001"), new ActContent("Exérèse du contenu canalaire non vivant d'une incisive ou d'une canine permanente", 33.74));
		builtEntries.put(new ActCode("HBFD003"), new ActContent("Exérèse du contenu canalaire non vivant d'une prémolaire autre que la première prémolaire maxillaire", 48.20));
		builtEntries.put(new ActCode("HBFD006"), new ActContent("Exérèse de la pulpe camérale [Biopulpotomie] d'une dent temporaire", 16.87));
		builtEntries.put(new ActCode("HBFD008"), new ActContent("Exérèse de la pulpe vivante d'une molaire permanente", 81.94));
		builtEntries.put(new ActCode("HBFD010"), new ActContent("Parage de plaie de la pulpe d'une dent avec coiffage", 0));
		builtEntries.put(new ActCode("HBFD014"), new ActContent("Amputation et/ou séparation radiculaire ou coronoradiculaire d'une dent", 0));
		builtEntries.put(new ActCode("HBFD015"), new ActContent("Exérèse du contenu canalaire non vivant d'une incisive ou d'une canine temporaire", 33.74));
		builtEntries.put(new ActCode("HBFD017"), new ActContent("Exérèse de la pulpe vivante d'une incisive ou d'une canine temporaire", 33.74));
		builtEntries.put(new ActCode("HBFD019"), new ActContent("Exérèse de la pulpe vivante d'une molaire temporaire", 81.94));
		builtEntries.put(new ActCode("HBFD021"), new ActContent("Exérèse de la pulpe vivante d'une première prémolaire maxillaire", 48.20));
		builtEntries.put(new ActCode("HBFD024"), new ActContent("Exérèse du contenu canalaire non vivant d'une molaire permanente", 81.94));
		builtEntries.put(new ActCode("HBFD032"), new ActContent("Exérèse partielle de la pulpe vivante d'une dent permanente immature pour apexogénèse", 0));
		builtEntries.put(new ActCode("HBFD033"), new ActContent("Exérèse de la pulpe vivante d'une incisive ou d'une canine permanente", 33.74));
		builtEntries.put(new ActCode("HBFD035"), new ActContent("Exérèse de la pulpe vivante d'une prémolaire autre que la première prémolaire maxillaire", 48.20));
		builtEntries.put(new ActCode("HBFD150"), new ActContent("Exérèse du contenu canalaire non vivant d'une molaire permanente immature", 81.94));
		builtEntries.put(new ActCode("HBFD297"), new ActContent("Exérèse du contenu canalaire non vivant d'une première prémolaire maxillaire", 48.20));
		builtEntries.put(new ActCode("HBFD326"), new ActContent("Exérèse du contenu canalaire non vivant d'une prémolaire immature autre que la première prémolaire maxillaire ", 48.20));
		builtEntries.put(new ActCode("HBFD395"), new ActContent("Exérèse du contenu canalaire non vivant d'une première prémolaire maxillaire immature", 48.20));
		builtEntries.put(new ActCode("HBFD458"), new ActContent("Exérèse du contenu canalaire non vivant d'une incisive ou d'une canine permanente immature", 33.74));
		builtEntries.put(new ActCode("HBFD474"), new ActContent("Exérèse du contenu canalaire non vivant d'une molaire temporaire", 81.94));
		builtEntries.put(new ActCode("HBGD001"), new ActContent("Désobturation endodontique d'une prémolaire autre que la première prémolaire maxillaire", 0));
		builtEntries.put(new ActCode("HBGD002"), new ActContent("Avulsion de 2 dents ankylosées sur arcade, avec section coronoradiculaire et séparation des racines", 50.16));
		builtEntries.put(new ActCode("HBGD003"), new ActContent("Avulsion d'un odontoïde inclus ou d'une dent surnuméraire à l'état de germe", 83.60));
		builtEntries.put(new ActCode("HBGD004"), new ActContent("Avulsion d'une troisième molaire mandibulaire retenue ou à l'état de germe", 83.60));
		builtEntries.put(new ActCode("HBGD005"), new ActContent("Ablation d'un ancrage coronoradiculaire", 0));
		builtEntries.put(new ActCode("HBGD009"), new ActContent("Ablation  d'une prothèse dentaire implantoportée", 0));
		builtEntries.put(new ActCode("HBGD011"), new ActContent("Ablation  d'un bloc métallique coulé ou d'une prothèse dentaire à tenon radiculaire scellé", 38.70));
		builtEntries.put(new ActCode("HBGD012"), new ActContent("Ablation de corps étranger  d'un canal radiculaire d'une dent", 0));
		builtEntries.put(new ActCode("HBGD014"), new ActContent("Avulsion d'une canine permanente retenue ou à l'état de germe", 104.50));
		builtEntries.put(new ActCode("HBGD015"), new ActContent("Avulsion de 2 canines permanentes  retenues ou à l'état de germe", 156.75));
		builtEntries.put(new ActCode("HBGD016"), new ActContent("Avulsion d'une racine incluse", 83.60));
		builtEntries.put(new ActCode("HBGD017"), new ActContent("Avulsion d'une dent ectopique", 167.20));
		builtEntries.put(new ActCode("HBGD018"), new ActContent("Avulsion d'une troisième molaire maxillaire retenue ou à l'état de germe", 83.60));
		builtEntries.put(new ActCode("HBGD021"), new ActContent("Avulsion de 3 troisièmes molaires retenues ou à l'état de germe", 167.20));
		builtEntries.put(new ActCode("HBGD022"), new ActContent("Avulsion d'1 dent permanente sur arcade avec alvéolectomie", 33.44));
		builtEntries.put(new ActCode("HBGD025"), new ActContent("Avulsion de 2 troisièmes molaires retenues ou à l'état de germe", 125.40));
		builtEntries.put(new ActCode("HBGD026"), new ActContent("Avulsion de 2 dents temporaires retenues, incluses ou réincluses", 125.40));
		builtEntries.put(new ActCode("HBGD027"), new ActContent("Ablation  d'une prothèse dentaire scellée unitaire", 38.70));
		builtEntries.put(new ActCode("HBGD028"), new ActContent("Avulsion d'une incisive permanente retenue ou à l'état de germe", 83.60));
		builtEntries.put(new ActCode("HBGD030"), new ActContent("Désobturation endodontique d'une incisive ou d'une canine", 0));
		builtEntries.put(new ActCode("HBGD031"), new ActContent("Avulsion d'1 dent permanente sur arcade avec séparation des racines", 33.44));
		builtEntries.put(new ActCode("HBGD032"), new ActContent("Avulsion de 2 dents permanentes sur arcade avec séparation des racines", 50.16));
		builtEntries.put(new ActCode("HBGD033"), new ActContent("Désobturation endodontique d'une molaire", 0));
		builtEntries.put(new ActCode("HBGD034"), new ActContent("Avulsion de 2 dents permanentes sur arcade avec alvéolectomie", 50.16));
		builtEntries.put(new ActCode("HBGD035"), new ActContent("Avulsion d'1 dent temporaire sur arcade", 16.72));
		builtEntries.put(new ActCode("HBGD036"), new ActContent("Avulsion d'1 dent permanente sur arcade sans alvéolectomie", 33.44));
		builtEntries.put(new ActCode("HBGD037"), new ActContent("Avulsion de 2 dents temporaires sur arcade", 25.08));
		builtEntries.put(new ActCode("HBGD038"), new ActContent("Avulsion de 4 troisièmes molaires retenues ou à l'état de germe", 209.00));
		builtEntries.put(new ActCode("HBGD039"), new ActContent("Avulsion d'1 dent ankylosée sur arcade, avec section coronoradiculaire et séparation des racines", 33.44));
		builtEntries.put(new ActCode("HBGD040"), new ActContent("Avulsion de plusieurs dents surnuméraires à l'état de germe ou de plusieurs odontoïdes", 125.40));
		builtEntries.put(new ActCode("HBGD042"), new ActContent("Avulsion d'1 dent temporaire retenue, incluse ou réincluse", 83.60));
		builtEntries.put(new ActCode("HBGD043"), new ActContent("Avulsion de 2 dents permanentes sur arcade sans alvéolectomie", 50.16));
		builtEntries.put(new ActCode("HBGD044"), new ActContent("Avulsion d'une dent à couronne sousmuqueuse ou en désinclusion muqueuse", 41.80));
		builtEntries.put(new ActCode("HBGD047"), new ActContent("Avulsion d'une première ou d'une deuxième molaire permanente retenue ou à l'état de germe", 83.60));
		builtEntries.put(new ActCode("HBGD054"), new ActContent("Avulsion de 12 dents temporaires sur arcade", 108.68));
		builtEntries.put(new ActCode("HBGD057"), new ActContent("Avulsion de 15 dents temporaires sur arcade", 133.76));
		builtEntries.put(new ActCode("HBGD064"), new ActContent("Avulsion de 10 dents permanentes sur arcade sans alvéolectomie", 183.92));
		builtEntries.put(new ActCode("HBGD065"), new ActContent("Avulsion de 5 dents temporaires sur arcade", 50.16));
		builtEntries.put(new ActCode("HBGD076"), new ActContent("Avulsion de 7 dents permanentes sur arcade sans alvéolectomie", 133.76));
		builtEntries.put(new ActCode("HBGD093"), new ActContent("Avulsion de 10 dents temporaires sur arcade", 91.96));
		builtEntries.put(new ActCode("HBGD106"), new ActContent("Avulsion de 6 dents permanentes sur arcade sans alvéolectomie", 117.04));
		builtEntries.put(new ActCode("HBGD111"), new ActContent("Avulsion de 13 dents temporaires sur arcade", 117.04));
		builtEntries.put(new ActCode("HBGD123"), new ActContent("Avulsion de 17 dents temporaires sur arcade", 150.48));
		builtEntries.put(new ActCode("HBGD133"), new ActContent("Avulsion de 16 dents temporaires sur arcade", 142.12));
		builtEntries.put(new ActCode("HBGD146"), new ActContent("Avulsion de 12 dents permanentes sur arcade sans alvéolectomie", 217.36));
		builtEntries.put(new ActCode("HBGD174"), new ActContent("Avulsion de 14 dents temporaires sur arcade", 125.40));
		builtEntries.put(new ActCode("HBGD193"), new ActContent("Avulsion de 28 dents permanentes sur arcade sans alvéolectomie", 484.88));
		builtEntries.put(new ActCode("HBGD197"), new ActContent("Avulsion de 15 dents permanente sur arcade sans alvéolectomie", 267.52));
		builtEntries.put(new ActCode("HBGD201"), new ActContent("Avulsion de 20 dents temporaires sur arcade", 175.56));
		builtEntries.put(new ActCode("HBGD233"), new ActContent("Désobturation endodontique d'une première prémolaire maxillaire", 0));
		builtEntries.put(new ActCode("HBGD235"), new ActContent("Avulsion de 23 dents permanentes sur arcade sans alvéolectomie", 401.28));
		builtEntries.put(new ActCode("HBGD245"), new ActContent("Avulsion de 31 dents permanentes sur arcade sans alvéolectomie", 535.04));
		builtEntries.put(new ActCode("HBGD247"), new ActContent("Avulsion de 14 dents permanentes sur arcade sans alvéolectomie", 250.80));
		builtEntries.put(new ActCode("HBGD258"), new ActContent("Avulsion de 21 dents permanentes sur arcade sans alvéolectomie", 367.84));
		builtEntries.put(new ActCode("HBGD261"), new ActContent("Avulsion de 17 dents permanentes sur arcade sans alvéolectomie", 300.96));
		builtEntries.put(new ActCode("HBGD263"), new ActContent("Avulsion de 8 dents temporaires sur arcade", 75.24));
		builtEntries.put(new ActCode("HBGD278"), new ActContent("Avulsion de 20 dents permanentes sur arcade sans alvéolectomie", 351.12));
		builtEntries.put(new ActCode("HBGD280"), new ActContent("Avulsion de 9 dents temporaires sur arcade", 83.60));
		builtEntries.put(new ActCode("HBGD282"), new ActContent("Avulsion de19 dents temporaires sur arcade", 167.20));
		builtEntries.put(new ActCode("HBGD283"), new ActContent("Avulsion de 32 dents permanentes sur arcade sans alvéolectomie", 551.76));
		builtEntries.put(new ActCode("HBGD284"), new ActContent("Avulsion de 4 dents temporaires sur arcade", 41.80));
		builtEntries.put(new ActCode("HBGD285"), new ActContent("Avulsion de 26 dents permanentes sur arcade sans alvéolectomie", 451.44));
		builtEntries.put(new ActCode("HBGD287"), new ActContent("Avulsion de 3 dents permanentes sur arcade avec alvéolectomie", 66.88));
		builtEntries.put(new ActCode("HBGD309"), new ActContent("Avulsion de 3 dents temporaires sur arcade", 33.44));
		builtEntries.put(new ActCode("HBGD311"), new ActContent("Avulsion de 22 dents permanentes sur arcade sans alvéolectomie", 384.56));
		builtEntries.put(new ActCode("HBGD319"), new ActContent("Avulsion de 3 dents permanentes sur arcade sans alvéolectomie", 66.88));
		builtEntries.put(new ActCode("HBGD333"), new ActContent("Avulsion de 16 dents permanente sur arcade sans alvéolectomie", 284.24));
		builtEntries.put(new ActCode("HBGD338"), new ActContent("Avulsion de 27 dents permanentes sur arcade sans alvéolectomie", 468.16));
		builtEntries.put(new ActCode("HBGD345"), new ActContent("Avulsion de 29 dents permanentes sur arcade sans alvéolectomie", 501.60));
		builtEntries.put(new ActCode("HBGD356"), new ActContent("Avulsion de 11 dents permanentes sur arcade sans alvéolectomie", 200.64));
		builtEntries.put(new ActCode("HBGD362"), new ActContent("Avulsion de 11 dents temporaires sur arcade", 100.32));
		builtEntries.put(new ActCode("HBGD374"), new ActContent("Avulsion de 24 dents permanentes sur arcade sans alvéolectomie", 418.00));
		builtEntries.put(new ActCode("HBGD382"), new ActContent("Avulsion de 13 dents permanentes sur arcade sans alvéolectomie", 234.08));
		builtEntries.put(new ActCode("HBGD386"), new ActContent("Avulsion de 2 prémolaires retenues ou à l'état de germe", 125.40));
		builtEntries.put(new ActCode("HBGD414"), new ActContent("Avulsion de 30 dents permanentes sur arcade sans alvéolectomie", 518.32));
		builtEntries.put(new ActCode("HBGD420"), new ActContent("Avulsion de 9 dents permanentes sur arcade sans alvéolectomie", 167.20));
		builtEntries.put(new ActCode("HBGD422"), new ActContent("Avulsion de 8 dents permanentes sur arcade sans alvéolectomie", 150.48));
		builtEntries.put(new ActCode("HBGD459"), new ActContent("Avulsion d'une prémolaire retenue ou à l'état de germe ", 83.60));
		builtEntries.put(new ActCode("HBGD461"), new ActContent("Avulsion de 19 dents permanentes sur arcade sans alvéolectomie", 334.40));
		builtEntries.put(new ActCode("HBGD462"), new ActContent("Avulsion de 6 dents temporaires sur arcade", 58.52));
		builtEntries.put(new ActCode("HBGD464"), new ActContent("Avulsion de 7 dents temporaires sur arcade", 66.88));
		builtEntries.put(new ActCode("HBGD468"), new ActContent("Avulsion de 18 dents temporaires sur arcade", 158.84));
		builtEntries.put(new ActCode("HBGD475"), new ActContent("Avulsion de 25 dents permanentes sur arcade sans alvéolectomie", 434.72));
		builtEntries.put(new ActCode("HBGD489"), new ActContent("Avulsion de 4 dents permanentes sur arcade sans alvéolectomie", 83.60));
		builtEntries.put(new ActCode("HBGD497"), new ActContent("Avulsion de 5 dents permanentes sur arcade sans alvéolectomie", 100.32));
		builtEntries.put(new ActCode("HBGD499"), new ActContent("Avulsion de 18 dents permanentes sur arcade sans alvéolectomie", 317.68));
		builtEntries.put(new ActCode("HBJD001"), new ActContent("Détartrage et polissage des dents", 28.92));
		builtEntries.put(new ActCode("HBKD005"), new ActContent("Changement de dispositif d'attachement d'une prothèse dentaire amovible supra implantaire", 32.25));
		builtEntries.put(new ActCode("HBKD140"), new ActContent("Changement de 7 facettes d'une prothèse dentaire amovible ", 120.40));
		builtEntries.put(new ActCode("HBKD212"), new ActContent("Changement de 4 facettes d'une prothèse dentaire amovible ", 68.80));
		builtEntries.put(new ActCode("HBKD213"), new ActContent("Changement de 6 facettes d'une prothèse dentaire amovible ", 103.20));
		builtEntries.put(new ActCode("HBKD244"), new ActContent("Changement de 8 facettes d'une prothèse dentaire amovible ", 137.60));
		builtEntries.put(new ActCode("HBKD300"), new ActContent("Changement de 3 facettes d'une prothèse dentaire amovible ", 51.60));
		builtEntries.put(new ActCode("HBKD396"), new ActContent("Changement d'1 facette d'une prothèse dentaire amovible", 17.20));
		builtEntries.put(new ActCode("HBKD431"), new ActContent("Changement de 2 facettes d'une prothèse dentaire amovible ", 34.40));
		builtEntries.put(new ActCode("HBKD462"), new ActContent("Changement de 5 facettes d'une prothèse dentaire amovible ", 86.00));
		builtEntries.put(new ActCode("HBLD001"), new ActContent("Pose d'un arc de maintien d'espace interdentaire sans dent prothétique", 0));
		builtEntries.put(new ActCode("HBLD002"), new ActContent("Pose d'un mainteneur d'espace interdentaire amovible passif", 0));
		builtEntries.put(new ActCode("HBLD003"), new ActContent("Pose d'un arc de maintien d'espace interdentaire avec dent prothétique", 0));
		builtEntries.put(new ActCode("HBLD004"), new ActContent("Séance d'application topique intrabuccale de fluorures", 0));
		builtEntries.put(new ActCode("HBLD005"), new ActContent("Pose d'infrastructure coronaire sur 5 implants ou plus", 0));
		builtEntries.put(new ActCode("HBLD006"), new ActContent("Pose d'un mainteneur d'espace interdentaire unitaire scellé", 0));
		builtEntries.put(new ActCode("HBLD007"), new ActContent("Pose d'une infrastructure coronoradiculaire sans clavette sur une dent [Inlay core]", 122.55));
		builtEntries.put(new ActCode("HBLD008"), new ActContent("Pose d'un attachement coronoradiculaire sur une dent", 0));
		builtEntries.put(new ActCode("HBLD009"), new ActContent("Application d'un topique pour hypersensibilité dentinaire", 0));
		builtEntries.put(new ActCode("HBLD012"), new ActContent("Pose d'une infrastructure coronaire sur 1 implant", 0));
		builtEntries.put(new ActCode("HBLD013"), new ActContent("Pose d'infrastructure coronaire sur 4 implants", 0));
		builtEntries.put(new ActCode("HBLD015"), new ActContent("Pose d'une coiffe de recouvrement d'une racine dentaire [Coping]", 0));
		builtEntries.put(new ActCode("HBLD017"), new ActContent("Pose d'infrastructure coronaire sur 2 implants", 0));
		builtEntries.put(new ActCode("HBLD018"), new ActContent("Pose d'un plan de libération occlusale", 172.80));
		builtEntries.put(new ActCode("HBLD019"), new ActContent("Pose d'un plan de guidage des mouvements antéropostérieurs mandibulaires", 0));
		builtEntries.put(new ActCode("HBLD020"), new ActContent("Pose d'un appareil de posture mandibulaire [cale]", 0));
		builtEntries.put(new ActCode("HBLD021"), new ActContent("Pose d'infrastructure coronaire sur 3 implants", 0));
		builtEntries.put(new ActCode("HBLD023"), new ActContent("Pose d'une prothèse plurale [bridge] comportant 2 piliers d'ancrage céramométalliques ou en équivalents minéraux et 1 élément intermédiaire céramométallique ou en équivalents minéraux", 279.50));
		builtEntries.put(new ActCode("HBLD030"), new ActContent("Pose d'une prothèse dentaire complète transvissée implantoportée", 182.75));
		builtEntries.put(new ActCode("HBLD031"), new ActContent("Pose d'une prothèse amovible définitive complète unimaxillaire à plaque base résine", 182.75));
		builtEntries.put(new ActCode("HBLD032"), new ActContent("Pose d'une prothèse amovible de transition complète unimaxillaire à plaque base résine", 182.75));
		builtEntries.put(new ActCode("HBLD033"), new ActContent("Pose d'une prothèse plurale [bridge] comportant 2 piliers d'ancrage métalliques et 1 élément intermédiaire métallique", 279.50));
		builtEntries.put(new ActCode("HBLD034"), new ActContent("Pose d'une prothèse dentaire plurale transitoire ", 0));
		builtEntries.put(new ActCode("HBLD035"), new ActContent("Pose d'une prothèse amovible définitive complète bimaxillaire à plaque base résine", 365.50));
		builtEntries.put(new ActCode("HBLD036"), new ActContent("Pose d'une couronne dentaire dentoportée céramométallique ou en équivalents minéraux ", 107.50));
		builtEntries.put(new ActCode("HBLD037"), new ActContent("Pose d'une couronne dentaire transitoire ", 0));
		builtEntries.put(new ActCode("HBLD038"), new ActContent("Pose d'une couronne dentaire dentoportée métallique ", 107.50));
		builtEntries.put(new ActCode("HBLD040"), new ActContent("Pose d'une prothèse plurale [bridge] comportant 1 pilier d'ancrage métallique, 1 pilier d'ancrage céramométallique ou en équivalents minéraux, et 1 élément intermédiaire métallique", 279.50));
		builtEntries.put(new ActCode("HBLD043"), new ActContent("Pose d'une prothèse plurale [bridge] comportant 1 pilier d'ancrage métallique, 1 pilier d'ancrage céramométallique ou en équivalents minéraux, et 1 élément intermédiaire céramométallique ou en équivalents minéraux", 279.50));
		builtEntries.put(new ActCode("HBLD045"), new ActContent("Application dentaire d'un vernis de reminéralisation sur une arcade", 0));
		builtEntries.put(new ActCode("HBLD046"), new ActContent("Pose d'une prothèse amovible définitive complète bimaxillaire à châssis métallique", 623.50));
		builtEntries.put(new ActCode("HBLD047"), new ActContent("Pose d'une prothèse amovible définitive complète unimaxillaire à châssis métallique", 311.75));
		builtEntries.put(new ActCode("HBLD048"), new ActContent("Pose d'une prothèse amovible définitive complète unimaxillaire à plaque base résine et d'une prothèse amovible définitive complète unimaxillaire à châssis métallique", 494.50));
		builtEntries.put(new ActCode("HBLD050"), new ActContent("Pose d'un dispositif unimaxillaire de contention extracoronaire par attelle composite collée, sur 7 dents ou plus", 0));
		builtEntries.put(new ActCode("HBLD051"), new ActContent("Pose d'un dispositif unimaxillaire de contention extracoronaire par attelle métallique coulée et collée, sur 7 dents ou plus", 96.40));
		builtEntries.put(new ActCode("HBLD052"), new ActContent("Pose d'un dispositif unimaxillaire de contention extracoronaire par attelle composite collée, sur 1 à 6 dents", 0));
		builtEntries.put(new ActCode("HBLD053"), new ActContent("Pose d'un dispositif unimaxillaire de contention extracoronaire par attelle métallique coulée et collée, sur 1 à 6 dents", 96.40));
		builtEntries.put(new ActCode("HBLD075"), new ActContent("Pose d'une prothèse amovible définitive à châssis métallique, comportant 7 dents", 236.50));
		builtEntries.put(new ActCode("HBLD079"), new ActContent("Pose d'une prothèse amovible définitive à châssis métallique, comportant 10 dents", 268.75));
		builtEntries.put(new ActCode("HBLD083"), new ActContent("Pose d'une prothèse amovible définitive à plaque base résine, comportant 11 dents", 150.50));
		builtEntries.put(new ActCode("HBLD101"), new ActContent("Pose d'une prothèse amovible définitive à plaque base résine, comportant 9 dents", 129.00));
		builtEntries.put(new ActCode("HBLD112"), new ActContent("Pose d'une prothèse amovible définitive à châssis métallique, comportant 12 dents", 290.25));
		builtEntries.put(new ActCode("HBLD118"), new ActContent("Pose d'une prothèse amovible supra-implantaire complète unimaxillaire à plaque base résine", 182.75));
		builtEntries.put(new ActCode("HBLD123"), new ActContent("Pose d'une prothèse amovible de transition à plaque base résine, comportant 7 dents", 107.50));
		builtEntries.put(new ActCode("HBLD131"), new ActContent("Pose d'une prothèse amovible définitive à châssis métallique, comportant 1 à 3 dents", 193.50));
		builtEntries.put(new ActCode("HBLD132"), new ActContent("Pose d'une prothèse amovible supra-implantaire à plaque résine comportant moins de 9 dents ", 102.13));
		builtEntries.put(new ActCode("HBLD138"), new ActContent("Pose d'une prothèse amovible définitive à plaque base résine, comportant 10 dents", 139.75));
		builtEntries.put(new ActCode("HBLD148"), new ActContent("Pose d'une prothèse amovible de transition à plaque base résine, comportant 9 dents", 129.00));
		builtEntries.put(new ActCode("HBLD171"), new ActContent("Pose d'une prothèse amovible supra-implantaire complète bimaxillaire à chassis métallique ", 623.50));
		builtEntries.put(new ActCode("HBLD199"), new ActContent("Pose d'une prothèse amovible supra-implantaire complète bimaxillaire à plaque base résine", 365.50));
		builtEntries.put(new ActCode("HBLD203"), new ActContent("Pose d'une prothèse amovible définitive à châssis métallique, comportant 11 dents", 279.50));
		builtEntries.put(new ActCode("HBLD215"), new ActContent("Pose d'une prothèse amovible de transition à plaque base résine, comportant 11 dents", 150.50));
		builtEntries.put(new ActCode("HBLD217"), new ActContent("Pose d'une prothèse amovible supra-implantaire complète unimaxillaire à chassis métallique", 311.75));
		builtEntries.put(new ActCode("HBLD224"), new ActContent("Pose d'une prothèse amovible de transition à plaque base résine, comportant 5 dents", 86.00));
		builtEntries.put(new ActCode("HBLD231"), new ActContent("Pose d'une prothèse amovible de transition à plaque base résine, comportant 10 dents", 139.75));
		builtEntries.put(new ActCode("HBLD232"), new ActContent("Pose d'une prothèse amovible de transition à plaque base résine, comportant 13 dents", 172.00));
		builtEntries.put(new ActCode("HBLD236"), new ActContent("Pose d'une prothèse amovible supra-implantaire à chassis métallique  comportant de 9 à 13 dents ", 279.50));
		builtEntries.put(new ActCode("HBLD240"), new ActContent("Pose d'une prothèse amovible supra-implantaire à chassis métallique  comportant moins de 9 dents ", 236.50));
		builtEntries.put(new ActCode("HBLD261"), new ActContent("Pose d'une infrastructure coronoradiculaire avec clavette sur une dent [Inlay core à clavette]", 144.05));
		builtEntries.put(new ActCode("HBLD262"), new ActContent("Pose d'une prothèse amovible de transition à plaque base résine, comportant 12 dents", 161.25));
		builtEntries.put(new ActCode("HBLD270"), new ActContent("Pose d'une prothèse amovible de transition à plaque base résine, comportant 8 dents", 118.25));
		builtEntries.put(new ActCode("HBLD308"), new ActContent("Pose d'une prothèse amovible définitive à châssis métallique, comportant 13 dents", 301.00));
		builtEntries.put(new ActCode("HBLD332"), new ActContent("Pose d'une prothèse amovible définitive à châssis métallique, comportant 4 dents", 204.25));
		builtEntries.put(new ActCode("HBLD349"), new ActContent("Pose d'une prothèse amovible définitive à plaque base résine, comportant 13 dents", 172.00));
		builtEntries.put(new ActCode("HBLD364"), new ActContent("Pose d'une prothèse amovible de transition à plaque base résine, comportant 1 à 3 dents", 64.50));
		builtEntries.put(new ActCode("HBLD370"), new ActContent("Pose d'une prothèse amovible définitive à plaque base résine, comportant 12 dents", 161.25));
		builtEntries.put(new ActCode("HBLD371"), new ActContent("Pose d'une prothèse amovible de transition à plaque base résine, comportant 6 dents", 96.75));
		builtEntries.put(new ActCode("HBLD418"), new ActContent("Pose d'une couronne dentaire implantoportée", 107.50));
		builtEntries.put(new ActCode("HBLD435"), new ActContent("Pose d'une prothèse amovible définitive à châssis métallique, comportant 9 dents", 258.00));
		builtEntries.put(new ActCode("HBLD452"), new ActContent("Pose d'une prothèse amovible définitive à châssis métallique, comportant 5 dents", 215.00));
		builtEntries.put(new ActCode("HBLD470"), new ActContent("Pose d'une prothèse amovible définitive à châssis métallique, comportant 8 dents", 247.25));
		builtEntries.put(new ActCode("HBLD474"), new ActContent("Pose d'une prothèse amovible définitive à châssis métallique, comportant 6 dents", 225.75));
		builtEntries.put(new ActCode("HBLD476"), new ActContent("Pose d'une prothèse amovible de transition à plaque base résine, comportant 4 dents", 75.25));
		builtEntries.put(new ActCode("HBLD492"), new ActContent("Pose d'une prothèse amovible supra-implantaire à plaque base résine, comportant de 9 à 13 dents", 150.50));
		builtEntries.put(new ActCode("HBMD001"), new ActContent("Eclaircissement de dent dépulpée", 0));
		builtEntries.put(new ActCode("HBMD002"), new ActContent("Réparation d'une fracture de châssis métallique de prothèse dentaire amovible, avec remontage d'1 élément", 38.70));
		builtEntries.put(new ActCode("HBMD003"), new ActContent("Séance de renouvellement de l'obturation radiculaire d'une dent permanente immature à l'hydroxyde de calcium", 0));
		builtEntries.put(new ActCode("HBMD004"), new ActContent("Réfection de la base d'une prothèse dentaire amovible complète", 0));
		builtEntries.put(new ActCode("HBMD005"), new ActContent("Eclaircissement des dents pulpées", 0));
		builtEntries.put(new ActCode("HBMD007"), new ActContent("Réfection des bords et/ou de l'intrados d'une prothèse dentaire amovible partielle", 0));
		builtEntries.put(new ActCode("HBMD008"), new ActContent("Réparation d'une fracture de châssis métallique de prothèse dentaire amovible, sans démontage d'éléments", 32.25));
		builtEntries.put(new ActCode("HBMD009"), new ActContent("Rescellement et/ou recollage de 3 couronnes ou plus ou de 3 ancrages ou plus d'une prothèse dentaire fixée", 0));
		builtEntries.put(new ActCode("HBMD016"), new ActContent("Rescellement et/ou recollage d'une ou deux couronnes ou d'un ou deux ancrages d'une prothèse dentaire fixée", 0));
		builtEntries.put(new ActCode("HBMD017"), new ActContent("Adjonction ou changement d'1 élément d'une prothèse dentaire amovible ", 21.50));
		builtEntries.put(new ActCode("HBMD019"), new ActContent("Révision des piliers implantoportés d'une prothèse dentaire", 18.81));
		builtEntries.put(new ActCode("HBMD020"), new ActContent("Réparation d'une prothèse dentaire amovible en résine, fêlée ou fracturée", 21.50));
		builtEntries.put(new ActCode("HBMD038"), new ActContent("Restauration d'une dent d'un secteur prémolomolaire sur 3 faces ou plus par matériau inséré en phase plastique sans ancrage radiculaire", 40.97));
		builtEntries.put(new ActCode("HBMD042"), new ActContent("Restauration d'une dent par matériau inséré en phase plastique avec ancrage radiculaire", 79.53));
		builtEntries.put(new ActCode("HBMD043"), new ActContent("Restauration d'une dent sur 1 face par matériau incrusté [inlay-onlay]", 19.28));
		builtEntries.put(new ActCode("HBMD044"), new ActContent("Restauration d'une dent d'un secteur incisivocanin sur 1 angle par matériau inséré en phase plastique, sans ancrage radiculaire", 43.00));
		builtEntries.put(new ActCode("HBMD046"), new ActContent("Restauration d'une dent sur 2 faces par matériau incrusté [inlay-onlay]", 33.74));
		builtEntries.put(new ActCode("HBMD047"), new ActContent("Restauration d'une dent d'un secteur incisivocanin sur 2 angles par matériau inséré en phase plastique, sans ancrage radiculaire", 86.00));
		builtEntries.put(new ActCode("HBMD048"), new ActContent("Pose d'une facette céramique ou en équivalents minéraux sur une dent d'un secteur incisivocanin", 0));
		builtEntries.put(new ActCode("HBMD049"), new ActContent("Restauration d'une dent d'un secteur prémolomolaire sur 2 faces par matériau inséré en phase plastique sans ancrage radiculaire", 33.74));
		builtEntries.put(new ActCode("HBMD050"), new ActContent("Restauration d'une dent d'un secteur incisivocanin sur 2 faces par matériau inséré en phase plastique sans ancrage radiculaire", 33.74));
		builtEntries.put(new ActCode("HBMD053"), new ActContent("Restauration d'une dent d'un secteur prémolomolaire sur 1 face par matériau inséré en phase plastique, sans ancrage radiculaire", 19.28));
		builtEntries.put(new ActCode("HBMD054"), new ActContent("Restauration d'une dent d'un secteur incisivocanin sur 3 faces ou plus par matériau inséré en phase plastique sans ancrage radiculaire", 40.97));
		builtEntries.put(new ActCode("HBMD055"), new ActContent("Restauration d'une dent sur 3 faces ou plus par matériau incrusté [inlay-onlay]", 40.97));
		builtEntries.put(new ActCode("HBMD058"), new ActContent("Restauration d'une dent d'un secteur incisivocanin sur 1 face par matériau inséré en phase plastique, sans ancrage radiculaire", 19.28));
		builtEntries.put(new ActCode("HBMD061"), new ActContent("Séance d'ajustement occlusal par coronoplastie", 0));
		builtEntries.put(new ActCode("HBMD076"), new ActContent("Réparation de l'artifice cosmétique d'une dent prothétique par technique directe", 0));
		builtEntries.put(new ActCode("HBMD079"), new ActContent("Réparation de l'artifice cosmétique d'une dent prothétique par technique indirecte", 0));
		builtEntries.put(new ActCode("HBMD110"), new ActContent("Réparation d'une fracture de châssis métallique de prothèse dentaire amovible, avec remontage de 4 éléments", 58.05));
		builtEntries.put(new ActCode("HBMD114"), new ActContent("Adjonction ou changement de 2 éléments d'une prothèse dentaire amovible", 32.25));
		builtEntries.put(new ActCode("HBMD134"), new ActContent("Adjonction ou changement de 13 éléments d'une prothèse dentaire amovible", 150.50));
		builtEntries.put(new ActCode("HBMD174"), new ActContent("Adjonction ou changement de 14 éléments d'une prothèse dentaire amovible", 161.25));
		builtEntries.put(new ActCode("HBMD188"), new ActContent("Adjonction ou changement de 3 éléments soudés d'une prothèse dentaire amovible sur châssis métallique", 129.00));
		builtEntries.put(new ActCode("HBMD198"), new ActContent("Adjonction ou changement de 6 éléments d'une prothèse dentaire amovible", 75.25));
		builtEntries.put(new ActCode("HBMD200"), new ActContent("Adjonction ou changement de 13 éléments soudés d'une prothèse dentaire amovible sur châssis métallique", 559.00));
		builtEntries.put(new ActCode("HBMD226"), new ActContent("Adjonction ou changement de 11 éléments d'une prothèse dentaire amovible", 129.00));
		builtEntries.put(new ActCode("HBMD228"), new ActContent("Adjonction ou changement de 8 éléments d'une prothèse dentaire amovible", 96.75));
		builtEntries.put(new ActCode("HBMD245"), new ActContent("Adjonction ou changement de 5 éléments d'une prothèse dentaire amovible", 64.50));
		builtEntries.put(new ActCode("HBMD249"), new ActContent("Adjonction ou changement d'1 élément soudé sur une prothèse dentaire amovible sur châssis métallique", 43.00));
		builtEntries.put(new ActCode("HBMD281"), new ActContent("Adjonction ou changement de 12 éléments soudés d'une prothèse dentaire amovible sur châssis métallique", 516.00));
		builtEntries.put(new ActCode("HBMD283"), new ActContent("Adjonction ou changement de 5 éléments soudés d'une prothèse dentaire amovible sur châssis métallique", 215.00));
		builtEntries.put(new ActCode("HBMD286"), new ActContent("Adjonction ou changement de 9 éléments d'une prothèse dentaire amovible", 107.50));
		builtEntries.put(new ActCode("HBMD289"), new ActContent("Réparation d'une fracture de châssis métallique de prothèse dentaire amovible, avec remontage de 13 éléments", 116.10));
		builtEntries.put(new ActCode("HBMD292"), new ActContent("Adjonction ou changement de 2 éléments soudés d'une prothèse dentaire amovible sur châssis métallique", 86.00));
		builtEntries.put(new ActCode("HBMD298"), new ActContent("Adjonction ou changement de 14 éléments soudés d'une prothèse dentaire amovible sur châssis métallique", 602.00));
		builtEntries.put(new ActCode("HBMD312"), new ActContent("Réparation d'une fracture de châssis métallique de prothèse dentaire amovible, avec remontage de 12 éléments", 109.65));
		builtEntries.put(new ActCode("HBMD322"), new ActContent("Adjonction ou changement de 3 éléments d'une prothèse dentaire amovible", 43.00));
		builtEntries.put(new ActCode("HBMD329"), new ActContent("Adjonction ou changement de 10 éléments d'une prothèse dentaire amovible", 118.25));
		builtEntries.put(new ActCode("HBMD339"), new ActContent("Réparation d'une fracture de châssis métallique de prothèse dentaire amovible, avec remontage de 7 éléments", 77.40));
		builtEntries.put(new ActCode("HBMD349"), new ActContent("Réparation d'une fracture de châssis métallique de prothèse dentaire amovible, avec remontage de 5 éléments", 64.50));
		builtEntries.put(new ActCode("HBMD373"), new ActContent("Adjonction ou changement de 7 éléments d'une prothèse dentaire amovible", 86.00));
		builtEntries.put(new ActCode("HBMD386"), new ActContent("Réparation d'une fracture de châssis métallique de prothèse dentaire amovible, avec remontage de 6 éléments", 70.95));
		builtEntries.put(new ActCode("HBMD387"), new ActContent("Adjonction ou changement de 12 éléments d'une prothèse dentaire amovible", 139.75));
		builtEntries.put(new ActCode("HBMD400"), new ActContent("Réparation d'une fracture de châssis métallique de prothèse dentaire amovible, avec remontage de 14 éléments", 122.55));
		builtEntries.put(new ActCode("HBMD404"), new ActContent("Adjonction ou changement de 4 éléments d'une prothèse dentaire amovible", 53.75));
		builtEntries.put(new ActCode("HBMD410"), new ActContent("Adjonction ou changement de 10 éléments soudés d'une prothèse dentaire amovible sur châssis métallique", 430.00));
		builtEntries.put(new ActCode("HBMD425"), new ActContent("Adjonction ou changement de 7 éléments soudés d'une prothèse dentaire amovible sur châssis métallique", 301.00));
		builtEntries.put(new ActCode("HBMD429"), new ActContent("Adjonction ou changement de 11 éléments soudés d'une prothèse dentaire amovible sur châssis métallique", 473.00));
		builtEntries.put(new ActCode("HBMD432"), new ActContent("Adjonction ou changement de 4 éléments soudés d'une prothèse dentaire amovible sur châssis métallique", 172.00));
		builtEntries.put(new ActCode("HBMD438"), new ActContent("Réparation d'une fracture de châssis métallique de prothèse dentaire amovible, avec remontage de 9 éléments", 90.30));
		builtEntries.put(new ActCode("HBMD439"), new ActContent("Adjonction ou changement de 6 éléments soudés d'une prothèse dentaire amovible sur châssis métallique", 258.00));
		builtEntries.put(new ActCode("HBMD444"), new ActContent("Adjonction ou changement de 8 éléments soudés d'une prothèse dentaire amovible sur châssis métallique", 344.00));
		builtEntries.put(new ActCode("HBMD449"), new ActContent("Réparation d'une fracture de châssis métallique de prothèse dentaire amovible, avec remontage de 11 éléments", 103.20));
		builtEntries.put(new ActCode("HBMD459"), new ActContent("Réparation d'une fracture de châssis métallique de prothèse dentaire amovible, avec remontage de 8 éléments", 83.85));
		builtEntries.put(new ActCode("HBMD469"), new ActContent("Réparation d'une fracture de châssis métallique de prothèse dentaire amovible, avec remontage de 3 éléments", 51.60));
		builtEntries.put(new ActCode("HBMD481"), new ActContent("Réparation d'une fracture de châssis métallique de prothèse dentaire amovible, avec remontage de 10 éléments", 96.75));
		builtEntries.put(new ActCode("HBMD485"), new ActContent("Adjonction ou changement de 9 éléments soudés d'une prothèse dentaire amovible sur châssis métallique", 387.00));
		builtEntries.put(new ActCode("HBMD488"), new ActContent("Réparation d'une fracture de châssis métallique de prothèse dentaire amovible, avec remontage de 2 éléments", 45.15));
		builtEntries.put(new ActCode("HBPA001"), new ActContent("Dégagement d'une dent retenue ou incluse, avec pose d'un dispositif de traction orthodontique et aménagement parodontal par greffe ou lambeau", 146.30));
		builtEntries.put(new ActCode("HBPD001"), new ActContent("Dégagement de plusieurs dents retenues ou incluses avec pose de dispositif de traction orthodontique", 156.75));
		builtEntries.put(new ActCode("HBPD002"), new ActContent("Dégagement d'une dent retenue ou incluse avec pose d'un dispositif de traction orthodontique sans aménagement parodontal", 104.50));
		builtEntries.put(new ActCode("LBGD001"), new ActContent("Ablation de moyen de contention maxillaire et/ou mandibulaire intrabuccal", 0));
		return builtEntries;
	}
	static private Map<ActCode, ActContent> entries;
	private ActsData(){}
}
